$axure.loadCurrentPage({
  "url":"余额_收入详情.html",
  "generationDate":new Date(1661406628405.14),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"32fd4a5bad5242ef987d9897fdcee850",
    "type":"Axure:Page",
    "name":"余额/收入详情",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"2cc223d7df8e48ccb3aa76a4cc9bab3b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":15,
              "y":40},
            "size":{
              "width":817,
              "height":240}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d94e6a21490f483ebfd19ee7f50cb18d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":15,
                  "y":40},
                "size":{
                  "width":817,
                  "height":240}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/余额_收入详情/u0.png"}},
{
          "id":"8a43888ae51f41d486797df621f65368",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":32,
              "y":97},
            "size":{
              "width":735,
              "height":93}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b2795915966c455aafa60c0db8f28695",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "size":{
                  "width":80,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"eb64184c17ed44b7a07e07ea2fbf99e7",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":80,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/余额_收入详情/u3.png"}},
{
              "id":"4997e7e250d3479c808f3187c9a1a732",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":20},
                "size":{
                  "width":80,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"dbdb55e7abbe48d0a12ac22fa2ca3498",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":20},
                    "size":{
                      "width":80,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/余额_收入详情/u25.png"}},
{
              "id":"634cd73b950d4bc7bc0bdd9845de1c39",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":56},
                "size":{
                  "width":80,
                  "height":37}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"9c428be74342428ea1d625a6674be9c5",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":56},
                    "size":{
                      "width":80,
                      "height":37}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/余额_收入详情/u47.png"}},
{
              "id":"c024f04c9adf4d0ca0264dad81fe9d2e",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":80,
                  "y":0},
                "size":{
                  "width":80,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"1a1d3e0a38da4119a3402ebf58dfd976",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":80,
                      "y":0},
                    "size":{
                      "width":80,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/余额_收入详情/u3.png"}},
{
              "id":"0e1f6511068548baabb534b90287ec59",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":80,
                  "y":20},
                "size":{
                  "width":80,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"bbb8055f782a4cfabb3dd03b96ffa7ca",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":80,
                      "y":20},
                    "size":{
                      "width":80,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/余额_收入详情/u25.png"}},
{
              "id":"0baaef8fa83642a380bcb070b622d174",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":80,
                  "y":56},
                "size":{
                  "width":80,
                  "height":37}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"eb1cc031773f40bfa0827cf5644afd94",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":80,
                      "y":56},
                    "size":{
                      "width":80,
                      "height":37}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/余额_收入详情/u47.png"}},
{
              "id":"1c3e479ff0014fa6894c35da398fa806",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":160,
                  "y":0},
                "size":{
                  "width":46,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"70459848ca6a451aa1f0c5a334e4b528",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":160,
                      "y":0},
                    "size":{
                      "width":46,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/余额_收入详情/u7.png"}},
{
              "id":"6c3713641688475fbc573c8fd73b44c3",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":160,
                  "y":20},
                "size":{
                  "width":46,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"b626df8bcf204ca1aa80d1ea5cd01466",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":160,
                      "y":20},
                    "size":{
                      "width":46,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/余额_收入详情/u29.png"}},
{
              "id":"ed4e6e4a14e847779de41aed5f3e5284",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":160,
                  "y":56},
                "size":{
                  "width":46,
                  "height":37}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"8a680abf77024aaa891c6fd73b430c6e",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":160,
                      "y":56},
                    "size":{
                      "width":46,
                      "height":37}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/余额_收入详情/u51.png"}},
{
              "id":"522e2bec4b0f45fca07a48150d56d471",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":206,
                  "y":0},
                "size":{
                  "width":37,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"aa0aa9f90aba48fc84e2ab98d68216e4",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":206,
                      "y":0},
                    "size":{
                      "width":37,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/余额_收入详情/u9.png"}},
{
              "id":"bde48feab40840478c13e54f20ec8f2c",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":206,
                  "y":20},
                "size":{
                  "width":37,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"a8eab607c3964de195221a6bbff1371b",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":206,
                      "y":20},
                    "size":{
                      "width":37,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/余额_收入详情/u31.png"}},
{
              "id":"fd61660f138840a181e9a6eff7289353",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":206,
                  "y":56},
                "size":{
                  "width":37,
                  "height":37}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"a0bc81c7ab0c4b8ab1b89114958410b2",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":206,
                      "y":56},
                    "size":{
                      "width":37,
                      "height":37}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/余额_收入详情/u53.png"}},
{
              "id":"83078c12d48d423aa86891c19bd9d56a",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":243,
                  "y":0},
                "size":{
                  "width":88,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"1445432285dd4a408d3f43732a951655",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":243,
                      "y":0},
                    "size":{
                      "width":88,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/余额_收入详情/u11.png"}},
{
              "id":"be9c2d8927b64927a44b992ee35ecccc",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":243,
                  "y":20},
                "size":{
                  "width":88,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"4982f6513e744ebf81bffdef53e8faf6",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":243,
                      "y":20},
                    "size":{
                      "width":88,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/余额_收入详情/u33.png"}},
{
              "id":"52e489dab60f4c09b7b48110c311bd98",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":243,
                  "y":56},
                "size":{
                  "width":88,
                  "height":37}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"d9f5bdec7cf64e72a449c685aaf7d83f",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":243,
                      "y":56},
                    "size":{
                      "width":88,
                      "height":37}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/余额_收入详情/u55.png"}},
{
              "id":"3c04da74d5c540f7af2191cb41256271",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":331,
                  "y":0},
                "size":{
                  "width":85,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"8a07977a5a7f4e48a6fbf2825d07ec13",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":331,
                      "y":0},
                    "size":{
                      "width":85,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/余额_收入详情/u13.png"}},
{
              "id":"f7eedd6769d2473dbd8b0b99780f7706",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":331,
                  "y":20},
                "size":{
                  "width":85,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"5dc2eb8ef9ba4e4384e95c6add3d0cf8",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":331,
                      "y":20},
                    "size":{
                      "width":85,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/余额_收入详情/u35.png"}},
{
              "id":"4206401c890e4386880d8b34924d9a0b",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":331,
                  "y":56},
                "size":{
                  "width":85,
                  "height":37}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"00676fbeff824d769164fb55f9880ec9",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":331,
                      "y":56},
                    "size":{
                      "width":85,
                      "height":37}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/余额_收入详情/u57.png"}},
{
              "id":"9e72625b88164812aa4d4d41566e9ff4",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":416,
                  "y":0},
                "size":{
                  "width":82,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"f5e3c33db3d1446f8274b6046e64d420",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":416,
                      "y":0},
                    "size":{
                      "width":82,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/余额_收入详情/u15.png"}},
{
              "id":"70f1f82007a34abba8c35c0b28eddf49",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":416,
                  "y":20},
                "size":{
                  "width":82,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"95ebc69eecbc4e6bbc76e455ff17b634",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":416,
                      "y":20},
                    "size":{
                      "width":82,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/余额_收入详情/u37.png"}},
{
              "id":"7320846bcdcf4400865ca29e8971e7c3",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":416,
                  "y":56},
                "size":{
                  "width":82,
                  "height":37}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"00efb2d173de49f08a11a348f7196bfa",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":416,
                      "y":56},
                    "size":{
                      "width":82,
                      "height":37}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/余额_收入详情/u59.png"}},
{
              "id":"6d78948e792a41b195a206cde9174669",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":540,
                  "y":0},
                "size":{
                  "width":46,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"0af5146770014af8b0b36e9710dd48ed",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":540,
                      "y":0},
                    "size":{
                      "width":46,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/余额_收入详情/u7.png"}},
{
              "id":"e9bf8107046a4a6d8d62b91cf0aa87cf",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":540,
                  "y":20},
                "size":{
                  "width":46,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"fab12cd8618d43d7bc363cc83262ced2",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":540,
                      "y":20},
                    "size":{
                      "width":46,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/余额_收入详情/u29.png"}},
{
              "id":"1a73f376ccce43ad9b91d6e28920c2cc",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":540,
                  "y":56},
                "size":{
                  "width":46,
                  "height":37}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"4a272fbd6dc6469eaf571abe1839544a",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":540,
                      "y":56},
                    "size":{
                      "width":46,
                      "height":37}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/余额_收入详情/u51.png"}},
{
              "id":"177e3315716f4066b0d92560e4701e81",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":586,
                  "y":0},
                "size":{
                  "width":73,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"0813b28ad4754e92aa65e802975660aa",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":586,
                      "y":0},
                    "size":{
                      "width":73,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/余额_收入详情/u21.png"}},
{
              "id":"05435950953a428fb28b2ecd07ce5fbb",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":586,
                  "y":20},
                "size":{
                  "width":73,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"e15fc2d9bdca467da2fa8230ff1aacb1",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":586,
                      "y":20},
                    "size":{
                      "width":73,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/余额_收入详情/u43.png"}},
{
              "id":"c187ed24af7e489ab363da161aaf8e11",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":586,
                  "y":56},
                "size":{
                  "width":73,
                  "height":37}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"64d26f283d4446bd8ec64d6de0729191",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":586,
                      "y":56},
                    "size":{
                      "width":73,
                      "height":37}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/余额_收入详情/u65.png"}},
{
              "id":"13b647fc5a0c403bbbb2034b46517f8f",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":659,
                  "y":0},
                "size":{
                  "width":76,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"a3516f8be0234c4080679aeeea2298bb",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":659,
                      "y":0},
                    "size":{
                      "width":76,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/余额_收入详情/u23.png"}},
{
              "id":"d507059624514ef7b69a66100fe18b00",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":659,
                  "y":20},
                "size":{
                  "width":76,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"f8627af4dfb54f62b297531879b726c5",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":659,
                      "y":20},
                    "size":{
                      "width":76,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/余额_收入详情/u45.png"}},
{
              "id":"30b20022a4314201a2af68448b15bb2a",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":659,
                  "y":56},
                "size":{
                  "width":76,
                  "height":37}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"81919e5d9ba94c7cb9a7ce5fadcbe45a",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":659,
                      "y":56},
                    "size":{
                      "width":76,
                      "height":37}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/余额_收入详情/u67.png"}},
{
              "id":"f05cccca6b514d4da22e17d31e12bacd",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":498,
                  "y":0},
                "size":{
                  "width":42,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"4e0562977c0042a7ba9adef615002e31",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":498,
                      "y":0},
                    "size":{
                      "width":42,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/余额_收入详情/u17.png"}},
{
              "id":"2473c583b822493693addfef81e1975a",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":498,
                  "y":20},
                "size":{
                  "width":42,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"1e5f4763241a4e018cdb23c15b2f1981",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":498,
                      "y":20},
                    "size":{
                      "width":42,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/余额_收入详情/u39.png"}},
{
              "id":"bdfe2f8500004a979fb44dd8cfd940e6",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":498,
                  "y":56},
                "size":{
                  "width":42,
                  "height":37}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"43a0aa4024714cd2b13a1c7bb91eadcf",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":498,
                      "y":56},
                    "size":{
                      "width":42,
                      "height":37}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/余额_收入详情/u61.png"}}]},
{
          "id":"c236311eea2c45bca407e4ef9899f23f",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":42,
              "y":49},
            "size":{
              "width":202,
              "height":38}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a1cd07f569974644be95c5435b086412",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":42,
                  "y":49},
                "size":{
                  "width":202,
                  "height":38}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fee154ee59c141da8066d94aa76b252f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":774,
              "y":49},
            "size":{
              "width":49,
              "height":38}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"067b0cc956194af7b2e56625fd79a88f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":774,
                  "y":49},
                "size":{
                  "width":49,
                  "height":38}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/余额_收入详情/u71.png"}},
{
          "id":"d06b23db963642899d029d6fa4064e31",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":259,
              "y":213},
            "size":{
              "width":508,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a057a61a117748a99988b8f99c9a8699",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":259,
                  "y":213},
                "size":{
                  "width":508,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/余额_收入详情/u73.png"}},
{
          "id":"cae5e35943cd40478ecfab772b383877",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":807,
              "y":213},
            "size":{
              "width":300,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"76eafe132b344b53b6ab531e40e8291e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":807,
                  "y":213},
                "size":{
                  "width":300,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "2cc223d7df8e48ccb3aa76a4cc9bab3b":{
      "scriptId":"u0"},
    "d94e6a21490f483ebfd19ee7f50cb18d":{
      "scriptId":"u1"},
    "8a43888ae51f41d486797df621f65368":{
      "scriptId":"u2"},
    "b2795915966c455aafa60c0db8f28695":{
      "scriptId":"u3"},
    "eb64184c17ed44b7a07e07ea2fbf99e7":{
      "scriptId":"u4"},
    "c024f04c9adf4d0ca0264dad81fe9d2e":{
      "scriptId":"u5"},
    "1a1d3e0a38da4119a3402ebf58dfd976":{
      "scriptId":"u6"},
    "1c3e479ff0014fa6894c35da398fa806":{
      "scriptId":"u7"},
    "70459848ca6a451aa1f0c5a334e4b528":{
      "scriptId":"u8"},
    "522e2bec4b0f45fca07a48150d56d471":{
      "scriptId":"u9"},
    "aa0aa9f90aba48fc84e2ab98d68216e4":{
      "scriptId":"u10"},
    "83078c12d48d423aa86891c19bd9d56a":{
      "scriptId":"u11"},
    "1445432285dd4a408d3f43732a951655":{
      "scriptId":"u12"},
    "3c04da74d5c540f7af2191cb41256271":{
      "scriptId":"u13"},
    "8a07977a5a7f4e48a6fbf2825d07ec13":{
      "scriptId":"u14"},
    "9e72625b88164812aa4d4d41566e9ff4":{
      "scriptId":"u15"},
    "f5e3c33db3d1446f8274b6046e64d420":{
      "scriptId":"u16"},
    "f05cccca6b514d4da22e17d31e12bacd":{
      "scriptId":"u17"},
    "4e0562977c0042a7ba9adef615002e31":{
      "scriptId":"u18"},
    "6d78948e792a41b195a206cde9174669":{
      "scriptId":"u19"},
    "0af5146770014af8b0b36e9710dd48ed":{
      "scriptId":"u20"},
    "177e3315716f4066b0d92560e4701e81":{
      "scriptId":"u21"},
    "0813b28ad4754e92aa65e802975660aa":{
      "scriptId":"u22"},
    "13b647fc5a0c403bbbb2034b46517f8f":{
      "scriptId":"u23"},
    "a3516f8be0234c4080679aeeea2298bb":{
      "scriptId":"u24"},
    "4997e7e250d3479c808f3187c9a1a732":{
      "scriptId":"u25"},
    "dbdb55e7abbe48d0a12ac22fa2ca3498":{
      "scriptId":"u26"},
    "0e1f6511068548baabb534b90287ec59":{
      "scriptId":"u27"},
    "bbb8055f782a4cfabb3dd03b96ffa7ca":{
      "scriptId":"u28"},
    "6c3713641688475fbc573c8fd73b44c3":{
      "scriptId":"u29"},
    "b626df8bcf204ca1aa80d1ea5cd01466":{
      "scriptId":"u30"},
    "bde48feab40840478c13e54f20ec8f2c":{
      "scriptId":"u31"},
    "a8eab607c3964de195221a6bbff1371b":{
      "scriptId":"u32"},
    "be9c2d8927b64927a44b992ee35ecccc":{
      "scriptId":"u33"},
    "4982f6513e744ebf81bffdef53e8faf6":{
      "scriptId":"u34"},
    "f7eedd6769d2473dbd8b0b99780f7706":{
      "scriptId":"u35"},
    "5dc2eb8ef9ba4e4384e95c6add3d0cf8":{
      "scriptId":"u36"},
    "70f1f82007a34abba8c35c0b28eddf49":{
      "scriptId":"u37"},
    "95ebc69eecbc4e6bbc76e455ff17b634":{
      "scriptId":"u38"},
    "2473c583b822493693addfef81e1975a":{
      "scriptId":"u39"},
    "1e5f4763241a4e018cdb23c15b2f1981":{
      "scriptId":"u40"},
    "e9bf8107046a4a6d8d62b91cf0aa87cf":{
      "scriptId":"u41"},
    "fab12cd8618d43d7bc363cc83262ced2":{
      "scriptId":"u42"},
    "05435950953a428fb28b2ecd07ce5fbb":{
      "scriptId":"u43"},
    "e15fc2d9bdca467da2fa8230ff1aacb1":{
      "scriptId":"u44"},
    "d507059624514ef7b69a66100fe18b00":{
      "scriptId":"u45"},
    "f8627af4dfb54f62b297531879b726c5":{
      "scriptId":"u46"},
    "634cd73b950d4bc7bc0bdd9845de1c39":{
      "scriptId":"u47"},
    "9c428be74342428ea1d625a6674be9c5":{
      "scriptId":"u48"},
    "0baaef8fa83642a380bcb070b622d174":{
      "scriptId":"u49"},
    "eb1cc031773f40bfa0827cf5644afd94":{
      "scriptId":"u50"},
    "ed4e6e4a14e847779de41aed5f3e5284":{
      "scriptId":"u51"},
    "8a680abf77024aaa891c6fd73b430c6e":{
      "scriptId":"u52"},
    "fd61660f138840a181e9a6eff7289353":{
      "scriptId":"u53"},
    "a0bc81c7ab0c4b8ab1b89114958410b2":{
      "scriptId":"u54"},
    "52e489dab60f4c09b7b48110c311bd98":{
      "scriptId":"u55"},
    "d9f5bdec7cf64e72a449c685aaf7d83f":{
      "scriptId":"u56"},
    "4206401c890e4386880d8b34924d9a0b":{
      "scriptId":"u57"},
    "00676fbeff824d769164fb55f9880ec9":{
      "scriptId":"u58"},
    "7320846bcdcf4400865ca29e8971e7c3":{
      "scriptId":"u59"},
    "00efb2d173de49f08a11a348f7196bfa":{
      "scriptId":"u60"},
    "bdfe2f8500004a979fb44dd8cfd940e6":{
      "scriptId":"u61"},
    "43a0aa4024714cd2b13a1c7bb91eadcf":{
      "scriptId":"u62"},
    "1a73f376ccce43ad9b91d6e28920c2cc":{
      "scriptId":"u63"},
    "4a272fbd6dc6469eaf571abe1839544a":{
      "scriptId":"u64"},
    "c187ed24af7e489ab363da161aaf8e11":{
      "scriptId":"u65"},
    "64d26f283d4446bd8ec64d6de0729191":{
      "scriptId":"u66"},
    "30b20022a4314201a2af68448b15bb2a":{
      "scriptId":"u67"},
    "81919e5d9ba94c7cb9a7ce5fadcbe45a":{
      "scriptId":"u68"},
    "c236311eea2c45bca407e4ef9899f23f":{
      "scriptId":"u69"},
    "a1cd07f569974644be95c5435b086412":{
      "scriptId":"u70"},
    "fee154ee59c141da8066d94aa76b252f":{
      "scriptId":"u71"},
    "067b0cc956194af7b2e56625fd79a88f":{
      "scriptId":"u72"},
    "d06b23db963642899d029d6fa4064e31":{
      "scriptId":"u73"},
    "a057a61a117748a99988b8f99c9a8699":{
      "scriptId":"u74"},
    "cae5e35943cd40478ecfab772b383877":{
      "scriptId":"u75"},
    "76eafe132b344b53b6ab531e40e8291e":{
      "scriptId":"u76"}}});