$axure.loadCurrentPage({
  "url":"查看风险上报.html",
  "generationDate":new Date(1662608852616.25),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"309a2a0eb70f4fc7b961f5fb2297605d",
    "type":"Axure:Page",
    "name":"查看风险上报",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"dfb34ec7f1d949feba5b8d37e38f946b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":40},
            "size":{
              "width":980,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a8b8e806692942eeb9af952b8f1aafbd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":40,
                  "y":40},
                "size":{
                  "width":980,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/查看风险上报/u0.png"}},
{
          "id":"69c19783f60d464fb69b33cf1ab9fc8f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":436.999969482422,
              "y":202},
            "size":{
              "width":353,
              "height":48}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7d42eed60ee444bcaf961491a1e11d6d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":436.999969482422,
                  "y":202},
                "size":{
                  "width":353,
                  "height":48}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5a52adbe70e64f9895a4c45019b5cf53",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":392,
              "y":147},
            "size":{
              "width":508,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"12b22435052249699664e1207daa8de0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":392,
                  "y":147},
                "size":{
                  "width":508,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/客户管理-业务数据展示/u559.png"}},
{
          "id":"69629e3599054cbcb30918a431c03592",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":204,
              "y":18},
            "size":{
              "width":33,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"05840b53b9944c8b8bc5f8bf038dfb78",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":204,
                  "y":18},
                "size":{
                  "width":33,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"756799abd4494b47840cffe2f041bf26",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "disabled":true,
          "visible":true,
          "style":{
            "location":{
              "x":268,
              "y":15},
            "size":{
              "width":222,
              "height":25}},
          "adaptiveStyles":{
}}]}},
  "masters":{
},
  "objectPaths":{
    "dfb34ec7f1d949feba5b8d37e38f946b":{
      "scriptId":"u0"},
    "a8b8e806692942eeb9af952b8f1aafbd":{
      "scriptId":"u1"},
    "69c19783f60d464fb69b33cf1ab9fc8f":{
      "scriptId":"u2"},
    "7d42eed60ee444bcaf961491a1e11d6d":{
      "scriptId":"u3"},
    "5a52adbe70e64f9895a4c45019b5cf53":{
      "scriptId":"u4"},
    "12b22435052249699664e1207daa8de0":{
      "scriptId":"u5"},
    "69629e3599054cbcb30918a431c03592":{
      "scriptId":"u6"},
    "05840b53b9944c8b8bc5f8bf038dfb78":{
      "scriptId":"u7"},
    "756799abd4494b47840cffe2f041bf26":{
      "scriptId":"u8"}}});