$axure.loadCurrentPage({
  "url":"积分统计.html",
  "generationDate":new Date(1661416136578.64),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"96375c01e2c249aa8d644e15ee5a0389",
    "type":"Axure:Page",
    "name":"积分统计",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"0651bd8a300042d38aac429308eb0813",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":51,
              "y":32},
            "size":{
              "width":249,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4bb9f8bf396146b7b66fb14802e4c4c7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":51,
                  "y":32},
                "size":{
                  "width":249,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7bb5514923734bf7ac3fad9921ef5542",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":48,
              "y":70},
            "size":{
              "width":852,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/金融产品管理/u5_line.png"}},
{
          "id":"1c6c986da48a4abab79039b45f08ef7e",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":730,
              "y":90},
            "size":{
              "width":60,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"2d1d1b0ba7384e61b4d59bb564aa4cef",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":800,
              "y":90},
            "size":{
              "width":60,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"764ee102b4104c10b85745d10d312937",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":48,
              "y":150},
            "size":{
              "width":604,
              "height":96}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b5135ccf027a47c089827d6f3a1a0015",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "size":{
                  "width":82,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"1fbbd90cc5a54088b215f6979400cbd4",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":82,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/余额_收入详情/u37.png"}},
{
              "id":"a4024332b9bd47248c4f9e38de61f73c",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":36},
                "size":{
                  "width":82,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"7f7b4df9522547f991b0eaf398c207d1",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":36},
                    "size":{
                      "width":82,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/余额_收入详情/u15.png"}},
{
              "id":"6eeac3850be74af5bd42ace98709d32b",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":56},
                "size":{
                  "width":82,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"0e923acf6e4e49458211ce4054782cc3",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":56},
                    "size":{
                      "width":82,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/余额_收入详情/u15.png"}},
{
              "id":"978c3a8a54d44fbdbcca480cefb4c4e2",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":76},
                "size":{
                  "width":82,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"7ddbf61c9e2b44ccbfc92cc48cfefc9b",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":76},
                    "size":{
                      "width":82,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/金融产品管理/u51.png"}},
{
              "id":"58bae2b351264fbe80b960f2f5d3a5d9",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":82,
                  "y":0},
                "size":{
                  "width":78,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"ae43f79d5186477abb085a92b49d5225",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":82,
                      "y":0},
                    "size":{
                      "width":78,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/客户管理-业务数据展示/u97.png"}},
{
              "id":"96e890df29df4c84b62c15ce260153f7",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":82,
                  "y":36},
                "size":{
                  "width":78,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"dde045c7f1c94b46aa947797204eb7dc",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":82,
                      "y":36},
                    "size":{
                      "width":78,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/客户管理-业务数据展示/u71.png"}},
{
              "id":"48fd2b48789943afb36e186954c7910b",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":82,
                  "y":56},
                "size":{
                  "width":78,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"d8210f5f179b48729ca57dd7a4d53ca1",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":82,
                      "y":56},
                    "size":{
                      "width":78,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/客户管理-业务数据展示/u71.png"}},
{
              "id":"e628bf22227645c1b91c7486e976761b",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":82,
                  "y":76},
                "size":{
                  "width":78,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"abf5eef607d146409b4a608460109fcb",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":82,
                      "y":76},
                    "size":{
                      "width":78,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/客户管理-业务数据展示/u501.png"}},
{
              "id":"260ee175c7c841fd9e5185542ecf7a05",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":160,
                  "y":0},
                "size":{
                  "width":71,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"086731303cb94d2ea98b24d6f6f44697",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":160,
                      "y":0},
                    "size":{
                      "width":71,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/金融产品管理/u13.png"}},
{
              "id":"8ebc026f6e694973984885c03b94a02c",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":160,
                  "y":36},
                "size":{
                  "width":71,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"df3110b4e10e4536b02ec2e35a562b33",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":160,
                      "y":36},
                    "size":{
                      "width":71,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/金融产品管理/u27.png"}},
{
              "id":"3c771e181a79454594c501454b8f49bc",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":160,
                  "y":56},
                "size":{
                  "width":71,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"98fedfaf152f438ea2f41b98a7aa8486",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":160,
                      "y":56},
                    "size":{
                      "width":71,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/金融产品管理/u27.png"}},
{
              "id":"ccc9af254f834e7bb366fb6a1587ca6b",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":160,
                  "y":76},
                "size":{
                  "width":71,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"ea8f0b9ab215410db5bb4b94b548a81e",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":160,
                      "y":76},
                    "size":{
                      "width":71,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/金融产品管理/u55.png"}},
{
              "id":"e18420e37f5b4ad9b3885a0151e03238",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":231,
                  "y":0},
                "size":{
                  "width":113,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"ed405d9696be43c9b023ec2043b95e0d",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":231,
                      "y":0},
                    "size":{
                      "width":113,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/金融产品管理/u15.png"}},
{
              "id":"4ea1f27299c6474ebe5a2af11023ec7b",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":231,
                  "y":36},
                "size":{
                  "width":113,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"6b855497f9634c2f95896c89be17792d",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":231,
                      "y":36},
                    "size":{
                      "width":113,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/金融产品管理/u29.png"}},
{
              "id":"c09a6f6ea8c745c4bb67d389bd5d3274",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":231,
                  "y":56},
                "size":{
                  "width":113,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"7949fb66e5cd4a7eb73a9dd825d668cb",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":231,
                      "y":56},
                    "size":{
                      "width":113,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/金融产品管理/u29.png"}},
{
              "id":"115983d77a42465484cb47975b60765b",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":231,
                  "y":76},
                "size":{
                  "width":113,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"4c4b9bc35bd747fb9e8fcdcc6d6051e2",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":231,
                      "y":76},
                    "size":{
                      "width":113,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/金融产品管理/u57.png"}},
{
              "id":"7e839768e5d041709889ed5c2577cc59",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":426,
                  "y":0},
                "size":{
                  "width":46,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"12e434d394ae4828b1f5cc7988481026",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":426,
                      "y":0},
                    "size":{
                      "width":46,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/余额_收入详情/u29.png"}},
{
              "id":"37614c2fcc704ec48634351ab3db5729",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":426,
                  "y":36},
                "size":{
                  "width":46,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"2e65be4cc39e4964adbc94ec8bd747fd",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":426,
                      "y":36},
                    "size":{
                      "width":46,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/余额_收入详情/u7.png"}},
{
              "id":"099effa2cc5348ce85d5f465608f9d11",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":426,
                  "y":56},
                "size":{
                  "width":46,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"b204b31bd4ec40909d3da5e6358b2ade",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":426,
                      "y":56},
                    "size":{
                      "width":46,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/余额_收入详情/u7.png"}},
{
              "id":"35ed3da7ca7e43cd8bd741909cca9616",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":426,
                  "y":76},
                "size":{
                  "width":46,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"6f4748cfd23c4a8d87f15d4db59cf86c",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":426,
                      "y":76},
                    "size":{
                      "width":46,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/金融产品管理/u61.png"}},
{
              "id":"eaf62c42c8c041509fb01c649232aaf2",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":472,
                  "y":0},
                "size":{
                  "width":132,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"50bf6e3f9f904f33b705b9d37062b018",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":472,
                      "y":0},
                    "size":{
                      "width":132,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/金融产品管理/u21.png"}},
{
              "id":"20773267381140e68b30679349bb2090",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000099,
                  "opacity":1},
                "location":{
                  "x":472,
                  "y":36},
                "size":{
                  "width":132,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"0de98a55a97f4ac9bf22f89c1c5b7dbd",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF000099,
                      "opacity":1},
                    "location":{
                      "x":472,
                      "y":36},
                    "size":{
                      "width":132,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/金融产品管理/u35.png"}},
{
              "id":"81cf65cb04954b638a6bcb88724204e1",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":472,
                  "y":56},
                "size":{
                  "width":132,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"5a62f36419414cbe8e6b3c817d3cb74b",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":472,
                      "y":56},
                    "size":{
                      "width":132,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/金融产品管理/u35.png"}},
{
              "id":"f7df7ee4553a4526a70ea01bc7407799",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":472,
                  "y":76},
                "size":{
                  "width":132,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"77a149ee63fd492b85000a8d152a7df3",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":472,
                      "y":76},
                    "size":{
                      "width":132,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/金融产品管理/u63.png"}},
{
              "id":"9a90a6cfd2874eb8bd86860813818634",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":344,
                  "y":0},
                "size":{
                  "width":82,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"e5eea0adadb34452af1d32b463d55f38",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":344,
                      "y":0},
                    "size":{
                      "width":82,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/余额_收入详情/u37.png"}},
{
              "id":"48a5842d4ebb4a1cb243ae1d67323580",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":344,
                  "y":36},
                "size":{
                  "width":82,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"2554188d207247099a02ba659dde6c2d",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":344,
                      "y":36},
                    "size":{
                      "width":82,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/余额_收入详情/u15.png"}},
{
              "id":"abb02af9d67e43e4a629110342d6ae7c",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":344,
                  "y":56},
                "size":{
                  "width":82,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"791211784efc40fe86bee75d0272db8e",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":344,
                      "y":56},
                    "size":{
                      "width":82,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/余额_收入详情/u15.png"}},
{
              "id":"8dd1d5b653a54315bd0592e8fe6cb63d",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":344,
                  "y":76},
                "size":{
                  "width":82,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"5dee25050fd94643987acca17e5ebcdf",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":344,
                      "y":76},
                    "size":{
                      "width":82,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/金融产品管理/u51.png"}}]},
{
          "id":"a8aa1723f3b242158d0f748101787a78",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":186,
              "y":290},
            "size":{
              "width":508,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8df78616ff844d6e919846ef20ea4fed",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":186,
                  "y":290},
                "size":{
                  "width":508,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/余额_收入详情/u73.png"}},
{
          "id":"7e78be9c1530448c9abb3a3520b97b7b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":717,
              "y":394},
            "size":{
              "width":429,
              "height":144}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"69147be70ae548eb8a436d7fa08903cc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":717,
                  "y":394},
                "size":{
                  "width":429,
                  "height":144}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6211a7f56c4d4ad78390a178c435a9b0",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":339,
              "y":93},
            "size":{
              "width":120,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"aaa6652102bb4a808462100f73e283da",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":186,
              "y":92},
            "size":{
              "width":120,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"5d39747913cc43f899369f8ff97859a7",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":48,
              "y":92},
            "size":{
              "width":132,
              "height":25}},
          "adaptiveStyles":{
},
          "placeholderText":"请输入客户经理姓名"}]}},
  "masters":{
},
  "objectPaths":{
    "0651bd8a300042d38aac429308eb0813":{
      "scriptId":"u0"},
    "4bb9f8bf396146b7b66fb14802e4c4c7":{
      "scriptId":"u1"},
    "7bb5514923734bf7ac3fad9921ef5542":{
      "scriptId":"u2"},
    "1c6c986da48a4abab79039b45f08ef7e":{
      "scriptId":"u3"},
    "2d1d1b0ba7384e61b4d59bb564aa4cef":{
      "scriptId":"u4"},
    "764ee102b4104c10b85745d10d312937":{
      "scriptId":"u5"},
    "b5135ccf027a47c089827d6f3a1a0015":{
      "scriptId":"u6"},
    "1fbbd90cc5a54088b215f6979400cbd4":{
      "scriptId":"u7"},
    "58bae2b351264fbe80b960f2f5d3a5d9":{
      "scriptId":"u8"},
    "ae43f79d5186477abb085a92b49d5225":{
      "scriptId":"u9"},
    "260ee175c7c841fd9e5185542ecf7a05":{
      "scriptId":"u10"},
    "086731303cb94d2ea98b24d6f6f44697":{
      "scriptId":"u11"},
    "e18420e37f5b4ad9b3885a0151e03238":{
      "scriptId":"u12"},
    "ed405d9696be43c9b023ec2043b95e0d":{
      "scriptId":"u13"},
    "9a90a6cfd2874eb8bd86860813818634":{
      "scriptId":"u14"},
    "e5eea0adadb34452af1d32b463d55f38":{
      "scriptId":"u15"},
    "7e839768e5d041709889ed5c2577cc59":{
      "scriptId":"u16"},
    "12e434d394ae4828b1f5cc7988481026":{
      "scriptId":"u17"},
    "eaf62c42c8c041509fb01c649232aaf2":{
      "scriptId":"u18"},
    "50bf6e3f9f904f33b705b9d37062b018":{
      "scriptId":"u19"},
    "a4024332b9bd47248c4f9e38de61f73c":{
      "scriptId":"u20"},
    "7f7b4df9522547f991b0eaf398c207d1":{
      "scriptId":"u21"},
    "96e890df29df4c84b62c15ce260153f7":{
      "scriptId":"u22"},
    "dde045c7f1c94b46aa947797204eb7dc":{
      "scriptId":"u23"},
    "8ebc026f6e694973984885c03b94a02c":{
      "scriptId":"u24"},
    "df3110b4e10e4536b02ec2e35a562b33":{
      "scriptId":"u25"},
    "4ea1f27299c6474ebe5a2af11023ec7b":{
      "scriptId":"u26"},
    "6b855497f9634c2f95896c89be17792d":{
      "scriptId":"u27"},
    "48a5842d4ebb4a1cb243ae1d67323580":{
      "scriptId":"u28"},
    "2554188d207247099a02ba659dde6c2d":{
      "scriptId":"u29"},
    "37614c2fcc704ec48634351ab3db5729":{
      "scriptId":"u30"},
    "2e65be4cc39e4964adbc94ec8bd747fd":{
      "scriptId":"u31"},
    "20773267381140e68b30679349bb2090":{
      "scriptId":"u32"},
    "0de98a55a97f4ac9bf22f89c1c5b7dbd":{
      "scriptId":"u33"},
    "6eeac3850be74af5bd42ace98709d32b":{
      "scriptId":"u34"},
    "0e923acf6e4e49458211ce4054782cc3":{
      "scriptId":"u35"},
    "48fd2b48789943afb36e186954c7910b":{
      "scriptId":"u36"},
    "d8210f5f179b48729ca57dd7a4d53ca1":{
      "scriptId":"u37"},
    "3c771e181a79454594c501454b8f49bc":{
      "scriptId":"u38"},
    "98fedfaf152f438ea2f41b98a7aa8486":{
      "scriptId":"u39"},
    "c09a6f6ea8c745c4bb67d389bd5d3274":{
      "scriptId":"u40"},
    "7949fb66e5cd4a7eb73a9dd825d668cb":{
      "scriptId":"u41"},
    "abb02af9d67e43e4a629110342d6ae7c":{
      "scriptId":"u42"},
    "791211784efc40fe86bee75d0272db8e":{
      "scriptId":"u43"},
    "099effa2cc5348ce85d5f465608f9d11":{
      "scriptId":"u44"},
    "b204b31bd4ec40909d3da5e6358b2ade":{
      "scriptId":"u45"},
    "81cf65cb04954b638a6bcb88724204e1":{
      "scriptId":"u46"},
    "5a62f36419414cbe8e6b3c817d3cb74b":{
      "scriptId":"u47"},
    "978c3a8a54d44fbdbcca480cefb4c4e2":{
      "scriptId":"u48"},
    "7ddbf61c9e2b44ccbfc92cc48cfefc9b":{
      "scriptId":"u49"},
    "e628bf22227645c1b91c7486e976761b":{
      "scriptId":"u50"},
    "abf5eef607d146409b4a608460109fcb":{
      "scriptId":"u51"},
    "ccc9af254f834e7bb366fb6a1587ca6b":{
      "scriptId":"u52"},
    "ea8f0b9ab215410db5bb4b94b548a81e":{
      "scriptId":"u53"},
    "115983d77a42465484cb47975b60765b":{
      "scriptId":"u54"},
    "4c4b9bc35bd747fb9e8fcdcc6d6051e2":{
      "scriptId":"u55"},
    "8dd1d5b653a54315bd0592e8fe6cb63d":{
      "scriptId":"u56"},
    "5dee25050fd94643987acca17e5ebcdf":{
      "scriptId":"u57"},
    "35ed3da7ca7e43cd8bd741909cca9616":{
      "scriptId":"u58"},
    "6f4748cfd23c4a8d87f15d4db59cf86c":{
      "scriptId":"u59"},
    "f7df7ee4553a4526a70ea01bc7407799":{
      "scriptId":"u60"},
    "77a149ee63fd492b85000a8d152a7df3":{
      "scriptId":"u61"},
    "a8aa1723f3b242158d0f748101787a78":{
      "scriptId":"u62"},
    "8df78616ff844d6e919846ef20ea4fed":{
      "scriptId":"u63"},
    "7e78be9c1530448c9abb3a3520b97b7b":{
      "scriptId":"u64"},
    "69147be70ae548eb8a436d7fa08903cc":{
      "scriptId":"u65"},
    "6211a7f56c4d4ad78390a178c435a9b0":{
      "scriptId":"u66"},
    "aaa6652102bb4a808462100f73e283da":{
      "scriptId":"u67"},
    "5d39747913cc43f899369f8ff97859a7":{
      "scriptId":"u68"}}});