$axure.loadCurrentPage({
  "url":"市场服务部人员.html",
  "generationDate":new Date(1662526079357.12),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"0e305521f67047748a8425c38a851e9f",
    "type":"Axure:Page",
    "name":"市场服务部人员",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"40f9d4049da0475993a0c8f188f3210b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":70,
              "y":40},
            "size":{
              "width":970,
              "height":500}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8a12af593dbe4b2182a3a21ca30e1d36",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":70,
                  "y":40},
                "size":{
                  "width":970,
                  "height":500}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/专业公司部门经理/u0.png"}},
{
          "id":"69e583f1f1754c23a08b186e2d6f8de0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":90,
              "y":60},
            "size":{
              "width":230,
              "height":230}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2e64b97087334ef5abb79859b89a8738",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":90,
                  "y":60},
                "size":{
                  "width":230,
                  "height":230}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/客户经理/u2.png"}},
{
          "id":"8b7dc94ec27942d1b8177308545f8432",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":330,
              "y":60},
            "size":{
              "width":240,
              "height":230}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f750d22938254b9eafd56a207eb0d32e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":330,
                  "y":60},
                "size":{
                  "width":240,
                  "height":230}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/市场服务部人员/u4.png"}},
{
          "id":"c1cc4dad0539487cb9ddd9b153884c74",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":580,
              "y":60},
            "size":{
              "width":260,
              "height":230},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"368392d5dc7a40f39b8092fb08c0bb2f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":580,
                  "y":60},
                "size":{
                  "width":260,
                  "height":230},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/市场服务部人员/u6.png"}},
{
          "id":"110ba469e88f447a8cff7d869eddb95b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "underline":true,
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":780,
              "y":270},
            "size":{
              "width":54,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"792dcf01a9f544008576cc1b0ae0d563",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "underline":true,
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":780,
                  "y":270},
                "size":{
                  "width":54,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9c78475ed39746779e5209ecde457aff",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":90,
              "y":300},
            "size":{
              "width":750,
              "height":240}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d953a52dc1d848309b6afaed456ff5a4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":90,
                  "y":300},
                "size":{
                  "width":750,
                  "height":240}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/客户经理/u10.png"}},
{
          "id":"4ace4f24405141d882dada2b471415ab",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":110,
              "y":340},
            "size":{
              "width":710,
              "height":178}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d883fa98b2ad4fee9f7cae451a07cb01",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "size":{
                  "width":202,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"bb5f669be18f4f7e8b55cd4a8774759b",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "size":{
                      "width":202,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/客户经理/u13.png"}},
{
              "id":"000e5f12b1cb4dca8df4b6c270a65978",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":30},
                "size":{
                  "width":202,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"e2a29d7e78ea4910affab78fca345957",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":30},
                    "size":{
                      "width":202,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/客户经理/u21.png"}},
{
              "id":"58fb21ec3e1b4aa7b386f1092c67fa59",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":66},
                "size":{
                  "width":202,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"e9354f78195c452d909f6a0c581ec36c",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":66},
                    "size":{
                      "width":202,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/客户经理/u21.png"}},
{
              "id":"3f9bd42e33504fd0a6551a9e448abddb",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":281,
                  "y":0},
                "size":{
                  "width":313,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"1ad9be6024bb45d384a0f06a0b9773e4",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":281,
                      "y":0},
                    "size":{
                      "width":313,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/客户经理/u17.png"}},
{
              "id":"2066ea2e6b064cca9bedf48871c129cc",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":281,
                  "y":30},
                "size":{
                  "width":313,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"4c88bc47309c4e878f1746aa14c064b5",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":281,
                      "y":30},
                    "size":{
                      "width":313,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/客户经理/u25.png"}},
{
              "id":"a5e000524c4d4ff9894eb1f12e9eb510",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":281,
                  "y":66},
                "size":{
                  "width":313,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"39f241eb4e2c49818a242f90ba280905",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":281,
                      "y":66},
                    "size":{
                      "width":313,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/客户经理/u25.png"}},
{
              "id":"e3687f229767446291dae8271dae7cd2",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":594,
                  "y":0},
                "size":{
                  "width":116,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"aeb365a0df3f4199a0b345afd5d72c91",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":594,
                      "y":0},
                    "size":{
                      "width":116,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/客户经理/u19.png"}},
{
              "id":"4539c68d2002451da3b509ade1a92377",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":594,
                  "y":30},
                "size":{
                  "width":116,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"3e394d6b534c46dbb3c0d92a6527b672",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":594,
                      "y":30},
                    "size":{
                      "width":116,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/客户经理/u27.png"}},
{
              "id":"d847b196a8e64ee28cd54649f8a30739",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":594,
                  "y":66},
                "size":{
                  "width":116,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"188c3dc5f8594c7598c145f2a3da8e98",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":594,
                      "y":66},
                    "size":{
                      "width":116,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/客户经理/u27.png"}},
{
              "id":"72dcbddda22d4661a066d3e291eb1324",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":202,
                  "y":0},
                "size":{
                  "width":79,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"bd8c624e08f3425e913c871cfcb77112",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":202,
                      "y":0},
                    "size":{
                      "width":79,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/客户经理/u15.png"}},
{
              "id":"720b0bf521924288acd21a500a400c60",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":202,
                  "y":30},
                "size":{
                  "width":79,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"dcf95615296843248f650110d2f6944b",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":202,
                      "y":30},
                    "size":{
                      "width":79,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/客户经理/u23.png"}},
{
              "id":"978ded84e01f46f091249e9a1d2cc1a5",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":202,
                  "y":66},
                "size":{
                  "width":79,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"4f80ad035f0a4fb8ac8dbcfde0beb32b",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":202,
                      "y":66},
                    "size":{
                      "width":79,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/客户经理/u23.png"}},
{
              "id":"ea588e80081e4e19a58041abf84f7c4a",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":102},
                "size":{
                  "width":202,
                  "height":38}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"a0b80fce603b4c60b92471878738067b",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":102},
                    "size":{
                      "width":202,
                      "height":38}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/客户经理/u37.png"}},
{
              "id":"a209ed76f9b54b2eb33935a66bc4503f",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":202,
                  "y":102},
                "size":{
                  "width":79,
                  "height":38}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"17b106d696634194947f683e1e72a0b7",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":202,
                      "y":102},
                    "size":{
                      "width":79,
                      "height":38}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/客户经理/u39.png"}},
{
              "id":"03f02fe0d16b4afbb421b653a4bb27be",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":281,
                  "y":102},
                "size":{
                  "width":313,
                  "height":38}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"99ba0626b5f440eb9d46d25c33884d3a",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":281,
                      "y":102},
                    "size":{
                      "width":313,
                      "height":38}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/客户经理/u41.png"}},
{
              "id":"ec9b1545790b4e628178231e39e4198a",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":594,
                  "y":102},
                "size":{
                  "width":116,
                  "height":38}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"6e09ad234a4b4ee1bad8161a39b3bfd3",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":594,
                      "y":102},
                    "size":{
                      "width":116,
                      "height":38}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/客户经理/u43.png"}},
{
              "id":"9bffe1ee89324d0bb6732c5039a5ad9d",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":140},
                "size":{
                  "width":202,
                  "height":38}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"dc5a2546a2b34346adede52f1a54ca27",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":140},
                    "size":{
                      "width":202,
                      "height":38}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/客户经理/u45.png"}},
{
              "id":"81c39b212eb1485e9f05714a3cf9e54d",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":202,
                  "y":140},
                "size":{
                  "width":79,
                  "height":38}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"635fffa87b7a447395c2af1d5f738aff",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":202,
                      "y":140},
                    "size":{
                      "width":79,
                      "height":38}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/客户经理/u47.png"}},
{
              "id":"e05f7596622243ac92233f9db26f4e28",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":281,
                  "y":140},
                "size":{
                  "width":313,
                  "height":38}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"e23c744750a54b1687adb3ce3559ac9a",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":281,
                      "y":140},
                    "size":{
                      "width":313,
                      "height":38}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/客户经理/u49.png"}},
{
              "id":"a2514da05b6847c6a7a094cd0f519464",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":594,
                  "y":140},
                "size":{
                  "width":116,
                  "height":38}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"b4803a1263ac47ca8abf947f631f2b2c",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":594,
                      "y":140},
                    "size":{
                      "width":116,
                      "height":38}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/客户经理/u51.png"}}]},
{
          "id":"205208a8dd25436cb2f04df21fa4c4d6",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":206,
              "y":302},
            "size":{
              "width":129,
              "height":38}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d2160fe71be54b819c3d8db16c0a30ae",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":206,
                  "y":302},
                "size":{
                  "width":129,
                  "height":38}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9d49f852fe4f4802b729af46a57a4d24",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "underline":true,
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":96,
              "y":518},
            "size":{
              "width":54,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d2473dd9edcd4140b2d20f52cec015ec",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "underline":true,
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":96,
                  "y":518},
                "size":{
                  "width":54,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"95ae035bd5a64674bcfc89ffbdb59245",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":620,
              "y":513},
            "size":{
              "width":218,
              "height":27},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"530247d887604e8f85d08c62a84b2132",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":620,
                  "y":513},
                "size":{
                  "width":218,
                  "height":27},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/客户经理/u57.png"}},
{
          "id":"521b9b6cda124f40b604266ace6a2a84",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":90,
              "y":60},
            "size":{
              "width":230,
              "height":230}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8d507f4894744315887d7e73f3eee4ef",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":90,
                  "y":60},
                "size":{
                  "width":230,
                  "height":230}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/客户经理/u4.png"}},
{
          "id":"b08c8a021fa5459f8848294fd84e0abc",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":90,
              "y":90},
            "size":{
              "width":230,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d1db4a41976b45a3a046ec63ddf09c7e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":90,
                  "y":90},
                "size":{
                  "width":230,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/市场服务部人员/u61.png"}},
{
          "id":"6f8a6ca312c84c51a192197c7a19baf6",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":330.000030517578,
              "y":90},
            "size":{
              "width":230,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e673928c5db740408e4cb55114e3f021",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":330.000030517578,
                  "y":90},
                "size":{
                  "width":230,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/市场服务部人员/u61.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "40f9d4049da0475993a0c8f188f3210b":{
      "scriptId":"u0"},
    "8a12af593dbe4b2182a3a21ca30e1d36":{
      "scriptId":"u1"},
    "69e583f1f1754c23a08b186e2d6f8de0":{
      "scriptId":"u2"},
    "2e64b97087334ef5abb79859b89a8738":{
      "scriptId":"u3"},
    "8b7dc94ec27942d1b8177308545f8432":{
      "scriptId":"u4"},
    "f750d22938254b9eafd56a207eb0d32e":{
      "scriptId":"u5"},
    "c1cc4dad0539487cb9ddd9b153884c74":{
      "scriptId":"u6"},
    "368392d5dc7a40f39b8092fb08c0bb2f":{
      "scriptId":"u7"},
    "110ba469e88f447a8cff7d869eddb95b":{
      "scriptId":"u8"},
    "792dcf01a9f544008576cc1b0ae0d563":{
      "scriptId":"u9"},
    "9c78475ed39746779e5209ecde457aff":{
      "scriptId":"u10"},
    "d953a52dc1d848309b6afaed456ff5a4":{
      "scriptId":"u11"},
    "4ace4f24405141d882dada2b471415ab":{
      "scriptId":"u12"},
    "d883fa98b2ad4fee9f7cae451a07cb01":{
      "scriptId":"u13"},
    "bb5f669be18f4f7e8b55cd4a8774759b":{
      "scriptId":"u14"},
    "72dcbddda22d4661a066d3e291eb1324":{
      "scriptId":"u15"},
    "bd8c624e08f3425e913c871cfcb77112":{
      "scriptId":"u16"},
    "3f9bd42e33504fd0a6551a9e448abddb":{
      "scriptId":"u17"},
    "1ad9be6024bb45d384a0f06a0b9773e4":{
      "scriptId":"u18"},
    "e3687f229767446291dae8271dae7cd2":{
      "scriptId":"u19"},
    "aeb365a0df3f4199a0b345afd5d72c91":{
      "scriptId":"u20"},
    "000e5f12b1cb4dca8df4b6c270a65978":{
      "scriptId":"u21"},
    "e2a29d7e78ea4910affab78fca345957":{
      "scriptId":"u22"},
    "720b0bf521924288acd21a500a400c60":{
      "scriptId":"u23"},
    "dcf95615296843248f650110d2f6944b":{
      "scriptId":"u24"},
    "2066ea2e6b064cca9bedf48871c129cc":{
      "scriptId":"u25"},
    "4c88bc47309c4e878f1746aa14c064b5":{
      "scriptId":"u26"},
    "4539c68d2002451da3b509ade1a92377":{
      "scriptId":"u27"},
    "3e394d6b534c46dbb3c0d92a6527b672":{
      "scriptId":"u28"},
    "58fb21ec3e1b4aa7b386f1092c67fa59":{
      "scriptId":"u29"},
    "e9354f78195c452d909f6a0c581ec36c":{
      "scriptId":"u30"},
    "978ded84e01f46f091249e9a1d2cc1a5":{
      "scriptId":"u31"},
    "4f80ad035f0a4fb8ac8dbcfde0beb32b":{
      "scriptId":"u32"},
    "a5e000524c4d4ff9894eb1f12e9eb510":{
      "scriptId":"u33"},
    "39f241eb4e2c49818a242f90ba280905":{
      "scriptId":"u34"},
    "d847b196a8e64ee28cd54649f8a30739":{
      "scriptId":"u35"},
    "188c3dc5f8594c7598c145f2a3da8e98":{
      "scriptId":"u36"},
    "ea588e80081e4e19a58041abf84f7c4a":{
      "scriptId":"u37"},
    "a0b80fce603b4c60b92471878738067b":{
      "scriptId":"u38"},
    "a209ed76f9b54b2eb33935a66bc4503f":{
      "scriptId":"u39"},
    "17b106d696634194947f683e1e72a0b7":{
      "scriptId":"u40"},
    "03f02fe0d16b4afbb421b653a4bb27be":{
      "scriptId":"u41"},
    "99ba0626b5f440eb9d46d25c33884d3a":{
      "scriptId":"u42"},
    "ec9b1545790b4e628178231e39e4198a":{
      "scriptId":"u43"},
    "6e09ad234a4b4ee1bad8161a39b3bfd3":{
      "scriptId":"u44"},
    "9bffe1ee89324d0bb6732c5039a5ad9d":{
      "scriptId":"u45"},
    "dc5a2546a2b34346adede52f1a54ca27":{
      "scriptId":"u46"},
    "81c39b212eb1485e9f05714a3cf9e54d":{
      "scriptId":"u47"},
    "635fffa87b7a447395c2af1d5f738aff":{
      "scriptId":"u48"},
    "e05f7596622243ac92233f9db26f4e28":{
      "scriptId":"u49"},
    "e23c744750a54b1687adb3ce3559ac9a":{
      "scriptId":"u50"},
    "a2514da05b6847c6a7a094cd0f519464":{
      "scriptId":"u51"},
    "b4803a1263ac47ca8abf947f631f2b2c":{
      "scriptId":"u52"},
    "205208a8dd25436cb2f04df21fa4c4d6":{
      "scriptId":"u53"},
    "d2160fe71be54b819c3d8db16c0a30ae":{
      "scriptId":"u54"},
    "9d49f852fe4f4802b729af46a57a4d24":{
      "scriptId":"u55"},
    "d2473dd9edcd4140b2d20f52cec015ec":{
      "scriptId":"u56"},
    "95ae035bd5a64674bcfc89ffbdb59245":{
      "scriptId":"u57"},
    "530247d887604e8f85d08c62a84b2132":{
      "scriptId":"u58"},
    "521b9b6cda124f40b604266ace6a2a84":{
      "scriptId":"u59"},
    "8d507f4894744315887d7e73f3eee4ef":{
      "scriptId":"u60"},
    "b08c8a021fa5459f8848294fd84e0abc":{
      "scriptId":"u61"},
    "d1db4a41976b45a3a046ec63ddf09c7e":{
      "scriptId":"u62"},
    "6f8a6ca312c84c51a192197c7a19baf6":{
      "scriptId":"u63"},
    "e673928c5db740408e4cb55114e3f021":{
      "scriptId":"u64"}}});