$axure.loadCurrentPage({
  "url":"功能风格.html",
  "generationDate":new Date(1659405086108.86),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"e2cb010fa4df4681abd0972184d6197e",
    "type":"Axure:Page",
    "name":"功能风格",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"d4c0865cd3124f6a8de193b115466fad",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":100},
            "size":{
              "width":228,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"10059af54f8c4c739871867f4770ddfd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":60,
                  "y":100},
                "size":{
                  "width":228,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "d4c0865cd3124f6a8de193b115466fad":{
      "scriptId":"u0"},
    "10059af54f8c4c739871867f4770ddfd":{
      "scriptId":"u1"}}});