$axure.loadCurrentPage({
  "url":"功能风格.html",
  "generationDate":new Date(1662609051959.31),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"e2cb010fa4df4681abd0972184d6197e",
    "type":"Axure:Page",
    "name":"功能风格",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"d4c0865cd3124f6a8de193b115466fad",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":100},
            "size":{
              "width":555,
              "height":528}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"10059af54f8c4c739871867f4770ddfd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":60,
                  "y":100},
                "size":{
                  "width":555,
                  "height":528}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7d5d03914b4442a3bc98f8d5bf030794",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":40},
            "size":{
              "width":289,
              "height":38}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4182c4eeb0184eccb74537cddf168486",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":60,
                  "y":40},
                "size":{
                  "width":289,
                  "height":38}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"521707aa6481498690d7c166c8afbb73",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":50,
              "y":567},
            "size":{
              "width":530,
              "height":133}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4532c1d69932453890c079347d68bd49",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":50,
                  "y":567},
                "size":{
                  "width":530,
                  "height":133}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/功能风格/u4.jpg"}},
{
          "id":"f529db701af448c68fced213ec4edb94",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":714},
            "size":{
              "width":290,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0b9239278b1c44fe83f51b9db596583c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":60,
                  "y":714},
                "size":{
                  "width":290,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "d4c0865cd3124f6a8de193b115466fad":{
      "scriptId":"u0"},
    "10059af54f8c4c739871867f4770ddfd":{
      "scriptId":"u1"},
    "7d5d03914b4442a3bc98f8d5bf030794":{
      "scriptId":"u2"},
    "4182c4eeb0184eccb74537cddf168486":{
      "scriptId":"u3"},
    "521707aa6481498690d7c166c8afbb73":{
      "scriptId":"u4"},
    "4532c1d69932453890c079347d68bd49":{
      "scriptId":"u5"},
    "f529db701af448c68fced213ec4edb94":{
      "scriptId":"u6"},
    "0b9239278b1c44fe83f51b9db596583c":{
      "scriptId":"u7"}}});