$axure.loadCurrentPage({
  "url":"新页面_1.html",
  "generationDate":new Date(1662692043976.78),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"3b3e7e96c8a3406fae362fc460cfed23",
    "type":"Axure:Page",
    "name":"新页面 1",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"708d74b772c949e588ea62e02ebc064f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":27,
              "y":10},
            "size":{
              "width":843,
              "height":369},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"37ce5a65a4584e5ea586ec4213eb0d92",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":27,
                  "y":10},
                "size":{
                  "width":843,
                  "height":369},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新页面_1/u0.png"}},
{
          "id":"a2a4a6bf7671404abee29de02630debd",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":400},
            "size":{
              "width":600,
              "height":90}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d6a3cc5146cc45099673272ceb9b0a66",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "size":{
                  "width":93,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"9646923227184e22838e5ff06b0d0a12",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "size":{
                      "width":93,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/新页面_1/u3.png"}},
{
              "id":"ec8385ad921d4dbaaadab1f20ad799a6",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":30},
                "size":{
                  "width":93,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"776124e7d89f4afeb0ae5f47d048d51b",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":30},
                    "size":{
                      "width":93,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/新页面_1/u3.png"}},
{
              "id":"dd374d684cd948ffbf4cea4f6b027f74",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":60},
                "size":{
                  "width":93,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"9bcbfc41b7e34392b9bc5e5834993557",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":60},
                    "size":{
                      "width":93,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/新页面_1/u19.png"}},
{
              "id":"48eb1c554b63425086ea9559f61c74a1",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":93,
                  "y":0},
                "size":{
                  "width":207,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"780bf5eb92c14e3196d038368c9bea4b",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":93,
                      "y":0},
                    "size":{
                      "width":207,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/新页面_1/u5.png"}},
{
              "id":"a29bbc00473949cc836ff8da95b8a08c",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":93,
                  "y":30},
                "size":{
                  "width":207,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"6df420b021a14c70b5a78dcd16517fc1",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":93,
                      "y":30},
                    "size":{
                      "width":207,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/新页面_1/u5.png"}},
{
              "id":"1b701bb480c84954aac9f4327f637d1c",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":93,
                  "y":60},
                "size":{
                  "width":207,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"0e272576217745fdbbf5bdc6bfcfbeff",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":93,
                      "y":60},
                    "size":{
                      "width":207,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/新页面_1/u21.png"}},
{
              "id":"faa27ad07f144a899820c5b978600e74",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":300,
                  "y":0},
                "size":{
                  "width":191,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"64fe9a9f5ecb426c95d5dbfbc2493ce7",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":300,
                      "y":0},
                    "size":{
                      "width":191,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/新页面_1/u7.png"}},
{
              "id":"1cd868ad87154baea4b18c00ede32b04",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":300,
                  "y":30},
                "size":{
                  "width":191,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"900991132cfd4ed1b78a2fa4a012b705",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":300,
                      "y":30},
                    "size":{
                      "width":191,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/新页面_1/u7.png"}},
{
              "id":"9d258bfcaa0948b3888b5579609797dd",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":300,
                  "y":60},
                "size":{
                  "width":191,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"9bb78ab139894457af442b0baae4c680",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":300,
                      "y":60},
                    "size":{
                      "width":191,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/新页面_1/u23.png"}},
{
              "id":"68a4ce30bef4470aa39ddfa80d7d48f0",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":491,
                  "y":0},
                "size":{
                  "width":109,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"9b7ee338d73148f18073bf500fc89260",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":491,
                      "y":0},
                    "size":{
                      "width":109,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/新页面_1/u9.png"}},
{
              "id":"1279350e689b46499fcf587a8d077835",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":491,
                  "y":30},
                "size":{
                  "width":109,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"c356601ff6cd42fea8eae1be4b2a01e3",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":491,
                      "y":30},
                    "size":{
                      "width":109,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/新页面_1/u9.png"}},
{
              "id":"523638634a7b439a9976c330dec9d0fc",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":491,
                  "y":60},
                "size":{
                  "width":109,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"1f534803101d40a39745abfaf0358aec",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":491,
                      "y":60},
                    "size":{
                      "width":109,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/新页面_1/u25.png"}}]},
{
          "id":"fde2581d625c4bc9bc33eae2a57a92a1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":730,
              "y":400},
            "size":{
              "width":6,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dd742d4d40b84d1584a7dcc8e3b1abe3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":730,
                  "y":400},
                "size":{
                  "width":6,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"acde297db3b940ddbd125b73c1bd2d24",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":666,
              "y":394},
            "size":{
              "width":80,
              "height":71}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"596a4f5e4dca4a45a706bc87b0c309e6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":666,
                  "y":394},
                "size":{
                  "width":80,
                  "height":71}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新页面_1/u29.png"}},
{
          "id":"a211ededd740462e9aab5f209c4efe07",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":39,
              "y":353},
            "size":{
              "width":841,
              "height":36},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a34992ddd4da4379a37866679e6ba0bc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":39,
                  "y":353},
                "size":{
                  "width":841,
                  "height":36},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新页面_1/u31.png"}},
{
          "id":"1aca413027e441cab354ac20401ea694",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":39,
              "y":534},
            "size":{
              "width":841,
              "height":36},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b429ad78c645411297265fb59fde5e82",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":39,
                  "y":534},
                "size":{
                  "width":841,
                  "height":36},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新页面_1/u33.png"}},
{
          "id":"904ef04d8c5247b2b98e59576bc629d3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF008000,
              "opacity":1},
            "location":{
              "x":110,
              "y":363},
            "size":{
              "width":41,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5545ac2d9858494998da4b260285c71e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF008000,
                  "opacity":1},
                "location":{
                  "x":110,
                  "y":363},
                "size":{
                  "width":41,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7618400cc519482d8716153f37a63b1c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF008000,
              "opacity":1},
            "location":{
              "x":110,
              "y":544},
            "size":{
              "width":41,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"88ac0338fe72451e936053b32aaf6676",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF008000,
                  "opacity":1},
                "location":{
                  "x":110,
                  "y":544},
                "size":{
                  "width":41,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a8ba17d4c23b40d0a13bdf3ec3696908",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF008000,
              "opacity":1},
            "location":{
              "x":292,
              "y":544},
            "size":{
              "width":28,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"31e43fa17c0f45909897fa0923b376f1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF008000,
                  "opacity":1},
                "location":{
                  "x":292,
                  "y":544},
                "size":{
                  "width":28,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e084693f91ee42ecbf389d5710352b38",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF008000,
              "opacity":1},
            "location":{
              "x":459,
              "y":544},
            "size":{
              "width":28,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a5885e6a57bf44da9a3dc3840508d56d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF008000,
                  "opacity":1},
                "location":{
                  "x":459,
                  "y":544},
                "size":{
                  "width":28,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"778b05689899414385d131bd7feca4d0",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":52.5,
              "y":634},
            "size":{
              "width":841,
              "height":36},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e4d01d259a76415992461eb4d1a01e68",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":52.5,
                  "y":634},
                "size":{
                  "width":841,
                  "height":36},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新页面_1/u43.png"}},
{
          "id":"6a5ed44445374721a9f067c19caee889",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF008000,
              "opacity":1},
            "location":{
              "x":139,
              "y":644},
            "size":{
              "width":41,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0a3c029ac6554792a0235527a10ba258",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF008000,
                  "opacity":1},
                "location":{
                  "x":139,
                  "y":644},
                "size":{
                  "width":41,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f72100fa55c24b369b855e98518a2aef",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF008000,
              "opacity":1},
            "location":{
              "x":472,
              "y":644},
            "size":{
              "width":28,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"234fd35bb7574555a63d078ed2384ccb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF008000,
                  "opacity":1},
                "location":{
                  "x":472,
                  "y":644},
                "size":{
                  "width":28,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6220c4179665444d822f2622fa22417f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF008000,
              "opacity":1},
            "location":{
              "x":640,
              "y":644},
            "size":{
              "width":28,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b7eb2cd82a1a4ef1bce027f6443ab05d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF008000,
                  "opacity":1},
                "location":{
                  "x":640,
                  "y":644},
                "size":{
                  "width":28,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"44e9e4c901db4d0980daadbc8ad8594d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF008000,
              "opacity":1},
            "location":{
              "x":802,
              "y":644},
            "size":{
              "width":54,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6ab7d82b799d4607b255bcc8c8f876c7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF008000,
                  "opacity":1},
                "location":{
                  "x":802,
                  "y":644},
                "size":{
                  "width":54,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"920c54bc080f4ee9990bebb8e0eb38f6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":266,
              "y":644},
            "size":{
              "width":74,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ba584f4e634a4da48e41670e8bdae5d0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":266,
                  "y":644},
                "size":{
                  "width":74,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新页面_1/u53.png"}},
{
          "id":"58f766a81a6b46d6917c17c73b82ec6e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF008000,
              "opacity":1},
            "location":{
              "x":276,
              "y":644},
            "size":{
              "width":54,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4ddd750f6cee4f40a7b69fd4ef99209b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF008000,
                  "opacity":1},
                "location":{
                  "x":276,
                  "y":644},
                "size":{
                  "width":54,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b2260c4365e340078e5271c61ebade3f",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":195,
              "y":670},
            "size":{
              "width":545,
              "height":70}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7f1978169afd42468261ac746518170e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":195,
                  "y":670},
                "size":{
                  "width":545,
                  "height":70}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新页面_1/u57.png"}},
{
          "id":"df33f7e2f21e49579093e96b0011c69c",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":459,
              "y":660},
            "size":{
              "width":31,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d2b216d4a16f4625a8c8486c03d5639e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":459,
                  "y":660},
                "size":{
                  "width":31,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新页面_1/u59.png"}},
{
          "id":"601ffb950845493cbb50b0f927255be9",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":212,
              "y":680},
            "size":{
              "width":508,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9b63d1694f0b42dea6de1ca125beac4f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":212,
                  "y":680},
                "size":{
                  "width":508,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新页面_1/u61.png"}},
{
          "id":"a51fddc0400d4d4ca4c423053bce3c8e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":677,
              "y":353},
            "size":{
              "width":202,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"105be70a851c435ba42e9ccfaeb0eaa2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":677,
                  "y":353},
                "size":{
                  "width":202,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "708d74b772c949e588ea62e02ebc064f":{
      "scriptId":"u0"},
    "37ce5a65a4584e5ea586ec4213eb0d92":{
      "scriptId":"u1"},
    "a2a4a6bf7671404abee29de02630debd":{
      "scriptId":"u2"},
    "d6a3cc5146cc45099673272ceb9b0a66":{
      "scriptId":"u3"},
    "9646923227184e22838e5ff06b0d0a12":{
      "scriptId":"u4"},
    "48eb1c554b63425086ea9559f61c74a1":{
      "scriptId":"u5"},
    "780bf5eb92c14e3196d038368c9bea4b":{
      "scriptId":"u6"},
    "faa27ad07f144a899820c5b978600e74":{
      "scriptId":"u7"},
    "64fe9a9f5ecb426c95d5dbfbc2493ce7":{
      "scriptId":"u8"},
    "68a4ce30bef4470aa39ddfa80d7d48f0":{
      "scriptId":"u9"},
    "9b7ee338d73148f18073bf500fc89260":{
      "scriptId":"u10"},
    "ec8385ad921d4dbaaadab1f20ad799a6":{
      "scriptId":"u11"},
    "776124e7d89f4afeb0ae5f47d048d51b":{
      "scriptId":"u12"},
    "a29bbc00473949cc836ff8da95b8a08c":{
      "scriptId":"u13"},
    "6df420b021a14c70b5a78dcd16517fc1":{
      "scriptId":"u14"},
    "1cd868ad87154baea4b18c00ede32b04":{
      "scriptId":"u15"},
    "900991132cfd4ed1b78a2fa4a012b705":{
      "scriptId":"u16"},
    "1279350e689b46499fcf587a8d077835":{
      "scriptId":"u17"},
    "c356601ff6cd42fea8eae1be4b2a01e3":{
      "scriptId":"u18"},
    "dd374d684cd948ffbf4cea4f6b027f74":{
      "scriptId":"u19"},
    "9bcbfc41b7e34392b9bc5e5834993557":{
      "scriptId":"u20"},
    "1b701bb480c84954aac9f4327f637d1c":{
      "scriptId":"u21"},
    "0e272576217745fdbbf5bdc6bfcfbeff":{
      "scriptId":"u22"},
    "9d258bfcaa0948b3888b5579609797dd":{
      "scriptId":"u23"},
    "9bb78ab139894457af442b0baae4c680":{
      "scriptId":"u24"},
    "523638634a7b439a9976c330dec9d0fc":{
      "scriptId":"u25"},
    "1f534803101d40a39745abfaf0358aec":{
      "scriptId":"u26"},
    "fde2581d625c4bc9bc33eae2a57a92a1":{
      "scriptId":"u27"},
    "dd742d4d40b84d1584a7dcc8e3b1abe3":{
      "scriptId":"u28"},
    "acde297db3b940ddbd125b73c1bd2d24":{
      "scriptId":"u29"},
    "596a4f5e4dca4a45a706bc87b0c309e6":{
      "scriptId":"u30"},
    "a211ededd740462e9aab5f209c4efe07":{
      "scriptId":"u31"},
    "a34992ddd4da4379a37866679e6ba0bc":{
      "scriptId":"u32"},
    "1aca413027e441cab354ac20401ea694":{
      "scriptId":"u33"},
    "b429ad78c645411297265fb59fde5e82":{
      "scriptId":"u34"},
    "904ef04d8c5247b2b98e59576bc629d3":{
      "scriptId":"u35"},
    "5545ac2d9858494998da4b260285c71e":{
      "scriptId":"u36"},
    "7618400cc519482d8716153f37a63b1c":{
      "scriptId":"u37"},
    "88ac0338fe72451e936053b32aaf6676":{
      "scriptId":"u38"},
    "a8ba17d4c23b40d0a13bdf3ec3696908":{
      "scriptId":"u39"},
    "31e43fa17c0f45909897fa0923b376f1":{
      "scriptId":"u40"},
    "e084693f91ee42ecbf389d5710352b38":{
      "scriptId":"u41"},
    "a5885e6a57bf44da9a3dc3840508d56d":{
      "scriptId":"u42"},
    "778b05689899414385d131bd7feca4d0":{
      "scriptId":"u43"},
    "e4d01d259a76415992461eb4d1a01e68":{
      "scriptId":"u44"},
    "6a5ed44445374721a9f067c19caee889":{
      "scriptId":"u45"},
    "0a3c029ac6554792a0235527a10ba258":{
      "scriptId":"u46"},
    "f72100fa55c24b369b855e98518a2aef":{
      "scriptId":"u47"},
    "234fd35bb7574555a63d078ed2384ccb":{
      "scriptId":"u48"},
    "6220c4179665444d822f2622fa22417f":{
      "scriptId":"u49"},
    "b7eb2cd82a1a4ef1bce027f6443ab05d":{
      "scriptId":"u50"},
    "44e9e4c901db4d0980daadbc8ad8594d":{
      "scriptId":"u51"},
    "6ab7d82b799d4607b255bcc8c8f876c7":{
      "scriptId":"u52"},
    "920c54bc080f4ee9990bebb8e0eb38f6":{
      "scriptId":"u53"},
    "ba584f4e634a4da48e41670e8bdae5d0":{
      "scriptId":"u54"},
    "58f766a81a6b46d6917c17c73b82ec6e":{
      "scriptId":"u55"},
    "4ddd750f6cee4f40a7b69fd4ef99209b":{
      "scriptId":"u56"},
    "b2260c4365e340078e5271c61ebade3f":{
      "scriptId":"u57"},
    "7f1978169afd42468261ac746518170e":{
      "scriptId":"u58"},
    "df33f7e2f21e49579093e96b0011c69c":{
      "scriptId":"u59"},
    "d2b216d4a16f4625a8c8486c03d5639e":{
      "scriptId":"u60"},
    "601ffb950845493cbb50b0f927255be9":{
      "scriptId":"u61"},
    "9b63d1694f0b42dea6de1ca125beac4f":{
      "scriptId":"u62"},
    "a51fddc0400d4d4ca4c423053bce3c8e":{
      "scriptId":"u63"},
    "105be70a851c435ba42e9ccfaeb0eaa2":{
      "scriptId":"u64"}}});