$axure.loadCurrentPage({
  "url":"新页面_1.html",
  "generationDate":new Date(1663837683218.1),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"3b3e7e96c8a3406fae362fc460cfed23",
    "type":"Axure:Page",
    "name":"新页面 1",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"265555a55ea944d0898a73afe961b730",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":44,
              "y":997},
            "size":{
              "width":606,
              "height":133}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1e1f829c23334f948ee5a68945ac1849",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":44,
                  "y":997},
                "size":{
                  "width":606,
                  "height":133}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新页面_1/u0.png"}},
{
          "id":"708d74b772c949e588ea62e02ebc064f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":27,
              "y":10},
            "size":{
              "width":843,
              "height":369},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"37ce5a65a4584e5ea586ec4213eb0d92",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":27,
                  "y":10},
                "size":{
                  "width":843,
                  "height":369},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新页面_1/u2.png"}},
{
          "id":"a2a4a6bf7671404abee29de02630debd",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":400},
            "size":{
              "width":600,
              "height":90}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d6a3cc5146cc45099673272ceb9b0a66",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "size":{
                  "width":93,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"9646923227184e22838e5ff06b0d0a12",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "size":{
                      "width":93,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/新页面_1/u5.png"}},
{
              "id":"ec8385ad921d4dbaaadab1f20ad799a6",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":30},
                "size":{
                  "width":93,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"776124e7d89f4afeb0ae5f47d048d51b",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":30},
                    "size":{
                      "width":93,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/新页面_1/u5.png"}},
{
              "id":"dd374d684cd948ffbf4cea4f6b027f74",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":60},
                "size":{
                  "width":93,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"9bcbfc41b7e34392b9bc5e5834993557",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":60},
                    "size":{
                      "width":93,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/新页面_1/u21.png"}},
{
              "id":"48eb1c554b63425086ea9559f61c74a1",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":93,
                  "y":0},
                "size":{
                  "width":207,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"780bf5eb92c14e3196d038368c9bea4b",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":93,
                      "y":0},
                    "size":{
                      "width":207,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/新页面_1/u7.png"}},
{
              "id":"a29bbc00473949cc836ff8da95b8a08c",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":93,
                  "y":30},
                "size":{
                  "width":207,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"6df420b021a14c70b5a78dcd16517fc1",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":93,
                      "y":30},
                    "size":{
                      "width":207,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/新页面_1/u7.png"}},
{
              "id":"1b701bb480c84954aac9f4327f637d1c",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":93,
                  "y":60},
                "size":{
                  "width":207,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"0e272576217745fdbbf5bdc6bfcfbeff",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":93,
                      "y":60},
                    "size":{
                      "width":207,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/新页面_1/u23.png"}},
{
              "id":"faa27ad07f144a899820c5b978600e74",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":300,
                  "y":0},
                "size":{
                  "width":191,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"64fe9a9f5ecb426c95d5dbfbc2493ce7",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":300,
                      "y":0},
                    "size":{
                      "width":191,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/新页面_1/u9.png"}},
{
              "id":"1cd868ad87154baea4b18c00ede32b04",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":300,
                  "y":30},
                "size":{
                  "width":191,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"900991132cfd4ed1b78a2fa4a012b705",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":300,
                      "y":30},
                    "size":{
                      "width":191,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/新页面_1/u9.png"}},
{
              "id":"9d258bfcaa0948b3888b5579609797dd",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":300,
                  "y":60},
                "size":{
                  "width":191,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"9bb78ab139894457af442b0baae4c680",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":300,
                      "y":60},
                    "size":{
                      "width":191,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/新页面_1/u25.png"}},
{
              "id":"68a4ce30bef4470aa39ddfa80d7d48f0",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":491,
                  "y":0},
                "size":{
                  "width":109,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"9b7ee338d73148f18073bf500fc89260",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":491,
                      "y":0},
                    "size":{
                      "width":109,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/新页面_1/u11.png"}},
{
              "id":"1279350e689b46499fcf587a8d077835",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":491,
                  "y":30},
                "size":{
                  "width":109,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"c356601ff6cd42fea8eae1be4b2a01e3",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":491,
                      "y":30},
                    "size":{
                      "width":109,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/新页面_1/u11.png"}},
{
              "id":"523638634a7b439a9976c330dec9d0fc",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":491,
                  "y":60},
                "size":{
                  "width":109,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"1f534803101d40a39745abfaf0358aec",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":491,
                      "y":60},
                    "size":{
                      "width":109,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/新页面_1/u27.png"}}]},
{
          "id":"fde2581d625c4bc9bc33eae2a57a92a1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":730,
              "y":400},
            "size":{
              "width":6,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dd742d4d40b84d1584a7dcc8e3b1abe3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":730,
                  "y":400},
                "size":{
                  "width":6,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"acde297db3b940ddbd125b73c1bd2d24",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":666,
              "y":394},
            "size":{
              "width":80,
              "height":71}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"596a4f5e4dca4a45a706bc87b0c309e6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":666,
                  "y":394},
                "size":{
                  "width":80,
                  "height":71}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新页面_1/u31.png"}},
{
          "id":"a211ededd740462e9aab5f209c4efe07",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":39,
              "y":353},
            "size":{
              "width":841,
              "height":36},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a34992ddd4da4379a37866679e6ba0bc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":39,
                  "y":353},
                "size":{
                  "width":841,
                  "height":36},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新页面_1/u33.png"}},
{
          "id":"1aca413027e441cab354ac20401ea694",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":39,
              "y":534},
            "size":{
              "width":841,
              "height":36},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b429ad78c645411297265fb59fde5e82",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":39,
                  "y":534},
                "size":{
                  "width":841,
                  "height":36},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新页面_1/u35.png"}},
{
          "id":"904ef04d8c5247b2b98e59576bc629d3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF008000,
              "opacity":1},
            "location":{
              "x":110,
              "y":363},
            "size":{
              "width":41,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5545ac2d9858494998da4b260285c71e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF008000,
                  "opacity":1},
                "location":{
                  "x":110,
                  "y":363},
                "size":{
                  "width":41,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7618400cc519482d8716153f37a63b1c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF008000,
              "opacity":1},
            "location":{
              "x":110,
              "y":544},
            "size":{
              "width":41,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"88ac0338fe72451e936053b32aaf6676",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF008000,
                  "opacity":1},
                "location":{
                  "x":110,
                  "y":544},
                "size":{
                  "width":41,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a8ba17d4c23b40d0a13bdf3ec3696908",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF008000,
              "opacity":1},
            "location":{
              "x":292,
              "y":544},
            "size":{
              "width":28,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"31e43fa17c0f45909897fa0923b376f1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF008000,
                  "opacity":1},
                "location":{
                  "x":292,
                  "y":544},
                "size":{
                  "width":28,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e084693f91ee42ecbf389d5710352b38",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF008000,
              "opacity":1},
            "location":{
              "x":459,
              "y":544},
            "size":{
              "width":28,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a5885e6a57bf44da9a3dc3840508d56d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF008000,
                  "opacity":1},
                "location":{
                  "x":459,
                  "y":544},
                "size":{
                  "width":28,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"778b05689899414385d131bd7feca4d0",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":52.5,
              "y":634},
            "size":{
              "width":841,
              "height":36},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e4d01d259a76415992461eb4d1a01e68",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":52.5,
                  "y":634},
                "size":{
                  "width":841,
                  "height":36},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新页面_1/u45.png"}},
{
          "id":"6a5ed44445374721a9f067c19caee889",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF008000,
              "opacity":1},
            "location":{
              "x":139,
              "y":644},
            "size":{
              "width":41,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0a3c029ac6554792a0235527a10ba258",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF008000,
                  "opacity":1},
                "location":{
                  "x":139,
                  "y":644},
                "size":{
                  "width":41,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f72100fa55c24b369b855e98518a2aef",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF008000,
              "opacity":1},
            "location":{
              "x":472,
              "y":644},
            "size":{
              "width":28,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"234fd35bb7574555a63d078ed2384ccb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF008000,
                  "opacity":1},
                "location":{
                  "x":472,
                  "y":644},
                "size":{
                  "width":28,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6220c4179665444d822f2622fa22417f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF008000,
              "opacity":1},
            "location":{
              "x":640,
              "y":644},
            "size":{
              "width":28,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b7eb2cd82a1a4ef1bce027f6443ab05d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF008000,
                  "opacity":1},
                "location":{
                  "x":640,
                  "y":644},
                "size":{
                  "width":28,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"44e9e4c901db4d0980daadbc8ad8594d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF008000,
              "opacity":1},
            "location":{
              "x":802,
              "y":644},
            "size":{
              "width":54,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6ab7d82b799d4607b255bcc8c8f876c7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF008000,
                  "opacity":1},
                "location":{
                  "x":802,
                  "y":644},
                "size":{
                  "width":54,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"920c54bc080f4ee9990bebb8e0eb38f6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":266,
              "y":644},
            "size":{
              "width":74,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ba584f4e634a4da48e41670e8bdae5d0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":266,
                  "y":644},
                "size":{
                  "width":74,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新页面_1/u55.png"}},
{
          "id":"58f766a81a6b46d6917c17c73b82ec6e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF008000,
              "opacity":1},
            "location":{
              "x":276,
              "y":644},
            "size":{
              "width":54,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4ddd750f6cee4f40a7b69fd4ef99209b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF008000,
                  "opacity":1},
                "location":{
                  "x":276,
                  "y":644},
                "size":{
                  "width":54,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b2260c4365e340078e5271c61ebade3f",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":195,
              "y":670},
            "size":{
              "width":545,
              "height":70}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7f1978169afd42468261ac746518170e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":195,
                  "y":670},
                "size":{
                  "width":545,
                  "height":70}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新页面_1/u59.png"}},
{
          "id":"df33f7e2f21e49579093e96b0011c69c",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":459,
              "y":660},
            "size":{
              "width":31,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d2b216d4a16f4625a8c8486c03d5639e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":459,
                  "y":660},
                "size":{
                  "width":31,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新页面_1/u61.png"}},
{
          "id":"601ffb950845493cbb50b0f927255be9",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":212,
              "y":680},
            "size":{
              "width":508,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9b63d1694f0b42dea6de1ca125beac4f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":212,
                  "y":680},
                "size":{
                  "width":508,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新页面_1/u63.png"}},
{
          "id":"a51fddc0400d4d4ca4c423053bce3c8e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":677,
              "y":353},
            "size":{
              "width":202,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"105be70a851c435ba42e9ccfaeb0eaa2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":677,
                  "y":353},
                "size":{
                  "width":202,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"12688fc1195642ecac58f6563582964c",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":52,
              "y":840},
            "size":{
              "width":750,
              "height":90}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dc9ceb6ed8964574866223547a500537",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "size":{
                  "width":171,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"d2ccf5043dbd4d5399f67a338c2aa4e7",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "size":{
                      "width":171,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/新页面_1/u68.png"}},
{
              "id":"8424e9a1d4784f5ea4a937fc82da6786",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "underline":true,
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":0,
                  "y":30},
                "size":{
                  "width":171,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"b34bfc9ddfeb42359e6eb7d41e6370d3",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "underline":true,
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0000FF,
                      "opacity":1},
                    "location":{
                      "x":0,
                      "y":30},
                    "size":{
                      "width":171,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/新页面_1/u68.png"}},
{
              "id":"4e6565ca9fee415da3ec2f222cd6ac0b",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "underline":true,
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":0,
                  "y":60},
                "size":{
                  "width":171,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"1f0e2475b4634066b088ee722954968a",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "underline":true,
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0000FF,
                      "opacity":1},
                    "location":{
                      "x":0,
                      "y":60},
                    "size":{
                      "width":171,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/新页面_1/u88.png"}},
{
              "id":"1e0fdad379cd4e4189c19eb315119602",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":171,
                  "y":0},
                "size":{
                  "width":108,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"dec82858cb44474d84ad8e46d2e60e63",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":171,
                      "y":0},
                    "size":{
                      "width":108,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/新页面_1/u70.png"}},
{
              "id":"07912fad27d44a60b964cb20cdecd96c",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":171,
                  "y":30},
                "size":{
                  "width":108,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"eac0ecc5e8d54a428be1cdff56552b83",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":171,
                      "y":30},
                    "size":{
                      "width":108,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/新页面_1/u70.png"}},
{
              "id":"7a23fb323b294502bddc44fe27ddc2fb",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":171,
                  "y":60},
                "size":{
                  "width":108,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"920691f56f5e4391a2fd2a10c19df095",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":171,
                      "y":60},
                    "size":{
                      "width":108,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/新页面_1/u90.png"}},
{
              "id":"9aaea09f8f91487da36eee49c3149d6c",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":279,
                  "y":0},
                "size":{
                  "width":212,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"cea024ff6bf64a9a8d2be59f81cbe384",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":279,
                      "y":0},
                    "size":{
                      "width":212,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/新页面_1/u72.png"}},
{
              "id":"def3089013bc4086bae3860a7ecaa534",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":279,
                  "y":30},
                "size":{
                  "width":212,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"6676861bac974efbb446a4521ca51eb7",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":279,
                      "y":30},
                    "size":{
                      "width":212,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/新页面_1/u72.png"}},
{
              "id":"2e00525a84694ef7bc491d2c087af26e",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":279,
                  "y":60},
                "size":{
                  "width":212,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"2d663e1e330b4d4f8de74229c5bf7b60",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":279,
                      "y":60},
                    "size":{
                      "width":212,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/新页面_1/u92.png"}},
{
              "id":"03d10c8f5865479bb7ea45cdfcc7e8d6",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":601,
                  "y":0},
                "size":{
                  "width":149,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"71d17dc26d7b488f9398a758a51d2dbc",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":601,
                      "y":0},
                    "size":{
                      "width":149,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/新页面_1/u76.png"}},
{
              "id":"4be46b261a3b475e98ffd3f1694be2f6",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":601,
                  "y":30},
                "size":{
                  "width":149,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"79fb68633db4446abf12ee74b37c613b",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":601,
                      "y":30},
                    "size":{
                      "width":149,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/新页面_1/u76.png"}},
{
              "id":"bd4f7bed6e1042a9bdb88ccd44790ecd",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":601,
                  "y":60},
                "size":{
                  "width":149,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"3e41c28997864483aaeefa2350a4da2e",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":601,
                      "y":60},
                    "size":{
                      "width":149,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/新页面_1/u96.png"}},
{
              "id":"a48643130f624844909921b6cb4ff3f5",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":491,
                  "y":0},
                "size":{
                  "width":110,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"91ce779dcc3f487a81342fb471303dd0",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":491,
                      "y":0},
                    "size":{
                      "width":110,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/新页面_1/u74.png"}},
{
              "id":"b0f2964c2e9d4c27a6d5387a31f7e1d3",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":491,
                  "y":30},
                "size":{
                  "width":110,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"958f47253fa6426987950cedf7ae5242",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":491,
                      "y":30},
                    "size":{
                      "width":110,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/新页面_1/u74.png"}},
{
              "id":"52b5f419825240508b15da7ed7249285",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":491,
                  "y":60},
                "size":{
                  "width":110,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"fdb9bd13a65a4513836eacfee953a882",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":491,
                      "y":60},
                    "size":{
                      "width":110,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/新页面_1/u94.png"}}]},
{
          "id":"8e177c97aa9646988500e0a3a9143bc5",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":52,
              "y":792},
            "size":{
              "width":65,
              "height":38}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"376ecc60250142168c3b190f0793b721",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":52,
                  "y":792},
                "size":{
                  "width":65,
                  "height":38}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2dcbf0b0a3984f34acdb5d4c599b1df1",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":802,
              "y":840},
            "size":{
              "width":80,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"708c46784ba24ef28a810abfcfa33780",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":802,
                  "y":840},
                "size":{
                  "width":80,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新页面_1/u31.png"}},
{
          "id":"68729afb229048e1a4b7319a48217406",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":52,
              "y":1020},
            "size":{
              "width":54,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"20ec619a99094324a535c13f5448fc1d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":52,
                  "y":1020},
                "size":{
                  "width":54,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a3ed0ce819f24a419a784b9e3d2ec046",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":116,
              "y":1016},
            "size":{
              "width":114,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"904eccc40401427eaa0fb97221180db9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":230,
              "y":1020},
            "size":{
              "width":14,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"871c4d619bcd4807b40b7f042033ac01",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":230,
                  "y":1020},
                "size":{
                  "width":14,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ac891936f5074be497a85c78772b0da2",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":254,
              "y":1017},
            "size":{
              "width":76,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"3db0113321ab419394bf6ef2e6fd1c1e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":380,
              "y":1020},
            "size":{
              "width":28,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7a04fc2a6337455ca846a611bb711aa0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":380,
                  "y":1020},
                "size":{
                  "width":28,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"719305f92b544613867653bf7b552598",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":418,
              "y":1016},
            "size":{
              "width":162,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"23fa875d8eaa4e4bad2926c71cee32a4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":587,
              "y":1020},
            "size":{
              "width":13,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e346f56ac4304c91b87c8dfa797b8493",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":587,
                  "y":1020},
                "size":{
                  "width":13,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "265555a55ea944d0898a73afe961b730":{
      "scriptId":"u0"},
    "1e1f829c23334f948ee5a68945ac1849":{
      "scriptId":"u1"},
    "708d74b772c949e588ea62e02ebc064f":{
      "scriptId":"u2"},
    "37ce5a65a4584e5ea586ec4213eb0d92":{
      "scriptId":"u3"},
    "a2a4a6bf7671404abee29de02630debd":{
      "scriptId":"u4"},
    "d6a3cc5146cc45099673272ceb9b0a66":{
      "scriptId":"u5"},
    "9646923227184e22838e5ff06b0d0a12":{
      "scriptId":"u6"},
    "48eb1c554b63425086ea9559f61c74a1":{
      "scriptId":"u7"},
    "780bf5eb92c14e3196d038368c9bea4b":{
      "scriptId":"u8"},
    "faa27ad07f144a899820c5b978600e74":{
      "scriptId":"u9"},
    "64fe9a9f5ecb426c95d5dbfbc2493ce7":{
      "scriptId":"u10"},
    "68a4ce30bef4470aa39ddfa80d7d48f0":{
      "scriptId":"u11"},
    "9b7ee338d73148f18073bf500fc89260":{
      "scriptId":"u12"},
    "ec8385ad921d4dbaaadab1f20ad799a6":{
      "scriptId":"u13"},
    "776124e7d89f4afeb0ae5f47d048d51b":{
      "scriptId":"u14"},
    "a29bbc00473949cc836ff8da95b8a08c":{
      "scriptId":"u15"},
    "6df420b021a14c70b5a78dcd16517fc1":{
      "scriptId":"u16"},
    "1cd868ad87154baea4b18c00ede32b04":{
      "scriptId":"u17"},
    "900991132cfd4ed1b78a2fa4a012b705":{
      "scriptId":"u18"},
    "1279350e689b46499fcf587a8d077835":{
      "scriptId":"u19"},
    "c356601ff6cd42fea8eae1be4b2a01e3":{
      "scriptId":"u20"},
    "dd374d684cd948ffbf4cea4f6b027f74":{
      "scriptId":"u21"},
    "9bcbfc41b7e34392b9bc5e5834993557":{
      "scriptId":"u22"},
    "1b701bb480c84954aac9f4327f637d1c":{
      "scriptId":"u23"},
    "0e272576217745fdbbf5bdc6bfcfbeff":{
      "scriptId":"u24"},
    "9d258bfcaa0948b3888b5579609797dd":{
      "scriptId":"u25"},
    "9bb78ab139894457af442b0baae4c680":{
      "scriptId":"u26"},
    "523638634a7b439a9976c330dec9d0fc":{
      "scriptId":"u27"},
    "1f534803101d40a39745abfaf0358aec":{
      "scriptId":"u28"},
    "fde2581d625c4bc9bc33eae2a57a92a1":{
      "scriptId":"u29"},
    "dd742d4d40b84d1584a7dcc8e3b1abe3":{
      "scriptId":"u30"},
    "acde297db3b940ddbd125b73c1bd2d24":{
      "scriptId":"u31"},
    "596a4f5e4dca4a45a706bc87b0c309e6":{
      "scriptId":"u32"},
    "a211ededd740462e9aab5f209c4efe07":{
      "scriptId":"u33"},
    "a34992ddd4da4379a37866679e6ba0bc":{
      "scriptId":"u34"},
    "1aca413027e441cab354ac20401ea694":{
      "scriptId":"u35"},
    "b429ad78c645411297265fb59fde5e82":{
      "scriptId":"u36"},
    "904ef04d8c5247b2b98e59576bc629d3":{
      "scriptId":"u37"},
    "5545ac2d9858494998da4b260285c71e":{
      "scriptId":"u38"},
    "7618400cc519482d8716153f37a63b1c":{
      "scriptId":"u39"},
    "88ac0338fe72451e936053b32aaf6676":{
      "scriptId":"u40"},
    "a8ba17d4c23b40d0a13bdf3ec3696908":{
      "scriptId":"u41"},
    "31e43fa17c0f45909897fa0923b376f1":{
      "scriptId":"u42"},
    "e084693f91ee42ecbf389d5710352b38":{
      "scriptId":"u43"},
    "a5885e6a57bf44da9a3dc3840508d56d":{
      "scriptId":"u44"},
    "778b05689899414385d131bd7feca4d0":{
      "scriptId":"u45"},
    "e4d01d259a76415992461eb4d1a01e68":{
      "scriptId":"u46"},
    "6a5ed44445374721a9f067c19caee889":{
      "scriptId":"u47"},
    "0a3c029ac6554792a0235527a10ba258":{
      "scriptId":"u48"},
    "f72100fa55c24b369b855e98518a2aef":{
      "scriptId":"u49"},
    "234fd35bb7574555a63d078ed2384ccb":{
      "scriptId":"u50"},
    "6220c4179665444d822f2622fa22417f":{
      "scriptId":"u51"},
    "b7eb2cd82a1a4ef1bce027f6443ab05d":{
      "scriptId":"u52"},
    "44e9e4c901db4d0980daadbc8ad8594d":{
      "scriptId":"u53"},
    "6ab7d82b799d4607b255bcc8c8f876c7":{
      "scriptId":"u54"},
    "920c54bc080f4ee9990bebb8e0eb38f6":{
      "scriptId":"u55"},
    "ba584f4e634a4da48e41670e8bdae5d0":{
      "scriptId":"u56"},
    "58f766a81a6b46d6917c17c73b82ec6e":{
      "scriptId":"u57"},
    "4ddd750f6cee4f40a7b69fd4ef99209b":{
      "scriptId":"u58"},
    "b2260c4365e340078e5271c61ebade3f":{
      "scriptId":"u59"},
    "7f1978169afd42468261ac746518170e":{
      "scriptId":"u60"},
    "df33f7e2f21e49579093e96b0011c69c":{
      "scriptId":"u61"},
    "d2b216d4a16f4625a8c8486c03d5639e":{
      "scriptId":"u62"},
    "601ffb950845493cbb50b0f927255be9":{
      "scriptId":"u63"},
    "9b63d1694f0b42dea6de1ca125beac4f":{
      "scriptId":"u64"},
    "a51fddc0400d4d4ca4c423053bce3c8e":{
      "scriptId":"u65"},
    "105be70a851c435ba42e9ccfaeb0eaa2":{
      "scriptId":"u66"},
    "12688fc1195642ecac58f6563582964c":{
      "scriptId":"u67"},
    "dc9ceb6ed8964574866223547a500537":{
      "scriptId":"u68"},
    "d2ccf5043dbd4d5399f67a338c2aa4e7":{
      "scriptId":"u69"},
    "1e0fdad379cd4e4189c19eb315119602":{
      "scriptId":"u70"},
    "dec82858cb44474d84ad8e46d2e60e63":{
      "scriptId":"u71"},
    "9aaea09f8f91487da36eee49c3149d6c":{
      "scriptId":"u72"},
    "cea024ff6bf64a9a8d2be59f81cbe384":{
      "scriptId":"u73"},
    "a48643130f624844909921b6cb4ff3f5":{
      "scriptId":"u74"},
    "91ce779dcc3f487a81342fb471303dd0":{
      "scriptId":"u75"},
    "03d10c8f5865479bb7ea45cdfcc7e8d6":{
      "scriptId":"u76"},
    "71d17dc26d7b488f9398a758a51d2dbc":{
      "scriptId":"u77"},
    "8424e9a1d4784f5ea4a937fc82da6786":{
      "scriptId":"u78"},
    "b34bfc9ddfeb42359e6eb7d41e6370d3":{
      "scriptId":"u79"},
    "07912fad27d44a60b964cb20cdecd96c":{
      "scriptId":"u80"},
    "eac0ecc5e8d54a428be1cdff56552b83":{
      "scriptId":"u81"},
    "def3089013bc4086bae3860a7ecaa534":{
      "scriptId":"u82"},
    "6676861bac974efbb446a4521ca51eb7":{
      "scriptId":"u83"},
    "b0f2964c2e9d4c27a6d5387a31f7e1d3":{
      "scriptId":"u84"},
    "958f47253fa6426987950cedf7ae5242":{
      "scriptId":"u85"},
    "4be46b261a3b475e98ffd3f1694be2f6":{
      "scriptId":"u86"},
    "79fb68633db4446abf12ee74b37c613b":{
      "scriptId":"u87"},
    "4e6565ca9fee415da3ec2f222cd6ac0b":{
      "scriptId":"u88"},
    "1f0e2475b4634066b088ee722954968a":{
      "scriptId":"u89"},
    "7a23fb323b294502bddc44fe27ddc2fb":{
      "scriptId":"u90"},
    "920691f56f5e4391a2fd2a10c19df095":{
      "scriptId":"u91"},
    "2e00525a84694ef7bc491d2c087af26e":{
      "scriptId":"u92"},
    "2d663e1e330b4d4f8de74229c5bf7b60":{
      "scriptId":"u93"},
    "52b5f419825240508b15da7ed7249285":{
      "scriptId":"u94"},
    "fdb9bd13a65a4513836eacfee953a882":{
      "scriptId":"u95"},
    "bd4f7bed6e1042a9bdb88ccd44790ecd":{
      "scriptId":"u96"},
    "3e41c28997864483aaeefa2350a4da2e":{
      "scriptId":"u97"},
    "8e177c97aa9646988500e0a3a9143bc5":{
      "scriptId":"u98"},
    "376ecc60250142168c3b190f0793b721":{
      "scriptId":"u99"},
    "2dcbf0b0a3984f34acdb5d4c599b1df1":{
      "scriptId":"u100"},
    "708c46784ba24ef28a810abfcfa33780":{
      "scriptId":"u101"},
    "68729afb229048e1a4b7319a48217406":{
      "scriptId":"u102"},
    "20ec619a99094324a535c13f5448fc1d":{
      "scriptId":"u103"},
    "a3ed0ce819f24a419a784b9e3d2ec046":{
      "scriptId":"u104"},
    "904eccc40401427eaa0fb97221180db9":{
      "scriptId":"u105"},
    "871c4d619bcd4807b40b7f042033ac01":{
      "scriptId":"u106"},
    "ac891936f5074be497a85c78772b0da2":{
      "scriptId":"u107"},
    "3db0113321ab419394bf6ef2e6fd1c1e":{
      "scriptId":"u108"},
    "7a04fc2a6337455ca846a611bb711aa0":{
      "scriptId":"u109"},
    "719305f92b544613867653bf7b552598":{
      "scriptId":"u110"},
    "23fa875d8eaa4e4bad2926c71cee32a4":{
      "scriptId":"u111"},
    "e346f56ac4304c91b87c8dfa797b8493":{
      "scriptId":"u112"}}});