$axure.loadCurrentPage({
  "url":"oa对接.html",
  "generationDate":new Date(1661326032791.66),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"d7a186019c9d4b488de60fd42d47c7f3",
    "type":"Axure:Page",
    "name":"OA对接",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"1080334d1f744772b46393821bf28e11",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":130,
              "y":60},
            "size":{
              "width":300,
              "height":204}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"921064bbda60407da7fbf133146d4378",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"588b81d853f44d3ebedd21ff48551385",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/客户管理-业务数据/u515.png"}},
{
              "id":"6bb22d6ab8374ce6916ad82175334742",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":30},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"3010e6a6f66a4afeab42eb44b090a09f",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":30},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/客户管理-业务数据/u515.png"}},
{
              "id":"21e7e3c34375496dac88dfc4988832fe",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":60},
                "size":{
                  "width":100,
                  "height":84}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"e64169ec7d974be0804e85554db75892",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":60},
                    "size":{
                      "width":100,
                      "height":84}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/oa对接/u13.png"}},
{
              "id":"5c51dac2a3c54691b992a08e6e353485",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":100,
                  "y":0},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"62273b0203c74b8d8b4f7b0f7f4dec11",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":100,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/客户管理-业务数据/u515.png"}},
{
              "id":"4d0b297ba42a448cbaa113977b4afb44",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":100,
                  "y":30},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"b6c87cab661045b5a97926da3a516317",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":100,
                      "y":30},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/客户管理-业务数据/u515.png"}},
{
              "id":"807cc5f511d445eeaa2e01c4942ee9cb",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":100,
                  "y":60},
                "size":{
                  "width":100,
                  "height":84}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"dee5c1f8c4394114906f2fc30faad539",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":100,
                      "y":60},
                    "size":{
                      "width":100,
                      "height":84}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/oa对接/u13.png"}},
{
              "id":"bc1f549ebd14444e9a122f8207ce4a62",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":200,
                  "y":0},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"7ffe35ba9072429c80aff533b33dcaca",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":200,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/客户管理-业务数据/u517.png"}},
{
              "id":"ae5f6c4159b9403d855a350b27d47f1f",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":200,
                  "y":30},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"c6012ea2450741a6b9387c1409159298",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":200,
                      "y":30},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/客户管理-业务数据/u517.png"}},
{
              "id":"64da8bc53b384d3aaf3b6db76c6401d4",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":200,
                  "y":60},
                "size":{
                  "width":100,
                  "height":84}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"aa489c10020c4f8e98799c258fc3bedb",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":200,
                      "y":60},
                    "size":{
                      "width":100,
                      "height":84}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/oa对接/u17.png"}},
{
              "id":"5afbf5756b364f44b514e45c844cc568",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":144},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"4eddf522cd1d4caea07dea620d04b3d6",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":144},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/客户管理-业务数据/u515.png"}},
{
              "id":"32976b21e12749789f78e394f2db304e",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":100,
                  "y":144},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"647c99856db94fa1866c5369a9eb5c95",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":100,
                      "y":144},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/客户管理-业务数据/u515.png"}},
{
              "id":"9346569feb774ffcbb3d0c6dfab7a4ef",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":200,
                  "y":144},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"2b9e498d126c4383b72fb606254aeeed",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":200,
                      "y":144},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/客户管理-业务数据/u517.png"}},
{
              "id":"c5f29837ab5d4f4a9f34cc5e0228ed26",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":174},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"f3bb3e84cfeb44b5b11696e38035a2e5",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":174},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/贷款余额走势图/u81.png"}},
{
              "id":"78f9c6321c574cc0bf885cfa9f1f5536",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":100,
                  "y":174},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"c687f3e6a9d54977a4d4ca7740775769",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":100,
                      "y":174},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/贷款余额走势图/u81.png"}},
{
              "id":"45af4b5a3e2a41e8b301925def01a8c2",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":200,
                  "y":174},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"7e5d737ae8c948299c21b6b750c6f8fb",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":200,
                      "y":174},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/贷款余额走势图/u85.png"}}]}]}},
  "masters":{
},
  "objectPaths":{
    "1080334d1f744772b46393821bf28e11":{
      "scriptId":"u0"},
    "921064bbda60407da7fbf133146d4378":{
      "scriptId":"u1"},
    "588b81d853f44d3ebedd21ff48551385":{
      "scriptId":"u2"},
    "5c51dac2a3c54691b992a08e6e353485":{
      "scriptId":"u3"},
    "62273b0203c74b8d8b4f7b0f7f4dec11":{
      "scriptId":"u4"},
    "bc1f549ebd14444e9a122f8207ce4a62":{
      "scriptId":"u5"},
    "7ffe35ba9072429c80aff533b33dcaca":{
      "scriptId":"u6"},
    "6bb22d6ab8374ce6916ad82175334742":{
      "scriptId":"u7"},
    "3010e6a6f66a4afeab42eb44b090a09f":{
      "scriptId":"u8"},
    "4d0b297ba42a448cbaa113977b4afb44":{
      "scriptId":"u9"},
    "b6c87cab661045b5a97926da3a516317":{
      "scriptId":"u10"},
    "ae5f6c4159b9403d855a350b27d47f1f":{
      "scriptId":"u11"},
    "c6012ea2450741a6b9387c1409159298":{
      "scriptId":"u12"},
    "21e7e3c34375496dac88dfc4988832fe":{
      "scriptId":"u13"},
    "e64169ec7d974be0804e85554db75892":{
      "scriptId":"u14"},
    "807cc5f511d445eeaa2e01c4942ee9cb":{
      "scriptId":"u15"},
    "dee5c1f8c4394114906f2fc30faad539":{
      "scriptId":"u16"},
    "64da8bc53b384d3aaf3b6db76c6401d4":{
      "scriptId":"u17"},
    "aa489c10020c4f8e98799c258fc3bedb":{
      "scriptId":"u18"},
    "5afbf5756b364f44b514e45c844cc568":{
      "scriptId":"u19"},
    "4eddf522cd1d4caea07dea620d04b3d6":{
      "scriptId":"u20"},
    "32976b21e12749789f78e394f2db304e":{
      "scriptId":"u21"},
    "647c99856db94fa1866c5369a9eb5c95":{
      "scriptId":"u22"},
    "9346569feb774ffcbb3d0c6dfab7a4ef":{
      "scriptId":"u23"},
    "2b9e498d126c4383b72fb606254aeeed":{
      "scriptId":"u24"},
    "c5f29837ab5d4f4a9f34cc5e0228ed26":{
      "scriptId":"u25"},
    "f3bb3e84cfeb44b5b11696e38035a2e5":{
      "scriptId":"u26"},
    "78f9c6321c574cc0bf885cfa9f1f5536":{
      "scriptId":"u27"},
    "c687f3e6a9d54977a4d4ca7740775769":{
      "scriptId":"u28"},
    "45af4b5a3e2a41e8b301925def01a8c2":{
      "scriptId":"u29"},
    "7e5d737ae8c948299c21b6b750c6f8fb":{
      "scriptId":"u30"}}});