$axure.loadCurrentPage({
  "url":"查看数据-保经公司.html",
  "generationDate":new Date(1661416130114.12),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"b2b2d5cd549540d885e4a86ca02b0de9",
    "type":"Axure:Page",
    "name":"查看数据-保经公司",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"838e0d9e555e40519856271b46579fe1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":-8,
              "y":94},
            "size":{
              "width":1178,
              "height":556}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"24a7e020d79d47169034d2e6a7b49e67",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":-8,
                  "y":94},
                "size":{
                  "width":1178,
                  "height":556}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/查看数据-香港公司/u0.png"}},
{
          "id":"848179f3481241fe9ae0aba57b52033c",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":27,
              "y":94},
            "size":{
              "width":97,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8f905ce22942409d88c126724657648a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":27,
                  "y":94},
                "size":{
                  "width":97,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"14e0bf6a93e64983b641bfc17385c1c0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":34,
              "y":164},
            "size":{
              "width":112,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"73f16647ffb845fc810e462dc15d7790",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":34,
                  "y":164},
                "size":{
                  "width":112,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"682c82cebf934c249d4c61c26f1cb052",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "disabled":true,
          "visible":true,
          "style":{
            "location":{
              "x":146,
              "y":164.5},
            "size":{
              "width":120,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"e50d631b6fd04791b674e1c1d3ba3830",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":34,
              "y":196},
            "size":{
              "width":126,
              "height":52}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"955d62b397594e31931cfbeb6bb10e38",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "size":{
                  "width":126,
                  "height":52}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"0de7f6d8933d4e3b9a884848d3c58d2b",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFF0000,
                      "opacity":1},
                    "size":{
                      "width":126,
                      "height":52}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/查看数据-往来客户账-损益/u8.png"}}]},
{
          "id":"5e1d9ada7fed46dba7919a1db8e62357",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":302,
              "y":136},
            "size":{
              "width":54,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e1a8aa2bec7647bc8ce8799342eb70da",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":302,
                  "y":136},
                "size":{
                  "width":54,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"638536f5876b46b3ab42f2f1620578d1",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "disabled":true,
          "visible":true,
          "style":{
            "location":{
              "x":398,
              "y":132.5},
            "size":{
              "width":120,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"59ade5a89b384360bc4589d1deb8cad0",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":146,
              "y":132.5},
            "size":{
              "width":120,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"87d4972dd0324bf081f27baa89987810",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":34,
              "y":138},
            "size":{
              "width":86,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"524adc81647b49b687c2eb277d4b90fc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":34,
                  "y":138},
                "size":{
                  "width":86,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7628074c51704a4f8e79b98af7bad292",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":362,
              "y":583},
            "size":{
              "width":508,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9d5ba9f3ec6445f69147aefeed62c8fd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":362,
                  "y":583},
                "size":{
                  "width":508,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/余额_收入详情/u73.png"}},
{
          "id":"9823c2fd75634c248a33ad460214f2de",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":1200,
              "y":383},
            "size":{
              "width":166,
              "height":48}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1b22c27bd84342048b8ce606897181ad",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1200,
                  "y":383},
                "size":{
                  "width":166,
                  "height":48}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"da6908face8d444fac8b475e9529aa69",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":34,
              "y":248},
            "size":{
              "width":400,
              "height":160}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"674d3acccb994d82964e16b5529bd7c5",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "size":{
                  "width":100,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"9cc654643e7f40da8de7fd2d3c1e3896",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":100,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/客户管理-业务数据展示/u30.png"}},
{
              "id":"464d49e4e0794fe488f7d9eea15c080b",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":20},
                "size":{
                  "width":100,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"408d730d90dd4dd78f3a3f8f95017ad4",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":20},
                    "size":{
                      "width":100,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/客户管理-业务数据展示/u30.png"}},
{
              "id":"a8ec114b86b24b9291c17bb47c71b9e0",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":40},
                "size":{
                  "width":100,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"5d5be2193a3a40eabfcf7acc3f46c408",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":40},
                    "size":{
                      "width":100,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/客户管理-业务数据展示/u30.png"}},
{
              "id":"ea94000de8d44c46a5cd3c149a7b4bf1",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":60},
                "size":{
                  "width":100,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"5a2de03d31204407a1a8f2ef1807bcfb",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":60},
                    "size":{
                      "width":100,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/客户管理-业务数据展示/u30.png"}},
{
              "id":"2d32267ef956440bb70c875b8c765ee9",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":80},
                "size":{
                  "width":100,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"91ab21bd99b54dd0be67d49e1c50d0c5",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":80},
                    "size":{
                      "width":100,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/客户管理-业务数据展示/u30.png"}},
{
              "id":"0ca15924d28c433daceff68bc0a7f5b3",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":100},
                "size":{
                  "width":100,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"71bc7238293e467ea85945d541debe17",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":100},
                    "size":{
                      "width":100,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/客户管理-业务数据展示/u30.png"}},
{
              "id":"460634e4c4734baeb16249a49146a17c",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":120},
                "size":{
                  "width":100,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"6a0458782b9e48739abab2b981a9160a",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":120},
                    "size":{
                      "width":100,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/客户管理-业务数据展示/u30.png"}},
{
              "id":"73414525505043ad91fa28a427fc49e2",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":140},
                "size":{
                  "width":100,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"38d4d248215c46abb77dc0624ae9e6c7",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":140},
                    "size":{
                      "width":100,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/客户管理-业务数据展示/u60.png"}},
{
              "id":"ae8320aca6ed4277a00843e0bdd7e797",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":100,
                  "y":0},
                "size":{
                  "width":100,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"c0a0f864b01842dc896538ab25edbceb",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":100,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/客户管理-业务数据展示/u30.png"}},
{
              "id":"c7be6e2bac5c4c4d94a54e6fa38756cc",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":100,
                  "y":20},
                "size":{
                  "width":100,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"62b9978c683244af8f9dd895bcd6c8ad",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":100,
                      "y":20},
                    "size":{
                      "width":100,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/客户管理-业务数据展示/u30.png"}},
{
              "id":"f857e5c987d54a16b599e81273cbdbf7",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":100,
                  "y":40},
                "size":{
                  "width":100,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"3a7e8890e6004cf098336adf5a6db4a5",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":100,
                      "y":40},
                    "size":{
                      "width":100,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/客户管理-业务数据展示/u30.png"}},
{
              "id":"816ed0780e554c7db2a404fd2cdc23d8",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":100,
                  "y":60},
                "size":{
                  "width":100,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"928d583bd7814129bfe92dc370fa8469",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":100,
                      "y":60},
                    "size":{
                      "width":100,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/客户管理-业务数据展示/u30.png"}},
{
              "id":"221a1aed47634562a38fe0e6addb6fe0",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":100,
                  "y":80},
                "size":{
                  "width":100,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"99beaf92097b4270864fd02dbd6abf16",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":100,
                      "y":80},
                    "size":{
                      "width":100,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/客户管理-业务数据展示/u30.png"}},
{
              "id":"314001489dda4199a03a111c141a5c20",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":100,
                  "y":100},
                "size":{
                  "width":100,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"d8ceb1b09fbe47259e5f7b6c71e553c6",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":100,
                      "y":100},
                    "size":{
                      "width":100,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/客户管理-业务数据展示/u30.png"}},
{
              "id":"96c70feffc654a97960f7851854231b6",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":100,
                  "y":120},
                "size":{
                  "width":100,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"83c6bd19b9d747b497504191f2fbb7c5",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":100,
                      "y":120},
                    "size":{
                      "width":100,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/客户管理-业务数据展示/u30.png"}},
{
              "id":"ddae8df0923b42159709d4a89cfa7633",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":100,
                  "y":140},
                "size":{
                  "width":100,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"bc0453e08691411494ed5621cdbddbc0",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":100,
                      "y":140},
                    "size":{
                      "width":100,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/客户管理-业务数据展示/u60.png"}},
{
              "id":"4da24ab8d0ba4724953f02044baafd83",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":200,
                  "y":0},
                "size":{
                  "width":100,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"ca154de5c9f94700b085edd8f75efcb7",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":200,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/客户管理-业务数据展示/u30.png"}},
{
              "id":"867a46113a28467ca4d924296ad97c0f",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":200,
                  "y":20},
                "size":{
                  "width":100,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"0d74029c9d0b4c939cc2e6075bfbed58",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":200,
                      "y":20},
                    "size":{
                      "width":100,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/客户管理-业务数据展示/u30.png"}},
{
              "id":"09eeaa6e479f405081949310b0ab3fb5",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":200,
                  "y":40},
                "size":{
                  "width":100,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"91e49f402efb4915a35445bdc066eff6",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":200,
                      "y":40},
                    "size":{
                      "width":100,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/客户管理-业务数据展示/u30.png"}},
{
              "id":"7921c2d5a5ff4013aa1d1024af308cf8",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":200,
                  "y":60},
                "size":{
                  "width":100,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"e7a41b4b5f754a1daff153479ec1c112",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":200,
                      "y":60},
                    "size":{
                      "width":100,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/客户管理-业务数据展示/u30.png"}},
{
              "id":"d113c2b346674c40bc12cd78ece01139",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":200,
                  "y":80},
                "size":{
                  "width":100,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"5550616327f741f7a712863255c3eb3a",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":200,
                      "y":80},
                    "size":{
                      "width":100,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/客户管理-业务数据展示/u30.png"}},
{
              "id":"5db64e440d954afe93d58e4aad1a0e97",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":200,
                  "y":100},
                "size":{
                  "width":100,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"d186a9c293f241898e5f000cd0f5d07e",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":200,
                      "y":100},
                    "size":{
                      "width":100,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/客户管理-业务数据展示/u30.png"}},
{
              "id":"9bcf6ffb8a9c491baf4efc53ab55b5c3",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":200,
                  "y":120},
                "size":{
                  "width":100,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"ebf4fb75faf044ecaa29293688a00c0c",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":200,
                      "y":120},
                    "size":{
                      "width":100,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/客户管理-业务数据展示/u30.png"}},
{
              "id":"caec923a64844d848c07be6aaa2f4959",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":200,
                  "y":140},
                "size":{
                  "width":100,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"9204c87dee154e1e8e13c9cae91e1abf",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":200,
                      "y":140},
                    "size":{
                      "width":100,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/客户管理-业务数据展示/u60.png"}},
{
              "id":"1a35847b1d7f496386ecb7fcd84a58da",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":300,
                  "y":0},
                "size":{
                  "width":100,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"b7b8d110d85448c2a5b34c4f7292a621",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":300,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/客户管理-业务数据展示/u38.png"}},
{
              "id":"cbdf9d8a612742b38b0613d166b5fbd3",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":300,
                  "y":20},
                "size":{
                  "width":100,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"145ed035b68644688ba3dbcc4862062c",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":300,
                      "y":20},
                    "size":{
                      "width":100,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/客户管理-业务数据展示/u38.png"}},
{
              "id":"2ee75266286b41209cd56385c0b00251",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":300,
                  "y":40},
                "size":{
                  "width":100,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"2c607c62aed34f0aa2fa3843e2076d68",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":300,
                      "y":40},
                    "size":{
                      "width":100,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/客户管理-业务数据展示/u38.png"}},
{
              "id":"13330c6201764c5c8daf45e9aae9ebd8",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":300,
                  "y":60},
                "size":{
                  "width":100,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"183c5c9885a84471aab47fc31c40e83b",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":300,
                      "y":60},
                    "size":{
                      "width":100,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/客户管理-业务数据展示/u38.png"}},
{
              "id":"f1c441a8ddf64fca83b99a6bdf4ddb2e",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":300,
                  "y":80},
                "size":{
                  "width":100,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"783f6273480d45c1b9e51d52129b57fd",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":300,
                      "y":80},
                    "size":{
                      "width":100,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/客户管理-业务数据展示/u38.png"}},
{
              "id":"5ca4c33ebd624db1ae3c8f9bfdff01a4",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":300,
                  "y":100},
                "size":{
                  "width":100,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"fe97d3fd3fae41b18ad403d4a07e2ab7",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":300,
                      "y":100},
                    "size":{
                      "width":100,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/客户管理-业务数据展示/u38.png"}},
{
              "id":"7196dfb76c774cfb8ed4b6dc381c18a2",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":300,
                  "y":120},
                "size":{
                  "width":100,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"6881e78c4ab149bf8f20403ca913e8e3",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":300,
                      "y":120},
                    "size":{
                      "width":100,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/客户管理-业务数据展示/u38.png"}},
{
              "id":"16904941abb347769cb83c39d01e5aea",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":300,
                  "y":140},
                "size":{
                  "width":100,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"582f3c8d3acc4f6aa0dd289aca6f19f4",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":300,
                      "y":140},
                    "size":{
                      "width":100,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/客户管理-业务数据展示/u68.png"}}]}]}},
  "masters":{
},
  "objectPaths":{
    "838e0d9e555e40519856271b46579fe1":{
      "scriptId":"u0"},
    "24a7e020d79d47169034d2e6a7b49e67":{
      "scriptId":"u1"},
    "848179f3481241fe9ae0aba57b52033c":{
      "scriptId":"u2"},
    "8f905ce22942409d88c126724657648a":{
      "scriptId":"u3"},
    "14e0bf6a93e64983b641bfc17385c1c0":{
      "scriptId":"u4"},
    "73f16647ffb845fc810e462dc15d7790":{
      "scriptId":"u5"},
    "682c82cebf934c249d4c61c26f1cb052":{
      "scriptId":"u6"},
    "e50d631b6fd04791b674e1c1d3ba3830":{
      "scriptId":"u7"},
    "955d62b397594e31931cfbeb6bb10e38":{
      "scriptId":"u8"},
    "0de7f6d8933d4e3b9a884848d3c58d2b":{
      "scriptId":"u9"},
    "5e1d9ada7fed46dba7919a1db8e62357":{
      "scriptId":"u10"},
    "e1a8aa2bec7647bc8ce8799342eb70da":{
      "scriptId":"u11"},
    "638536f5876b46b3ab42f2f1620578d1":{
      "scriptId":"u12"},
    "59ade5a89b384360bc4589d1deb8cad0":{
      "scriptId":"u13"},
    "87d4972dd0324bf081f27baa89987810":{
      "scriptId":"u14"},
    "524adc81647b49b687c2eb277d4b90fc":{
      "scriptId":"u15"},
    "7628074c51704a4f8e79b98af7bad292":{
      "scriptId":"u16"},
    "9d5ba9f3ec6445f69147aefeed62c8fd":{
      "scriptId":"u17"},
    "9823c2fd75634c248a33ad460214f2de":{
      "scriptId":"u18"},
    "1b22c27bd84342048b8ce606897181ad":{
      "scriptId":"u19"},
    "da6908face8d444fac8b475e9529aa69":{
      "scriptId":"u20"},
    "674d3acccb994d82964e16b5529bd7c5":{
      "scriptId":"u21"},
    "9cc654643e7f40da8de7fd2d3c1e3896":{
      "scriptId":"u22"},
    "ae8320aca6ed4277a00843e0bdd7e797":{
      "scriptId":"u23"},
    "c0a0f864b01842dc896538ab25edbceb":{
      "scriptId":"u24"},
    "4da24ab8d0ba4724953f02044baafd83":{
      "scriptId":"u25"},
    "ca154de5c9f94700b085edd8f75efcb7":{
      "scriptId":"u26"},
    "1a35847b1d7f496386ecb7fcd84a58da":{
      "scriptId":"u27"},
    "b7b8d110d85448c2a5b34c4f7292a621":{
      "scriptId":"u28"},
    "464d49e4e0794fe488f7d9eea15c080b":{
      "scriptId":"u29"},
    "408d730d90dd4dd78f3a3f8f95017ad4":{
      "scriptId":"u30"},
    "c7be6e2bac5c4c4d94a54e6fa38756cc":{
      "scriptId":"u31"},
    "62b9978c683244af8f9dd895bcd6c8ad":{
      "scriptId":"u32"},
    "867a46113a28467ca4d924296ad97c0f":{
      "scriptId":"u33"},
    "0d74029c9d0b4c939cc2e6075bfbed58":{
      "scriptId":"u34"},
    "cbdf9d8a612742b38b0613d166b5fbd3":{
      "scriptId":"u35"},
    "145ed035b68644688ba3dbcc4862062c":{
      "scriptId":"u36"},
    "a8ec114b86b24b9291c17bb47c71b9e0":{
      "scriptId":"u37"},
    "5d5be2193a3a40eabfcf7acc3f46c408":{
      "scriptId":"u38"},
    "f857e5c987d54a16b599e81273cbdbf7":{
      "scriptId":"u39"},
    "3a7e8890e6004cf098336adf5a6db4a5":{
      "scriptId":"u40"},
    "09eeaa6e479f405081949310b0ab3fb5":{
      "scriptId":"u41"},
    "91e49f402efb4915a35445bdc066eff6":{
      "scriptId":"u42"},
    "2ee75266286b41209cd56385c0b00251":{
      "scriptId":"u43"},
    "2c607c62aed34f0aa2fa3843e2076d68":{
      "scriptId":"u44"},
    "ea94000de8d44c46a5cd3c149a7b4bf1":{
      "scriptId":"u45"},
    "5a2de03d31204407a1a8f2ef1807bcfb":{
      "scriptId":"u46"},
    "816ed0780e554c7db2a404fd2cdc23d8":{
      "scriptId":"u47"},
    "928d583bd7814129bfe92dc370fa8469":{
      "scriptId":"u48"},
    "7921c2d5a5ff4013aa1d1024af308cf8":{
      "scriptId":"u49"},
    "e7a41b4b5f754a1daff153479ec1c112":{
      "scriptId":"u50"},
    "13330c6201764c5c8daf45e9aae9ebd8":{
      "scriptId":"u51"},
    "183c5c9885a84471aab47fc31c40e83b":{
      "scriptId":"u52"},
    "2d32267ef956440bb70c875b8c765ee9":{
      "scriptId":"u53"},
    "91ab21bd99b54dd0be67d49e1c50d0c5":{
      "scriptId":"u54"},
    "221a1aed47634562a38fe0e6addb6fe0":{
      "scriptId":"u55"},
    "99beaf92097b4270864fd02dbd6abf16":{
      "scriptId":"u56"},
    "d113c2b346674c40bc12cd78ece01139":{
      "scriptId":"u57"},
    "5550616327f741f7a712863255c3eb3a":{
      "scriptId":"u58"},
    "f1c441a8ddf64fca83b99a6bdf4ddb2e":{
      "scriptId":"u59"},
    "783f6273480d45c1b9e51d52129b57fd":{
      "scriptId":"u60"},
    "0ca15924d28c433daceff68bc0a7f5b3":{
      "scriptId":"u61"},
    "71bc7238293e467ea85945d541debe17":{
      "scriptId":"u62"},
    "314001489dda4199a03a111c141a5c20":{
      "scriptId":"u63"},
    "d8ceb1b09fbe47259e5f7b6c71e553c6":{
      "scriptId":"u64"},
    "5db64e440d954afe93d58e4aad1a0e97":{
      "scriptId":"u65"},
    "d186a9c293f241898e5f000cd0f5d07e":{
      "scriptId":"u66"},
    "5ca4c33ebd624db1ae3c8f9bfdff01a4":{
      "scriptId":"u67"},
    "fe97d3fd3fae41b18ad403d4a07e2ab7":{
      "scriptId":"u68"},
    "460634e4c4734baeb16249a49146a17c":{
      "scriptId":"u69"},
    "6a0458782b9e48739abab2b981a9160a":{
      "scriptId":"u70"},
    "96c70feffc654a97960f7851854231b6":{
      "scriptId":"u71"},
    "83c6bd19b9d747b497504191f2fbb7c5":{
      "scriptId":"u72"},
    "9bcf6ffb8a9c491baf4efc53ab55b5c3":{
      "scriptId":"u73"},
    "ebf4fb75faf044ecaa29293688a00c0c":{
      "scriptId":"u74"},
    "7196dfb76c774cfb8ed4b6dc381c18a2":{
      "scriptId":"u75"},
    "6881e78c4ab149bf8f20403ca913e8e3":{
      "scriptId":"u76"},
    "73414525505043ad91fa28a427fc49e2":{
      "scriptId":"u77"},
    "38d4d248215c46abb77dc0624ae9e6c7":{
      "scriptId":"u78"},
    "ddae8df0923b42159709d4a89cfa7633":{
      "scriptId":"u79"},
    "bc0453e08691411494ed5621cdbddbc0":{
      "scriptId":"u80"},
    "caec923a64844d848c07be6aaa2f4959":{
      "scriptId":"u81"},
    "9204c87dee154e1e8e13c9cae91e1abf":{
      "scriptId":"u82"},
    "16904941abb347769cb83c39d01e5aea":{
      "scriptId":"u83"},
    "582f3c8d3acc4f6aa0dd289aca6f19f4":{
      "scriptId":"u84"}}});