$axure.loadCurrentPage({
  "url":"统一认证登录.html",
  "generationDate":new Date(1662070255525.86),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"5c143cba203041c7a564b9d511f538c2",
    "type":"Axure:Page",
    "name":"统一认证登录",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"f91bcb039a744eab8d8b76e4f411c166",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":87,
              "y":80},
            "size":{
              "width":652,
              "height":96}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b0513aab39cf476abfffe8a9c15ecacf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":87,
                  "y":80},
                "size":{
                  "width":652,
                  "height":96}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "f91bcb039a744eab8d8b76e4f411c166":{
      "scriptId":"u0"},
    "b0513aab39cf476abfffe8a9c15ecacf":{
      "scriptId":"u1"}}});