$axure.loadCurrentPage({
  "url":"专业公司部门经理.html",
  "generationDate":new Date(1662526079258.66),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"2677c4ed97cc49eca1fdfab339daf2e1",
    "type":"Axure:Page",
    "name":"专业公司部门经理",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"65cf160423de4fabad863a4515e49900",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":70,
              "y":40},
            "size":{
              "width":970,
              "height":500}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"483c0986e97f4afeb3938df82b838360",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":70,
                  "y":40},
                "size":{
                  "width":970,
                  "height":500}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/专业公司部门经理/u0.png"}},
{
          "id":"7d1d7d1b41514212aeb5e038f4fe828a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":90,
              "y":60},
            "size":{
              "width":230,
              "height":230}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3da3c65d178d42cdb7aa44421901dd0e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":90,
                  "y":60},
                "size":{
                  "width":230,
                  "height":230}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/客户经理/u2.png"}},
{
          "id":"e55f126f83954030a4491b936baf0911",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":90,
              "y":60},
            "size":{
              "width":230,
              "height":230}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0266f45dad5d49f187a56a80ef75d66a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":90,
                  "y":60},
                "size":{
                  "width":230,
                  "height":230}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/客户经理/u4.png"}},
{
          "id":"68cb8da51a22438b94465c1f54fa5670",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":330,
              "y":60},
            "size":{
              "width":240,
              "height":230}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f947000a083a4cc3bf060914e4825a66",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":330,
                  "y":60},
                "size":{
                  "width":240,
                  "height":230}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/客户经理/u6.png"}},
{
          "id":"4e44e304aa7341199b5f82392a8edbcf",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":580,
              "y":60},
            "size":{
              "width":260,
              "height":230},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f4c070c86efa4e4aa9e521fd70a46582",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":580,
                  "y":60},
                "size":{
                  "width":260,
                  "height":230},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/专业公司部门经理/u8.png"}},
{
          "id":"23b8a92538974d008257d2548a4bd243",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "underline":true,
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":786,
              "y":274},
            "size":{
              "width":54,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7105365307c9470086a4c7df215326fd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "underline":true,
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":786,
                  "y":274},
                "size":{
                  "width":54,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"def8fc5f41f04009ac435089071c48e9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":90,
              "y":300},
            "size":{
              "width":750,
              "height":240}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5a108c2704d44b4286883e545256f71d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":90,
                  "y":300},
                "size":{
                  "width":750,
                  "height":240}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/客户经理/u10.png"}},
{
          "id":"4848e083c6644f04b789b081ffb5a813",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":110,
              "y":340},
            "size":{
              "width":710,
              "height":178}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b6b2ef53e0124fd5af39a4a18bc3aa6f",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "size":{
                  "width":202,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"56768b466feb4b69bafa3e8ba8cafa68",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "size":{
                      "width":202,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/客户经理/u13.png"}},
{
              "id":"a6f7bd81399449f5974b8daa8a06291f",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":30},
                "size":{
                  "width":202,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"8ff5cf0f5a9446069dec4fcf7d4d89de",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":30},
                    "size":{
                      "width":202,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/客户经理/u21.png"}},
{
              "id":"9573a6cedb0c4cd9a90cfbfd81b3294c",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":66},
                "size":{
                  "width":202,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"e354e6e55c3e4cb28920a2adc6e01f21",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":66},
                    "size":{
                      "width":202,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/客户经理/u21.png"}},
{
              "id":"4e081887d6b640bebbc1263e59c09d27",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":281,
                  "y":0},
                "size":{
                  "width":313,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"b360636087804fa5aa5f67ac47383152",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":281,
                      "y":0},
                    "size":{
                      "width":313,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/客户经理/u17.png"}},
{
              "id":"f14a45a86ca441cdaec3aa4a5d9828fd",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":281,
                  "y":30},
                "size":{
                  "width":313,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"c43a48f5f7214aefacaa5934a3a77762",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":281,
                      "y":30},
                    "size":{
                      "width":313,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/客户经理/u25.png"}},
{
              "id":"c813d4fc219d446a836533077f2625af",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":281,
                  "y":66},
                "size":{
                  "width":313,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"8a0b51cf7dde4ff8af5983b2075acd11",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":281,
                      "y":66},
                    "size":{
                      "width":313,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/客户经理/u25.png"}},
{
              "id":"73a77f70f62b4d33bcaa63ab8428a07e",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":594,
                  "y":0},
                "size":{
                  "width":116,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"8a95726c35d9417187273f816b72004c",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":594,
                      "y":0},
                    "size":{
                      "width":116,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/客户经理/u19.png"}},
{
              "id":"1d98fc6f34a942ae9dd10eeedf3dcba9",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":594,
                  "y":30},
                "size":{
                  "width":116,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"7835c0b703db47db94065b05f455c877",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":594,
                      "y":30},
                    "size":{
                      "width":116,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/客户经理/u27.png"}},
{
              "id":"4f549b87a26643ad85df7dd4d483a5e7",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":594,
                  "y":66},
                "size":{
                  "width":116,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"05a2740f85f8446b80aacb34207803f9",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":594,
                      "y":66},
                    "size":{
                      "width":116,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/客户经理/u27.png"}},
{
              "id":"0e7397da7f364b218ed4c52e492d333e",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":202,
                  "y":0},
                "size":{
                  "width":79,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"45d4f916d3d2402a9cd372c67d6f848b",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":202,
                      "y":0},
                    "size":{
                      "width":79,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/客户经理/u15.png"}},
{
              "id":"38093fcc689b45b6abb9d30d8bbef8a0",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":202,
                  "y":30},
                "size":{
                  "width":79,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"a00f445c42a1409591fd6cda368cb687",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":202,
                      "y":30},
                    "size":{
                      "width":79,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/客户经理/u23.png"}},
{
              "id":"fafeff32b68645a9adb7a89644fb63c4",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":202,
                  "y":66},
                "size":{
                  "width":79,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"96a582e63f3c442ca0ed0bb90d4e0718",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":202,
                      "y":66},
                    "size":{
                      "width":79,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/客户经理/u23.png"}},
{
              "id":"6c319a5f55fb4919b9d3cb023e74229a",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":102},
                "size":{
                  "width":202,
                  "height":38}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"8eb3f410c08447aa8a9bbcbadbf9eaa0",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":102},
                    "size":{
                      "width":202,
                      "height":38}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/客户经理/u37.png"}},
{
              "id":"b24ceb22348a47888412abbe36bd19c0",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":202,
                  "y":102},
                "size":{
                  "width":79,
                  "height":38}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"0accae5390ec48f7af52b22664771a49",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":202,
                      "y":102},
                    "size":{
                      "width":79,
                      "height":38}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/客户经理/u39.png"}},
{
              "id":"c6c22082e54540768fe39e99e704b7d8",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":281,
                  "y":102},
                "size":{
                  "width":313,
                  "height":38}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"17e15b9508f94945b7e5f67293d4f472",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":281,
                      "y":102},
                    "size":{
                      "width":313,
                      "height":38}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/客户经理/u41.png"}},
{
              "id":"e6c97c00db7c4af28da163774a949e5a",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":594,
                  "y":102},
                "size":{
                  "width":116,
                  "height":38}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"2f6f26971abc4f67980abf513cffb4ea",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":594,
                      "y":102},
                    "size":{
                      "width":116,
                      "height":38}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/客户经理/u43.png"}},
{
              "id":"af000e485c484687a60f1236d238c429",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":140},
                "size":{
                  "width":202,
                  "height":38}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"f98e53a2245f40cca2716edde4032a18",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":140},
                    "size":{
                      "width":202,
                      "height":38}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/客户经理/u45.png"}},
{
              "id":"5e9e3bf19b304ec6960c2efde3b90909",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":202,
                  "y":140},
                "size":{
                  "width":79,
                  "height":38}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"1936b50369e64863a9b9a5ade2e1c721",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":202,
                      "y":140},
                    "size":{
                      "width":79,
                      "height":38}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/客户经理/u47.png"}},
{
              "id":"3cb5f5a729c941769008603e1d6c5e07",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":281,
                  "y":140},
                "size":{
                  "width":313,
                  "height":38}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"7423accbf37b4823a4d146036d229fe0",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":281,
                      "y":140},
                    "size":{
                      "width":313,
                      "height":38}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/客户经理/u49.png"}},
{
              "id":"453709159da74b1da9602bde9aa5be9b",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":594,
                  "y":140},
                "size":{
                  "width":116,
                  "height":38}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"96e0d02de72b43dfaf7d155e5306f749",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":594,
                      "y":140},
                    "size":{
                      "width":116,
                      "height":38}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/客户经理/u51.png"}}]},
{
          "id":"7ca07fe0f1f04361b2fc8af5c22e4a08",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":206,
              "y":302},
            "size":{
              "width":129,
              "height":38}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1f105f314d3d4ab7860c90963c1b1434",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":206,
                  "y":302},
                "size":{
                  "width":129,
                  "height":38}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c59a3a690be449bba78dae24272805d6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "underline":true,
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":96,
              "y":518},
            "size":{
              "width":54,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"32c0cb4715b0476c838e4926e553512e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "underline":true,
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":96,
                  "y":518},
                "size":{
                  "width":54,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4a6e7e80cc5a45bab5ab7504ff452238",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":620,
              "y":513},
            "size":{
              "width":218,
              "height":27},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"47830fd35fa54cf18dbc7203847e73a7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":620,
                  "y":513},
                "size":{
                  "width":218,
                  "height":27},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/客户经理/u57.png"}},
{
          "id":"65ed63f2b7384c16b77dcfcad059685f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":360,
              "y":70},
            "size":{
              "width":59,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"11d14e956d054ebf8b2cfeb5cd518d71",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":360,
                  "y":70},
                "size":{
                  "width":59,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "65cf160423de4fabad863a4515e49900":{
      "scriptId":"u0"},
    "483c0986e97f4afeb3938df82b838360":{
      "scriptId":"u1"},
    "7d1d7d1b41514212aeb5e038f4fe828a":{
      "scriptId":"u2"},
    "3da3c65d178d42cdb7aa44421901dd0e":{
      "scriptId":"u3"},
    "e55f126f83954030a4491b936baf0911":{
      "scriptId":"u4"},
    "0266f45dad5d49f187a56a80ef75d66a":{
      "scriptId":"u5"},
    "68cb8da51a22438b94465c1f54fa5670":{
      "scriptId":"u6"},
    "f947000a083a4cc3bf060914e4825a66":{
      "scriptId":"u7"},
    "4e44e304aa7341199b5f82392a8edbcf":{
      "scriptId":"u8"},
    "f4c070c86efa4e4aa9e521fd70a46582":{
      "scriptId":"u9"},
    "23b8a92538974d008257d2548a4bd243":{
      "scriptId":"u10"},
    "7105365307c9470086a4c7df215326fd":{
      "scriptId":"u11"},
    "def8fc5f41f04009ac435089071c48e9":{
      "scriptId":"u12"},
    "5a108c2704d44b4286883e545256f71d":{
      "scriptId":"u13"},
    "4848e083c6644f04b789b081ffb5a813":{
      "scriptId":"u14"},
    "b6b2ef53e0124fd5af39a4a18bc3aa6f":{
      "scriptId":"u15"},
    "56768b466feb4b69bafa3e8ba8cafa68":{
      "scriptId":"u16"},
    "0e7397da7f364b218ed4c52e492d333e":{
      "scriptId":"u17"},
    "45d4f916d3d2402a9cd372c67d6f848b":{
      "scriptId":"u18"},
    "4e081887d6b640bebbc1263e59c09d27":{
      "scriptId":"u19"},
    "b360636087804fa5aa5f67ac47383152":{
      "scriptId":"u20"},
    "73a77f70f62b4d33bcaa63ab8428a07e":{
      "scriptId":"u21"},
    "8a95726c35d9417187273f816b72004c":{
      "scriptId":"u22"},
    "a6f7bd81399449f5974b8daa8a06291f":{
      "scriptId":"u23"},
    "8ff5cf0f5a9446069dec4fcf7d4d89de":{
      "scriptId":"u24"},
    "38093fcc689b45b6abb9d30d8bbef8a0":{
      "scriptId":"u25"},
    "a00f445c42a1409591fd6cda368cb687":{
      "scriptId":"u26"},
    "f14a45a86ca441cdaec3aa4a5d9828fd":{
      "scriptId":"u27"},
    "c43a48f5f7214aefacaa5934a3a77762":{
      "scriptId":"u28"},
    "1d98fc6f34a942ae9dd10eeedf3dcba9":{
      "scriptId":"u29"},
    "7835c0b703db47db94065b05f455c877":{
      "scriptId":"u30"},
    "9573a6cedb0c4cd9a90cfbfd81b3294c":{
      "scriptId":"u31"},
    "e354e6e55c3e4cb28920a2adc6e01f21":{
      "scriptId":"u32"},
    "fafeff32b68645a9adb7a89644fb63c4":{
      "scriptId":"u33"},
    "96a582e63f3c442ca0ed0bb90d4e0718":{
      "scriptId":"u34"},
    "c813d4fc219d446a836533077f2625af":{
      "scriptId":"u35"},
    "8a0b51cf7dde4ff8af5983b2075acd11":{
      "scriptId":"u36"},
    "4f549b87a26643ad85df7dd4d483a5e7":{
      "scriptId":"u37"},
    "05a2740f85f8446b80aacb34207803f9":{
      "scriptId":"u38"},
    "6c319a5f55fb4919b9d3cb023e74229a":{
      "scriptId":"u39"},
    "8eb3f410c08447aa8a9bbcbadbf9eaa0":{
      "scriptId":"u40"},
    "b24ceb22348a47888412abbe36bd19c0":{
      "scriptId":"u41"},
    "0accae5390ec48f7af52b22664771a49":{
      "scriptId":"u42"},
    "c6c22082e54540768fe39e99e704b7d8":{
      "scriptId":"u43"},
    "17e15b9508f94945b7e5f67293d4f472":{
      "scriptId":"u44"},
    "e6c97c00db7c4af28da163774a949e5a":{
      "scriptId":"u45"},
    "2f6f26971abc4f67980abf513cffb4ea":{
      "scriptId":"u46"},
    "af000e485c484687a60f1236d238c429":{
      "scriptId":"u47"},
    "f98e53a2245f40cca2716edde4032a18":{
      "scriptId":"u48"},
    "5e9e3bf19b304ec6960c2efde3b90909":{
      "scriptId":"u49"},
    "1936b50369e64863a9b9a5ade2e1c721":{
      "scriptId":"u50"},
    "3cb5f5a729c941769008603e1d6c5e07":{
      "scriptId":"u51"},
    "7423accbf37b4823a4d146036d229fe0":{
      "scriptId":"u52"},
    "453709159da74b1da9602bde9aa5be9b":{
      "scriptId":"u53"},
    "96e0d02de72b43dfaf7d155e5306f749":{
      "scriptId":"u54"},
    "7ca07fe0f1f04361b2fc8af5c22e4a08":{
      "scriptId":"u55"},
    "1f105f314d3d4ab7860c90963c1b1434":{
      "scriptId":"u56"},
    "c59a3a690be449bba78dae24272805d6":{
      "scriptId":"u57"},
    "32c0cb4715b0476c838e4926e553512e":{
      "scriptId":"u58"},
    "4a6e7e80cc5a45bab5ab7504ff452238":{
      "scriptId":"u59"},
    "47830fd35fa54cf18dbc7203847e73a7":{
      "scriptId":"u60"},
    "65ed63f2b7384c16b77dcfcad059685f":{
      "scriptId":"u61"},
    "11d14e956d054ebf8b2cfeb5cd518d71":{
      "scriptId":"u62"}}});