$axure.loadCurrentPage({
  "url":"发送oa通知.html",
  "generationDate":new Date(1662609051947.88),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"d007f419b6a34345816fa7c0847ceddc",
    "type":"Axure:Page",
    "name":"发送OA通知",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"b27e2d98c6ca460391d103d3f12bc00f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":117,
              "y":124},
            "size":{
              "width":253,
              "height":64}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8e4b676f60ce4e72a12b8712d50d3891",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":117,
                  "y":124},
                "size":{
                  "width":253,
                  "height":64}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "b27e2d98c6ca460391d103d3f12bc00f":{
      "scriptId":"u0"},
    "8e4b676f60ce4e72a12b8712d50d3891":{
      "scriptId":"u1"}}});