$axure.loadCurrentPage({
  "url":"查看数据-历史融资.html",
  "generationDate":new Date(1662608850474.7),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"f5cd509dd6b14f7295e40cfb33800bac",
    "type":"Axure:Page",
    "name":"查看数据-历史融资",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"838e0d9e555e40519856271b46579fe1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":-8,
              "y":94},
            "size":{
              "width":1178,
              "height":556}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"24a7e020d79d47169034d2e6a7b49e67",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":-8,
                  "y":94},
                "size":{
                  "width":1178,
                  "height":556}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/查看数据-香港公司/u0.png"}},
{
          "id":"848179f3481241fe9ae0aba57b52033c",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":27,
              "y":94},
            "size":{
              "width":97,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8f905ce22942409d88c126724657648a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":27,
                  "y":94},
                "size":{
                  "width":97,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"14e0bf6a93e64983b641bfc17385c1c0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":34,
              "y":164},
            "size":{
              "width":112,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"73f16647ffb845fc810e462dc15d7790",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":34,
                  "y":164},
                "size":{
                  "width":112,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"682c82cebf934c249d4c61c26f1cb052",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "disabled":true,
          "visible":true,
          "style":{
            "location":{
              "x":146,
              "y":164.5},
            "size":{
              "width":120,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"e50d631b6fd04791b674e1c1d3ba3830",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":34,
              "y":196},
            "size":{
              "width":126,
              "height":52}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"955d62b397594e31931cfbeb6bb10e38",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "size":{
                  "width":126,
                  "height":52}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"0de7f6d8933d4e3b9a884848d3c58d2b",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFF0000,
                      "opacity":1},
                    "size":{
                      "width":126,
                      "height":52}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/查看数据-往来客户账-损益/u8.png"}}]},
{
          "id":"5e1d9ada7fed46dba7919a1db8e62357",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":302,
              "y":136},
            "size":{
              "width":54,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e1a8aa2bec7647bc8ce8799342eb70da",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":302,
                  "y":136},
                "size":{
                  "width":54,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"638536f5876b46b3ab42f2f1620578d1",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "disabled":true,
          "visible":true,
          "style":{
            "location":{
              "x":398,
              "y":132.5},
            "size":{
              "width":120,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"59ade5a89b384360bc4589d1deb8cad0",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":146,
              "y":132.5},
            "size":{
              "width":120,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"87d4972dd0324bf081f27baa89987810",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":34,
              "y":138},
            "size":{
              "width":86,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"524adc81647b49b687c2eb277d4b90fc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":34,
                  "y":138},
                "size":{
                  "width":86,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7628074c51704a4f8e79b98af7bad292",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":260,
              "y":353.5},
            "size":{
              "width":508,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9d5ba9f3ec6445f69147aefeed62c8fd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":260,
                  "y":353.5},
                "size":{
                  "width":508,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/客户管理-业务数据展示/u559.png"}},
{
          "id":"9823c2fd75634c248a33ad460214f2de",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":1200,
              "y":383},
            "size":{
              "width":166,
              "height":48}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1b22c27bd84342048b8ce606897181ad",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1200,
                  "y":383},
                "size":{
                  "width":166,
                  "height":48}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"84a360485c704ed5b852d1f88ce61faa",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":34,
              "y":248},
            "size":{
              "width":600,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a2525e02caf8421fb2ca662d597c271b",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "size":{
                  "width":100,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"8ccd0d0565a348cea74d0dd584a92d83",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":100,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/客户管理-业务数据展示/u32.png"}},
{
              "id":"a24b57e53d90479ebf0a41146395fe88",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":20},
                "size":{
                  "width":100,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"358dddf187474cc09365de0773b13dd6",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":20},
                    "size":{
                      "width":100,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/客户管理-业务数据展示/u32.png"}},
{
              "id":"54ebb5b8be3a44f396cbc068b95c8422",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":40},
                "size":{
                  "width":100,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"f2e7470689f445e39e4632db85e24101",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":40},
                    "size":{
                      "width":100,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/客户管理-业务数据展示/u32.png"}},
{
              "id":"e90b8f2fca074d049da4fe7e88774412",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":60},
                "size":{
                  "width":100,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"989ae82b01bb4bbcbb9465950e3c4b4b",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":60},
                    "size":{
                      "width":100,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/客户管理-业务数据展示/u62.png"}},
{
              "id":"9d95cdd909164dfcb261dd4d4f5f6dd8",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":100,
                  "y":0},
                "size":{
                  "width":100,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"9d8f12b8a1194d34b267bc45fe7c2ed3",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":100,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/客户管理-业务数据展示/u32.png"}},
{
              "id":"790443c2e9494008be4bdad909e030e2",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":100,
                  "y":20},
                "size":{
                  "width":100,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"4659484f53c24df98e50cf7e384f6534",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":100,
                      "y":20},
                    "size":{
                      "width":100,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/客户管理-业务数据展示/u32.png"}},
{
              "id":"f764be0eeb574354b47096fd79cb9627",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":100,
                  "y":40},
                "size":{
                  "width":100,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"34cac91df6904d1388864f183e96d613",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":100,
                      "y":40},
                    "size":{
                      "width":100,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/客户管理-业务数据展示/u32.png"}},
{
              "id":"6eb5075154b349d28a4ec40ae0d5fa9e",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":100,
                  "y":60},
                "size":{
                  "width":100,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"7b1bda5eb138436d8a81c4a4b87fe567",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":100,
                      "y":60},
                    "size":{
                      "width":100,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/客户管理-业务数据展示/u62.png"}},
{
              "id":"4860ba02510544b7a3e3d51c2f587482",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":200,
                  "y":0},
                "size":{
                  "width":100,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"fd9453f2b6674528b209a5e3ba77635d",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":200,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/客户管理-业务数据展示/u32.png"}},
{
              "id":"46e2e7899b0e423c8870b193982abd5f",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":200,
                  "y":20},
                "size":{
                  "width":100,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"87ce3c03c8d04239b36c781218cc982b",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":200,
                      "y":20},
                    "size":{
                      "width":100,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/客户管理-业务数据展示/u32.png"}},
{
              "id":"4f11c954e65e4488802d41b22e36e411",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":200,
                  "y":40},
                "size":{
                  "width":100,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"7484279a63cc4188b31115eb1db457b5",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":200,
                      "y":40},
                    "size":{
                      "width":100,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/客户管理-业务数据展示/u32.png"}},
{
              "id":"dd9c42735ab94702949fe121cabbaf20",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":200,
                  "y":60},
                "size":{
                  "width":100,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"efa6565b4586416b9792f2dff63d39c0",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":200,
                      "y":60},
                    "size":{
                      "width":100,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/客户管理-业务数据展示/u62.png"}},
{
              "id":"e40110b2cc654fac99d90aa5151a070d",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":300,
                  "y":0},
                "size":{
                  "width":100,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"070c26c3178b41758abfb53a081ea69b",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":300,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/客户管理-业务数据展示/u32.png"}},
{
              "id":"6973b01e5c7049528356dbf2223ca7f6",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":300,
                  "y":20},
                "size":{
                  "width":100,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"92658b5b148a444db91d77a09c3c8448",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":300,
                      "y":20},
                    "size":{
                      "width":100,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/客户管理-业务数据展示/u32.png"}},
{
              "id":"bf77fbc5779b481caccd27bcbc25942e",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":300,
                  "y":40},
                "size":{
                  "width":100,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"f53c598ecb4e40a7aca5d1e453548ceb",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":300,
                      "y":40},
                    "size":{
                      "width":100,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/客户管理-业务数据展示/u32.png"}},
{
              "id":"4ed4276cbf7f44a1a4ef6c5f65ed1c73",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":300,
                  "y":60},
                "size":{
                  "width":100,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"ef004134a52b4b9a9c516c1d9e16578c",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":300,
                      "y":60},
                    "size":{
                      "width":100,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/客户管理-业务数据展示/u62.png"}},
{
              "id":"48d33ae857434979afdc34dda2a94c36",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":400,
                  "y":0},
                "size":{
                  "width":100,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"b73e113fa32845158f1f43a846282c86",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":400,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/客户管理-业务数据展示/u32.png"}},
{
              "id":"ad290f58e96f4cccacd227aae5d984da",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":400,
                  "y":20},
                "size":{
                  "width":100,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"975d7e97e44d4dc49581ec5c79ac9619",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":400,
                      "y":20},
                    "size":{
                      "width":100,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/客户管理-业务数据展示/u32.png"}},
{
              "id":"8bab77a7c7f047b9aa81e3d53f8758b2",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":400,
                  "y":40},
                "size":{
                  "width":100,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"69a2a09ef8c84315bb4d52a0f56f90b6",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":400,
                      "y":40},
                    "size":{
                      "width":100,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/客户管理-业务数据展示/u32.png"}},
{
              "id":"95a075b474c24a57b25b78b74b5184a4",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":400,
                  "y":60},
                "size":{
                  "width":100,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"e362abb1032440a1a732ac1eaf06244d",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":400,
                      "y":60},
                    "size":{
                      "width":100,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/客户管理-业务数据展示/u62.png"}},
{
              "id":"88a6ff17fcf24947bf7123604a6d28d3",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":500,
                  "y":0},
                "size":{
                  "width":100,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"c05d91bbd1db4dab82c8e7c1dfdb2fac",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":500,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/客户管理-业务数据展示/u40.png"}},
{
              "id":"f9d6ad375c6f45deb6cf690b5de649cf",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":500,
                  "y":20},
                "size":{
                  "width":100,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"32ca638eafe7444babe3c48c1229c9ad",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":500,
                      "y":20},
                    "size":{
                      "width":100,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/客户管理-业务数据展示/u40.png"}},
{
              "id":"04ce8e97d70b4dcc823debd8ab974d28",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":500,
                  "y":40},
                "size":{
                  "width":100,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"e16b9f0882dc48148cef2346e354ea2a",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":500,
                      "y":40},
                    "size":{
                      "width":100,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/客户管理-业务数据展示/u40.png"}},
{
              "id":"c1ad1a3670e24b2aa3f4e1548a7f7fad",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":500,
                  "y":60},
                "size":{
                  "width":100,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"5f8eb5e29e7c4ae58c66baf2fdc2bb7e",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":500,
                      "y":60},
                    "size":{
                      "width":100,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/客户管理-业务数据展示/u70.png"}}]}]}},
  "masters":{
},
  "objectPaths":{
    "838e0d9e555e40519856271b46579fe1":{
      "scriptId":"u0"},
    "24a7e020d79d47169034d2e6a7b49e67":{
      "scriptId":"u1"},
    "848179f3481241fe9ae0aba57b52033c":{
      "scriptId":"u2"},
    "8f905ce22942409d88c126724657648a":{
      "scriptId":"u3"},
    "14e0bf6a93e64983b641bfc17385c1c0":{
      "scriptId":"u4"},
    "73f16647ffb845fc810e462dc15d7790":{
      "scriptId":"u5"},
    "682c82cebf934c249d4c61c26f1cb052":{
      "scriptId":"u6"},
    "e50d631b6fd04791b674e1c1d3ba3830":{
      "scriptId":"u7"},
    "955d62b397594e31931cfbeb6bb10e38":{
      "scriptId":"u8"},
    "0de7f6d8933d4e3b9a884848d3c58d2b":{
      "scriptId":"u9"},
    "5e1d9ada7fed46dba7919a1db8e62357":{
      "scriptId":"u10"},
    "e1a8aa2bec7647bc8ce8799342eb70da":{
      "scriptId":"u11"},
    "638536f5876b46b3ab42f2f1620578d1":{
      "scriptId":"u12"},
    "59ade5a89b384360bc4589d1deb8cad0":{
      "scriptId":"u13"},
    "87d4972dd0324bf081f27baa89987810":{
      "scriptId":"u14"},
    "524adc81647b49b687c2eb277d4b90fc":{
      "scriptId":"u15"},
    "7628074c51704a4f8e79b98af7bad292":{
      "scriptId":"u16"},
    "9d5ba9f3ec6445f69147aefeed62c8fd":{
      "scriptId":"u17"},
    "9823c2fd75634c248a33ad460214f2de":{
      "scriptId":"u18"},
    "1b22c27bd84342048b8ce606897181ad":{
      "scriptId":"u19"},
    "84a360485c704ed5b852d1f88ce61faa":{
      "scriptId":"u20"},
    "a2525e02caf8421fb2ca662d597c271b":{
      "scriptId":"u21"},
    "8ccd0d0565a348cea74d0dd584a92d83":{
      "scriptId":"u22"},
    "9d95cdd909164dfcb261dd4d4f5f6dd8":{
      "scriptId":"u23"},
    "9d8f12b8a1194d34b267bc45fe7c2ed3":{
      "scriptId":"u24"},
    "4860ba02510544b7a3e3d51c2f587482":{
      "scriptId":"u25"},
    "fd9453f2b6674528b209a5e3ba77635d":{
      "scriptId":"u26"},
    "e40110b2cc654fac99d90aa5151a070d":{
      "scriptId":"u27"},
    "070c26c3178b41758abfb53a081ea69b":{
      "scriptId":"u28"},
    "48d33ae857434979afdc34dda2a94c36":{
      "scriptId":"u29"},
    "b73e113fa32845158f1f43a846282c86":{
      "scriptId":"u30"},
    "88a6ff17fcf24947bf7123604a6d28d3":{
      "scriptId":"u31"},
    "c05d91bbd1db4dab82c8e7c1dfdb2fac":{
      "scriptId":"u32"},
    "a24b57e53d90479ebf0a41146395fe88":{
      "scriptId":"u33"},
    "358dddf187474cc09365de0773b13dd6":{
      "scriptId":"u34"},
    "790443c2e9494008be4bdad909e030e2":{
      "scriptId":"u35"},
    "4659484f53c24df98e50cf7e384f6534":{
      "scriptId":"u36"},
    "46e2e7899b0e423c8870b193982abd5f":{
      "scriptId":"u37"},
    "87ce3c03c8d04239b36c781218cc982b":{
      "scriptId":"u38"},
    "6973b01e5c7049528356dbf2223ca7f6":{
      "scriptId":"u39"},
    "92658b5b148a444db91d77a09c3c8448":{
      "scriptId":"u40"},
    "ad290f58e96f4cccacd227aae5d984da":{
      "scriptId":"u41"},
    "975d7e97e44d4dc49581ec5c79ac9619":{
      "scriptId":"u42"},
    "f9d6ad375c6f45deb6cf690b5de649cf":{
      "scriptId":"u43"},
    "32ca638eafe7444babe3c48c1229c9ad":{
      "scriptId":"u44"},
    "54ebb5b8be3a44f396cbc068b95c8422":{
      "scriptId":"u45"},
    "f2e7470689f445e39e4632db85e24101":{
      "scriptId":"u46"},
    "f764be0eeb574354b47096fd79cb9627":{
      "scriptId":"u47"},
    "34cac91df6904d1388864f183e96d613":{
      "scriptId":"u48"},
    "4f11c954e65e4488802d41b22e36e411":{
      "scriptId":"u49"},
    "7484279a63cc4188b31115eb1db457b5":{
      "scriptId":"u50"},
    "bf77fbc5779b481caccd27bcbc25942e":{
      "scriptId":"u51"},
    "f53c598ecb4e40a7aca5d1e453548ceb":{
      "scriptId":"u52"},
    "8bab77a7c7f047b9aa81e3d53f8758b2":{
      "scriptId":"u53"},
    "69a2a09ef8c84315bb4d52a0f56f90b6":{
      "scriptId":"u54"},
    "04ce8e97d70b4dcc823debd8ab974d28":{
      "scriptId":"u55"},
    "e16b9f0882dc48148cef2346e354ea2a":{
      "scriptId":"u56"},
    "e90b8f2fca074d049da4fe7e88774412":{
      "scriptId":"u57"},
    "989ae82b01bb4bbcbb9465950e3c4b4b":{
      "scriptId":"u58"},
    "6eb5075154b349d28a4ec40ae0d5fa9e":{
      "scriptId":"u59"},
    "7b1bda5eb138436d8a81c4a4b87fe567":{
      "scriptId":"u60"},
    "dd9c42735ab94702949fe121cabbaf20":{
      "scriptId":"u61"},
    "efa6565b4586416b9792f2dff63d39c0":{
      "scriptId":"u62"},
    "4ed4276cbf7f44a1a4ef6c5f65ed1c73":{
      "scriptId":"u63"},
    "ef004134a52b4b9a9c516c1d9e16578c":{
      "scriptId":"u64"},
    "95a075b474c24a57b25b78b74b5184a4":{
      "scriptId":"u65"},
    "e362abb1032440a1a732ac1eaf06244d":{
      "scriptId":"u66"},
    "c1ad1a3670e24b2aa3f4e1548a7f7fad":{
      "scriptId":"u67"},
    "5f8eb5e29e7c4ae58c66baf2fdc2bb7e":{
      "scriptId":"u68"}}});