$axure.loadCurrentPage({
  "url":"舆情详情查看.html",
  "generationDate":new Date(1662609046706.64),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"5b104ad64bec4eba895b79e7b61764e8",
    "type":"Axure:Page",
    "name":"舆情详情查看",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"325af05ffd6049fc9ec9050c9478d990",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":100,
              "y":175.999984741211},
            "size":{
              "width":520,
              "height":344}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5406cf2c76c547c8889eb84a8787e8a3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":100,
                  "y":175.999984741211},
                "size":{
                  "width":520,
                  "height":344}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fcc9dba091834075bd8a6c876dbe01d4",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":136,
              "y":62},
            "size":{
              "width":154,
              "height":38}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"87b3ba08e6654a3db2eab3a10550e6b2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":136,
                  "y":62},
                "size":{
                  "width":154,
                  "height":38}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7ee863f88fb54525bed6dae767e60588",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":417,
              "y":120},
            "size":{
              "width":97,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"77643ff1e4104d3cad9ba3f3f95cbc75",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":417,
                  "y":120},
                "size":{
                  "width":97,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2dcf8823a40e43f4b2f38eb3f838fb96",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":580,
              "y":54},
            "size":{
              "width":200,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"313cb5ef4d71415d8312301190d34b69",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":580,
                  "y":54},
                "size":{
                  "width":200,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "325af05ffd6049fc9ec9050c9478d990":{
      "scriptId":"u0"},
    "5406cf2c76c547c8889eb84a8787e8a3":{
      "scriptId":"u1"},
    "fcc9dba091834075bd8a6c876dbe01d4":{
      "scriptId":"u2"},
    "87b3ba08e6654a3db2eab3a10550e6b2":{
      "scriptId":"u3"},
    "7ee863f88fb54525bed6dae767e60588":{
      "scriptId":"u4"},
    "77643ff1e4104d3cad9ba3f3f95cbc75":{
      "scriptId":"u5"},
    "2dcf8823a40e43f4b2f38eb3f838fb96":{
      "scriptId":"u6"},
    "313cb5ef4d71415d8312301190d34b69":{
      "scriptId":"u7"}}});