$axure.loadCurrentPage({
  "url":"数据处理流程示意.html",
  "generationDate":new Date(1662609047443.6),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"287a23f2801f461a93a561bd91536008",
    "type":"Axure:Page",
    "name":"数据处理流程示意",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"ced70b061b2045e78853ed5ccc14399e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":434,
              "y":10},
            "size":{
              "width":886,
              "height":1270}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"60d6c3078c9847cf92c08776710cded0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":434,
                  "y":10},
                "size":{
                  "width":886,
                  "height":1270}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/数据处理流程示意/u0.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "ced70b061b2045e78853ed5ccc14399e":{
      "scriptId":"u0"},
    "60d6c3078c9847cf92c08776710cded0":{
      "scriptId":"u1"}}});