$axure.loadCurrentPage({
  "url":"金融产品管理.html",
  "generationDate":new Date(1663837672857.59),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"a127f9e158774207aa6aff15fe25a915",
    "type":"Axure:Page",
    "name":"金融产品管理",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"03f827ab84af40dc8a541b5def0d3102",
          "label":"",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":false,
          "selected":true,
          "style":{
            "location":{
              "x":40,
              "y":363},
            "size":{
              "width":630,
              "height":237},
            "visible":false},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"6844208d831d488a8fea1b8bbb7ee221",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[]}]},
{
          "id":"409a9458647e498cad434197c1447305",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":51,
              "y":374},
            "size":{
              "width":608,
              "height":206}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"960825daee234aa8af7b398de15d0e64",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":51,
                  "y":374},
                "size":{
                  "width":608,
                  "height":206}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/金融产品管理/u1.png"}},
{
          "id":"0651bd8a300042d38aac429308eb0813",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":50,
              "y":32},
            "size":{
              "width":250,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4bb9f8bf396146b7b66fb14802e4c4c7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":50,
                  "y":32},
                "size":{
                  "width":250,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7bb5514923734bf7ac3fad9921ef5542",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":48,
              "y":70},
            "size":{
              "width":852,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/金融产品管理/u5_line.png"}},
{
          "id":"1c6c986da48a4abab79039b45f08ef7e",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":730,
              "y":90},
            "size":{
              "width":60,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"2d1d1b0ba7384e61b4d59bb564aa4cef",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":880,
              "y":90},
            "size":{
              "width":60,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"764ee102b4104c10b85745d10d312937",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":48,
              "y":150},
            "size":{
              "width":819,
              "height":96}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b5135ccf027a47c089827d6f3a1a0015",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "size":{
                  "width":82,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"1fbbd90cc5a54088b215f6979400cbd4",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":82,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/余额_收入详情/u15.png"}},
{
              "id":"a4024332b9bd47248c4f9e38de61f73c",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":36},
                "size":{
                  "width":82,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"7f7b4df9522547f991b0eaf398c207d1",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":36},
                    "size":{
                      "width":82,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/金融产品管理/u29.png"}},
{
              "id":"6eeac3850be74af5bd42ace98709d32b",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":56},
                "size":{
                  "width":82,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"0e923acf6e4e49458211ce4054782cc3",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":56},
                    "size":{
                      "width":82,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/金融产品管理/u29.png"}},
{
              "id":"978c3a8a54d44fbdbcca480cefb4c4e2",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":76},
                "size":{
                  "width":82,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"7ddbf61c9e2b44ccbfc92cc48cfefc9b",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":76},
                    "size":{
                      "width":82,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/金融产品管理/u69.png"}},
{
              "id":"58bae2b351264fbe80b960f2f5d3a5d9",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":82,
                  "y":0},
                "size":{
                  "width":78,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"ae43f79d5186477abb085a92b49d5225",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":82,
                      "y":0},
                    "size":{
                      "width":78,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/客户管理-业务数据展示/u91.png"}},
{
              "id":"96e890df29df4c84b62c15ce260153f7",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":82,
                  "y":36},
                "size":{
                  "width":78,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"dde045c7f1c94b46aa947797204eb7dc",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":82,
                      "y":36},
                    "size":{
                      "width":78,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/客户管理-业务数据展示/u73.png"}},
{
              "id":"48fd2b48789943afb36e186954c7910b",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":82,
                  "y":56},
                "size":{
                  "width":78,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"d8210f5f179b48729ca57dd7a4d53ca1",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":82,
                      "y":56},
                    "size":{
                      "width":78,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/客户管理-业务数据展示/u73.png"}},
{
              "id":"e628bf22227645c1b91c7486e976761b",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":82,
                  "y":76},
                "size":{
                  "width":78,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"abf5eef607d146409b4a608460109fcb",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":82,
                      "y":76},
                    "size":{
                      "width":78,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/客户管理-业务数据展示/u473.png"}},
{
              "id":"260ee175c7c841fd9e5185542ecf7a05",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":160,
                  "y":0},
                "size":{
                  "width":71,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"086731303cb94d2ea98b24d6f6f44697",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":160,
                      "y":0},
                    "size":{
                      "width":71,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/金融产品管理/u13.png"}},
{
              "id":"8ebc026f6e694973984885c03b94a02c",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":160,
                  "y":36},
                "size":{
                  "width":71,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"df3110b4e10e4536b02ec2e35a562b33",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":160,
                      "y":36},
                    "size":{
                      "width":71,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/金融产品管理/u33.png"}},
{
              "id":"3c771e181a79454594c501454b8f49bc",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":160,
                  "y":56},
                "size":{
                  "width":71,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"98fedfaf152f438ea2f41b98a7aa8486",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":160,
                      "y":56},
                    "size":{
                      "width":71,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/金融产品管理/u33.png"}},
{
              "id":"ccc9af254f834e7bb366fb6a1587ca6b",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":160,
                  "y":76},
                "size":{
                  "width":71,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"ea8f0b9ab215410db5bb4b94b548a81e",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":160,
                      "y":76},
                    "size":{
                      "width":71,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/金融产品管理/u73.png"}},
{
              "id":"e18420e37f5b4ad9b3885a0151e03238",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":231,
                  "y":0},
                "size":{
                  "width":113,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"ed405d9696be43c9b023ec2043b95e0d",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":231,
                      "y":0},
                    "size":{
                      "width":113,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/金融产品管理/u15.png"}},
{
              "id":"4ea1f27299c6474ebe5a2af11023ec7b",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":231,
                  "y":36},
                "size":{
                  "width":113,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"6b855497f9634c2f95896c89be17792d",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":231,
                      "y":36},
                    "size":{
                      "width":113,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/金融产品管理/u35.png"}},
{
              "id":"c09a6f6ea8c745c4bb67d389bd5d3274",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":231,
                  "y":56},
                "size":{
                  "width":113,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"7949fb66e5cd4a7eb73a9dd825d668cb",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":231,
                      "y":56},
                    "size":{
                      "width":113,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/金融产品管理/u35.png"}},
{
              "id":"115983d77a42465484cb47975b60765b",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":231,
                  "y":76},
                "size":{
                  "width":113,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"4c4b9bc35bd747fb9e8fcdcc6d6051e2",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":231,
                      "y":76},
                    "size":{
                      "width":113,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/金融产品管理/u75.png"}},
{
              "id":"142ef0867a0f4ba7b8c7ade95ac64375",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":590,
                  "y":0},
                "size":{
                  "width":51,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"c3345bdd57854054b7e8df5e77d17db5",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":590,
                      "y":0},
                    "size":{
                      "width":51,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/金融产品管理/u23.png"}},
{
              "id":"f91d67b0154a4d638e78b652a41dd655",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":590,
                  "y":36},
                "size":{
                  "width":51,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"4f29c63fa9e84b9bb5081f29313dae5c",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":590,
                      "y":36},
                    "size":{
                      "width":51,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/金融产品管理/u43.png"}},
{
              "id":"3ee67ee02bc74656b64d51654ca8884b",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":590,
                  "y":56},
                "size":{
                  "width":51,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"3a0c573022404d0d8d939845a7439638",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":590,
                      "y":56},
                    "size":{
                      "width":51,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/金融产品管理/u43.png"}},
{
              "id":"3a281df8cf2245f0b772441fe1298320",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":590,
                  "y":76},
                "size":{
                  "width":51,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"22e0d4094f9f4c0fbf74b3f09edfbdb0",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":590,
                      "y":76},
                    "size":{
                      "width":51,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/金融产品管理/u83.png"}},
{
              "id":"7e839768e5d041709889ed5c2577cc59",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":641,
                  "y":0},
                "size":{
                  "width":46,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"12e434d394ae4828b1f5cc7988481026",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":641,
                      "y":0},
                    "size":{
                      "width":46,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/余额_收入详情/u7.png"}},
{
              "id":"37614c2fcc704ec48634351ab3db5729",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":641,
                  "y":36},
                "size":{
                  "width":46,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"2e65be4cc39e4964adbc94ec8bd747fd",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":641,
                      "y":36},
                    "size":{
                      "width":46,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/金融产品管理/u45.png"}},
{
              "id":"099effa2cc5348ce85d5f465608f9d11",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":641,
                  "y":56},
                "size":{
                  "width":46,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"b204b31bd4ec40909d3da5e6358b2ade",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":641,
                      "y":56},
                    "size":{
                      "width":46,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/金融产品管理/u45.png"}},
{
              "id":"35ed3da7ca7e43cd8bd741909cca9616",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":641,
                  "y":76},
                "size":{
                  "width":46,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"6f4748cfd23c4a8d87f15d4db59cf86c",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":641,
                      "y":76},
                    "size":{
                      "width":46,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/金融产品管理/u85.png"}},
{
              "id":"eaf62c42c8c041509fb01c649232aaf2",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":687,
                  "y":0},
                "size":{
                  "width":132,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"50bf6e3f9f904f33b705b9d37062b018",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":687,
                      "y":0},
                    "size":{
                      "width":132,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/金融产品管理/u27.png"}},
{
              "id":"20773267381140e68b30679349bb2090",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000099,
                  "opacity":1},
                "location":{
                  "x":687,
                  "y":36},
                "size":{
                  "width":132,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"0de98a55a97f4ac9bf22f89c1c5b7dbd",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF000099,
                      "opacity":1},
                    "location":{
                      "x":687,
                      "y":36},
                    "size":{
                      "width":132,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/金融产品管理/u47.png"}},
{
              "id":"81cf65cb04954b638a6bcb88724204e1",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":687,
                  "y":56},
                "size":{
                  "width":132,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"5a62f36419414cbe8e6b3c817d3cb74b",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":687,
                      "y":56},
                    "size":{
                      "width":132,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/金融产品管理/u47.png"}},
{
              "id":"f7df7ee4553a4526a70ea01bc7407799",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":687,
                  "y":76},
                "size":{
                  "width":132,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"77a149ee63fd492b85000a8d152a7df3",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":687,
                      "y":76},
                    "size":{
                      "width":132,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/金融产品管理/u87.png"}},
{
              "id":"b872bf8771d54c39bf362d5f72397038",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":426,
                  "y":0},
                "size":{
                  "width":82,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"5598340bf3974eebb504c9de90ccf318",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":426,
                      "y":0},
                    "size":{
                      "width":82,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/余额_收入详情/u15.png"}},
{
              "id":"57ca10218b584925b57efb664cf524a9",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":426,
                  "y":36},
                "size":{
                  "width":82,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"01dd11f38fc7439f944b09262a7b0a57",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":426,
                      "y":36},
                    "size":{
                      "width":82,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/金融产品管理/u29.png"}},
{
              "id":"32f7aa23b9a04df29538088078d784a3",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":426,
                  "y":56},
                "size":{
                  "width":82,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"85f6a23ebd7a43e79b8bfdcc65073ec5",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":426,
                      "y":56},
                    "size":{
                      "width":82,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/金融产品管理/u29.png"}},
{
              "id":"22424aa43b084b07a973445179564042",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":426,
                  "y":76},
                "size":{
                  "width":82,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"5c9f894445b24e019c727a67d044aaf7",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":426,
                      "y":76},
                    "size":{
                      "width":82,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/金融产品管理/u69.png"}},
{
              "id":"be4abda19aad46e78529f0875b0cd699",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":508,
                  "y":0},
                "size":{
                  "width":82,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"fbb66e8f75594697bf87a802de10ff4f",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":508,
                      "y":0},
                    "size":{
                      "width":82,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/余额_收入详情/u15.png"}},
{
              "id":"aa70672c2bb24ced80e1f3d7f2c98dd0",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":508,
                  "y":36},
                "size":{
                  "width":82,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"6592254612c44182ac689d07e16e3d12",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":508,
                      "y":36},
                    "size":{
                      "width":82,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/金融产品管理/u29.png"}},
{
              "id":"315276f65e0b4212b03da1b65760a49e",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":508,
                  "y":56},
                "size":{
                  "width":82,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"ff0e34af126f4b04af6f1fe53ef8cb5f",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":508,
                      "y":56},
                    "size":{
                      "width":82,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/金融产品管理/u29.png"}},
{
              "id":"55a8faf3478e456682a6e6b70baa64fe",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":508,
                  "y":76},
                "size":{
                  "width":82,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"74e26c2b74014f50b1d53a2002f689f4",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":508,
                      "y":76},
                    "size":{
                      "width":82,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/金融产品管理/u69.png"}},
{
              "id":"04eaa9e647524620a96d1aac4dbe706c",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":344,
                  "y":0},
                "size":{
                  "width":82,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"dcae10aaa99446b1b6e9ed710a3e3a37",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":344,
                      "y":0},
                    "size":{
                      "width":82,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/余额_收入详情/u15.png"}},
{
              "id":"2d1a07d020884bd1802811fe9d0f1bfc",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":344,
                  "y":36},
                "size":{
                  "width":82,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"6cb7cca3dacf4eebbcd84a80ea695778",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":344,
                      "y":36},
                    "size":{
                      "width":82,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/金融产品管理/u29.png"}},
{
              "id":"65f65d6b8a6242f29bb428c03a5c6dea",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":344,
                  "y":56},
                "size":{
                  "width":82,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"cca2c76e716c461e80e3900e0455ba9c",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":344,
                      "y":56},
                    "size":{
                      "width":82,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/金融产品管理/u29.png"}},
{
              "id":"d7fce31c6efe4a71b4428410d374c141",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":344,
                  "y":76},
                "size":{
                  "width":82,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"6c676f1d1e1342d890d19aaba71f1738",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":344,
                      "y":76},
                    "size":{
                      "width":82,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/金融产品管理/u69.png"}}]},
{
          "id":"a8aa1723f3b242158d0f748101787a78",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":444,
              "y":263},
            "size":{
              "width":508,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8df78616ff844d6e919846ef20ea4fed",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":444,
                  "y":263},
                "size":{
                  "width":508,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/客户管理-业务数据展示/u559.png"}},
{
          "id":"fef5ba7cd2404fda8f2ef97dbe55a5e6",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":69,
              "y":374},
            "size":{
              "width":206,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8db59e9005164d96808628e943c0efe0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":69,
                  "y":374},
                "size":{
                  "width":206,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"51bd028d31ca435ea2304581a938faa1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":98,
              "y":458},
            "size":{
              "width":54,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"853a720a522245b1ad6c2680727b461d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":98,
                  "y":458},
                "size":{
                  "width":54,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e8fb7dfc507c45d4975fe925524feb63",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":104,
              "y":425},
            "size":{
              "width":54,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f224a30f24ea4243bccba7ec995eceb3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":104,
                  "y":425},
                "size":{
                  "width":54,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"92da21720a494f688d10be077154a327",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":168,
              "y":422},
            "size":{
              "width":122,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"63b8d94496274429b26bba9e7f2ee57a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":331,
              "y":460},
            "size":{
              "width":112,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3dbda1bc04a04bb5b7070b8331973406",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":331,
                  "y":460},
                "size":{
                  "width":112,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"56fc86d32ccc464fa7d0284a5b6cde1e",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":800,
              "y":90},
            "size":{
              "width":60,
              "height":25}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 (动态面板)",
                      "objectsToFades":[{
                          "objectPath":["03f827ab84af40dc8a541b5def0d3102"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true},
{
          "id":"be907d098c2b4159929bf9338176fda5",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":370,
              "y":535},
            "size":{
              "width":60,
              "height":25}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"隐藏 (动态面板) 向下滑动 500 ms",
                      "objectsToFades":[{
                          "objectPath":["03f827ab84af40dc8a541b5def0d3102"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "easing":"slideDown",
                              "duration":500,
                              "showType":"none"}}}]}]}]}},
          "tabbable":true},
{
          "id":"7ed7fa6ff25d45fe9b51a3ada2fc01df",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":444,
              "y":535},
            "size":{
              "width":60,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"7e78be9c1530448c9abb3a3520b97b7b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":717,
              "y":394},
            "size":{
              "width":328,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"69147be70ae548eb8a436d7fa08903cc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":717,
                  "y":394},
                "size":{
                  "width":328,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6211a7f56c4d4ad78390a178c435a9b0",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":339,
              "y":93},
            "size":{
              "width":120,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"aaa6652102bb4a808462100f73e283da",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":186,
              "y":92},
            "size":{
              "width":120,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"5d39747913cc43f899369f8ff97859a7",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":48,
              "y":92},
            "size":{
              "width":105,
              "height":25}},
          "adaptiveStyles":{
},
          "placeholderText":"请输入产品名称"},
{
          "id":"8de1eb5f62ca4dbba5477bd75c940dc0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":331,
              "y":419},
            "size":{
              "width":60,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bb0c3c03e01e432aad25a189bce9c01b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":331,
                  "y":419},
                "size":{
                  "width":60,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f3df973f8e7f473d92261052dea56e44",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":395,
              "y":416},
            "size":{
              "width":122,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"4f3391cd216647bab26936f9a1aaba34",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":162,
              "y":460},
            "size":{
              "width":128,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"b094a4e7ac1f4585b76ce25aa20f54dc",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":395,
              "y":457},
            "size":{
              "width":122,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"dd86fc6472cd4bb48ec14a5e00eedf62",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":98,
              "y":495},
            "size":{
              "width":28,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b8db44d1463f411e919b80c02d110f4b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":98,
                  "y":495},
                "size":{
                  "width":28,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"50fe4c8557d94b1e9239ff8dfc739f12",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":162,
              "y":492},
            "size":{
              "width":358,
              "height":38}},
          "adaptiveStyles":{
}}]}},
  "masters":{
},
  "objectPaths":{
    "03f827ab84af40dc8a541b5def0d3102":{
      "scriptId":"u0"},
    "409a9458647e498cad434197c1447305":{
      "scriptId":"u1"},
    "960825daee234aa8af7b398de15d0e64":{
      "scriptId":"u2"},
    "0651bd8a300042d38aac429308eb0813":{
      "scriptId":"u3"},
    "4bb9f8bf396146b7b66fb14802e4c4c7":{
      "scriptId":"u4"},
    "7bb5514923734bf7ac3fad9921ef5542":{
      "scriptId":"u5"},
    "1c6c986da48a4abab79039b45f08ef7e":{
      "scriptId":"u6"},
    "2d1d1b0ba7384e61b4d59bb564aa4cef":{
      "scriptId":"u7"},
    "764ee102b4104c10b85745d10d312937":{
      "scriptId":"u8"},
    "b5135ccf027a47c089827d6f3a1a0015":{
      "scriptId":"u9"},
    "1fbbd90cc5a54088b215f6979400cbd4":{
      "scriptId":"u10"},
    "58bae2b351264fbe80b960f2f5d3a5d9":{
      "scriptId":"u11"},
    "ae43f79d5186477abb085a92b49d5225":{
      "scriptId":"u12"},
    "260ee175c7c841fd9e5185542ecf7a05":{
      "scriptId":"u13"},
    "086731303cb94d2ea98b24d6f6f44697":{
      "scriptId":"u14"},
    "e18420e37f5b4ad9b3885a0151e03238":{
      "scriptId":"u15"},
    "ed405d9696be43c9b023ec2043b95e0d":{
      "scriptId":"u16"},
    "04eaa9e647524620a96d1aac4dbe706c":{
      "scriptId":"u17"},
    "dcae10aaa99446b1b6e9ed710a3e3a37":{
      "scriptId":"u18"},
    "b872bf8771d54c39bf362d5f72397038":{
      "scriptId":"u19"},
    "5598340bf3974eebb504c9de90ccf318":{
      "scriptId":"u20"},
    "be4abda19aad46e78529f0875b0cd699":{
      "scriptId":"u21"},
    "fbb66e8f75594697bf87a802de10ff4f":{
      "scriptId":"u22"},
    "142ef0867a0f4ba7b8c7ade95ac64375":{
      "scriptId":"u23"},
    "c3345bdd57854054b7e8df5e77d17db5":{
      "scriptId":"u24"},
    "7e839768e5d041709889ed5c2577cc59":{
      "scriptId":"u25"},
    "12e434d394ae4828b1f5cc7988481026":{
      "scriptId":"u26"},
    "eaf62c42c8c041509fb01c649232aaf2":{
      "scriptId":"u27"},
    "50bf6e3f9f904f33b705b9d37062b018":{
      "scriptId":"u28"},
    "a4024332b9bd47248c4f9e38de61f73c":{
      "scriptId":"u29"},
    "7f7b4df9522547f991b0eaf398c207d1":{
      "scriptId":"u30"},
    "96e890df29df4c84b62c15ce260153f7":{
      "scriptId":"u31"},
    "dde045c7f1c94b46aa947797204eb7dc":{
      "scriptId":"u32"},
    "8ebc026f6e694973984885c03b94a02c":{
      "scriptId":"u33"},
    "df3110b4e10e4536b02ec2e35a562b33":{
      "scriptId":"u34"},
    "4ea1f27299c6474ebe5a2af11023ec7b":{
      "scriptId":"u35"},
    "6b855497f9634c2f95896c89be17792d":{
      "scriptId":"u36"},
    "2d1a07d020884bd1802811fe9d0f1bfc":{
      "scriptId":"u37"},
    "6cb7cca3dacf4eebbcd84a80ea695778":{
      "scriptId":"u38"},
    "57ca10218b584925b57efb664cf524a9":{
      "scriptId":"u39"},
    "01dd11f38fc7439f944b09262a7b0a57":{
      "scriptId":"u40"},
    "aa70672c2bb24ced80e1f3d7f2c98dd0":{
      "scriptId":"u41"},
    "6592254612c44182ac689d07e16e3d12":{
      "scriptId":"u42"},
    "f91d67b0154a4d638e78b652a41dd655":{
      "scriptId":"u43"},
    "4f29c63fa9e84b9bb5081f29313dae5c":{
      "scriptId":"u44"},
    "37614c2fcc704ec48634351ab3db5729":{
      "scriptId":"u45"},
    "2e65be4cc39e4964adbc94ec8bd747fd":{
      "scriptId":"u46"},
    "20773267381140e68b30679349bb2090":{
      "scriptId":"u47"},
    "0de98a55a97f4ac9bf22f89c1c5b7dbd":{
      "scriptId":"u48"},
    "6eeac3850be74af5bd42ace98709d32b":{
      "scriptId":"u49"},
    "0e923acf6e4e49458211ce4054782cc3":{
      "scriptId":"u50"},
    "48fd2b48789943afb36e186954c7910b":{
      "scriptId":"u51"},
    "d8210f5f179b48729ca57dd7a4d53ca1":{
      "scriptId":"u52"},
    "3c771e181a79454594c501454b8f49bc":{
      "scriptId":"u53"},
    "98fedfaf152f438ea2f41b98a7aa8486":{
      "scriptId":"u54"},
    "c09a6f6ea8c745c4bb67d389bd5d3274":{
      "scriptId":"u55"},
    "7949fb66e5cd4a7eb73a9dd825d668cb":{
      "scriptId":"u56"},
    "65f65d6b8a6242f29bb428c03a5c6dea":{
      "scriptId":"u57"},
    "cca2c76e716c461e80e3900e0455ba9c":{
      "scriptId":"u58"},
    "32f7aa23b9a04df29538088078d784a3":{
      "scriptId":"u59"},
    "85f6a23ebd7a43e79b8bfdcc65073ec5":{
      "scriptId":"u60"},
    "315276f65e0b4212b03da1b65760a49e":{
      "scriptId":"u61"},
    "ff0e34af126f4b04af6f1fe53ef8cb5f":{
      "scriptId":"u62"},
    "3ee67ee02bc74656b64d51654ca8884b":{
      "scriptId":"u63"},
    "3a0c573022404d0d8d939845a7439638":{
      "scriptId":"u64"},
    "099effa2cc5348ce85d5f465608f9d11":{
      "scriptId":"u65"},
    "b204b31bd4ec40909d3da5e6358b2ade":{
      "scriptId":"u66"},
    "81cf65cb04954b638a6bcb88724204e1":{
      "scriptId":"u67"},
    "5a62f36419414cbe8e6b3c817d3cb74b":{
      "scriptId":"u68"},
    "978c3a8a54d44fbdbcca480cefb4c4e2":{
      "scriptId":"u69"},
    "7ddbf61c9e2b44ccbfc92cc48cfefc9b":{
      "scriptId":"u70"},
    "e628bf22227645c1b91c7486e976761b":{
      "scriptId":"u71"},
    "abf5eef607d146409b4a608460109fcb":{
      "scriptId":"u72"},
    "ccc9af254f834e7bb366fb6a1587ca6b":{
      "scriptId":"u73"},
    "ea8f0b9ab215410db5bb4b94b548a81e":{
      "scriptId":"u74"},
    "115983d77a42465484cb47975b60765b":{
      "scriptId":"u75"},
    "4c4b9bc35bd747fb9e8fcdcc6d6051e2":{
      "scriptId":"u76"},
    "d7fce31c6efe4a71b4428410d374c141":{
      "scriptId":"u77"},
    "6c676f1d1e1342d890d19aaba71f1738":{
      "scriptId":"u78"},
    "22424aa43b084b07a973445179564042":{
      "scriptId":"u79"},
    "5c9f894445b24e019c727a67d044aaf7":{
      "scriptId":"u80"},
    "55a8faf3478e456682a6e6b70baa64fe":{
      "scriptId":"u81"},
    "74e26c2b74014f50b1d53a2002f689f4":{
      "scriptId":"u82"},
    "3a281df8cf2245f0b772441fe1298320":{
      "scriptId":"u83"},
    "22e0d4094f9f4c0fbf74b3f09edfbdb0":{
      "scriptId":"u84"},
    "35ed3da7ca7e43cd8bd741909cca9616":{
      "scriptId":"u85"},
    "6f4748cfd23c4a8d87f15d4db59cf86c":{
      "scriptId":"u86"},
    "f7df7ee4553a4526a70ea01bc7407799":{
      "scriptId":"u87"},
    "77a149ee63fd492b85000a8d152a7df3":{
      "scriptId":"u88"},
    "a8aa1723f3b242158d0f748101787a78":{
      "scriptId":"u89"},
    "8df78616ff844d6e919846ef20ea4fed":{
      "scriptId":"u90"},
    "fef5ba7cd2404fda8f2ef97dbe55a5e6":{
      "scriptId":"u91"},
    "8db59e9005164d96808628e943c0efe0":{
      "scriptId":"u92"},
    "51bd028d31ca435ea2304581a938faa1":{
      "scriptId":"u93"},
    "853a720a522245b1ad6c2680727b461d":{
      "scriptId":"u94"},
    "e8fb7dfc507c45d4975fe925524feb63":{
      "scriptId":"u95"},
    "f224a30f24ea4243bccba7ec995eceb3":{
      "scriptId":"u96"},
    "92da21720a494f688d10be077154a327":{
      "scriptId":"u97"},
    "63b8d94496274429b26bba9e7f2ee57a":{
      "scriptId":"u98"},
    "3dbda1bc04a04bb5b7070b8331973406":{
      "scriptId":"u99"},
    "56fc86d32ccc464fa7d0284a5b6cde1e":{
      "scriptId":"u100"},
    "be907d098c2b4159929bf9338176fda5":{
      "scriptId":"u101"},
    "7ed7fa6ff25d45fe9b51a3ada2fc01df":{
      "scriptId":"u102"},
    "7e78be9c1530448c9abb3a3520b97b7b":{
      "scriptId":"u103"},
    "69147be70ae548eb8a436d7fa08903cc":{
      "scriptId":"u104"},
    "6211a7f56c4d4ad78390a178c435a9b0":{
      "scriptId":"u105"},
    "aaa6652102bb4a808462100f73e283da":{
      "scriptId":"u106"},
    "5d39747913cc43f899369f8ff97859a7":{
      "scriptId":"u107"},
    "8de1eb5f62ca4dbba5477bd75c940dc0":{
      "scriptId":"u108"},
    "bb0c3c03e01e432aad25a189bce9c01b":{
      "scriptId":"u109"},
    "f3df973f8e7f473d92261052dea56e44":{
      "scriptId":"u110"},
    "4f3391cd216647bab26936f9a1aaba34":{
      "scriptId":"u111"},
    "b094a4e7ac1f4585b76ce25aa20f54dc":{
      "scriptId":"u112"},
    "dd86fc6472cd4bb48ec14a5e00eedf62":{
      "scriptId":"u113"},
    "b8db44d1463f411e919b80c02d110f4b":{
      "scriptId":"u114"},
    "50fe4c8557d94b1e9239ff8dfc739f12":{
      "scriptId":"u115"}}});