$axure.loadCurrentPage({
  "url":"其它需求.html",
  "generationDate":new Date(1663292883900.16),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"1148fc410a214a84addac7eb677e2a29",
    "type":"Axure:Page",
    "name":"其它需求",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"23440cfd026641b791c076b46b9af7b3",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":70,
              "y":100},
            "size":{
              "width":560,
              "height":266}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fe17962fcd4c460fabf4dfb2598c607d",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "size":{
                  "width":187,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"c6768d04448e41a1bbfa2a38bc112bb6",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "size":{
                      "width":187,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/协同管理/u1.png"}},
{
              "id":"2c1ba710f5d54d75b1e1ffcc79be5167",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":30},
                "size":{
                  "width":187,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"824e2fb7c95749d8ab5d7422e4151ebc",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":30},
                    "size":{
                      "width":187,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/协同管理/u7.png"}},
{
              "id":"a0c1597a1e5b43919f02458354036d3c",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":66},
                "size":{
                  "width":187,
                  "height":52}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"9ce2a2a15cfa44f7a55a8436fca3b3a2",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":66},
                    "size":{
                      "width":187,
                      "height":52}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/协同管理/u13.png"}},
{
              "id":"053a85445a024572833d4ce56dd523e0",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":187,
                  "y":0},
                "size":{
                  "width":124,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"b9fa0a4ee9514e32984add6e9d101f91",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":187,
                      "y":0},
                    "size":{
                      "width":124,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/协同管理/u3.png"}},
{
              "id":"2314c42145de4b12ac3637227f473ef4",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":187,
                  "y":30},
                "size":{
                  "width":124,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"9d12ebbac70b41919bca624a6a096c31",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":187,
                      "y":30},
                    "size":{
                      "width":124,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/协同管理/u9.png"}},
{
              "id":"4a88da2bafae4f949451080c3a6d8819",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":187,
                  "y":66},
                "size":{
                  "width":124,
                  "height":52}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"1aed5dfa37cb443ea9b75fea5cdbf3d2",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":187,
                      "y":66},
                    "size":{
                      "width":124,
                      "height":52}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/协同管理/u15.png"}},
{
              "id":"8dfc28f0f67a4bff8399479107ee3245",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":311,
                  "y":0},
                "size":{
                  "width":249,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"762107d9da8f476ba7c09f7b075e5dc0",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":311,
                      "y":0},
                    "size":{
                      "width":249,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/协同管理/u5.png"}},
{
              "id":"0742834b1aab43f6800c2c19436f653f",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":311,
                  "y":30},
                "size":{
                  "width":249,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"113f1ab617c6473fb9d1905e7bef5099",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":311,
                      "y":30},
                    "size":{
                      "width":249,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/协同管理/u11.png"}},
{
              "id":"d4083aad930546a5a36405daa205489f",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":311,
                  "y":66},
                "size":{
                  "width":249,
                  "height":52}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"46d786e9a9004f7f8da30028ffa4a0e4",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":311,
                      "y":66},
                    "size":{
                      "width":249,
                      "height":52}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/协同管理/u17.png"}},
{
              "id":"4b674e2bf4214d4a8d2d94ac003d560d",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":118},
                "size":{
                  "width":187,
                  "height":52}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"de2f6258da744e2cbb9ff7cafd556e85",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":118},
                    "size":{
                      "width":187,
                      "height":52}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/协同管理/u13.png"}},
{
              "id":"575f6ff9fafb4425850e3614f975bee1",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":187,
                  "y":118},
                "size":{
                  "width":124,
                  "height":52}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"6ee0d89517de41f2984437f67e5fbcf4",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":187,
                      "y":118},
                    "size":{
                      "width":124,
                      "height":52}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/协同管理/u15.png"}},
{
              "id":"67de8c16cc294c11b3de66e5feb552d6",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":311,
                  "y":118},
                "size":{
                  "width":249,
                  "height":52}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"1cca2cbdb67049ab8dd9cbf51f0c7ca8",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":311,
                      "y":118},
                    "size":{
                      "width":249,
                      "height":52}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/协同管理/u17.png"}},
{
              "id":"3e205a4d523e4551a3877ce0df22b4cd",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":170},
                "size":{
                  "width":187,
                  "height":48}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"188d744a08bc4c60996b9f9d579d5aa6",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":170},
                    "size":{
                      "width":187,
                      "height":48}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/其它需求/u25.png"}},
{
              "id":"b248106cf25b4735a3b8eaa45411c0a8",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":187,
                  "y":170},
                "size":{
                  "width":124,
                  "height":48}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"568103ea1a7146b48d3f99e76f349c7f",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":187,
                      "y":170},
                    "size":{
                      "width":124,
                      "height":48}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/其它需求/u27.png"}},
{
              "id":"c68d376c04874017adee5eda72bfeb3b",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":311,
                  "y":170},
                "size":{
                  "width":249,
                  "height":48}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"eccc1b36e13c45f5adfd3361482287b3",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":311,
                      "y":170},
                    "size":{
                      "width":249,
                      "height":48}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/其它需求/u29.png"}},
{
              "id":"25c58e2c1d554957b74de05e40751bbc",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":218},
                "size":{
                  "width":187,
                  "height":48}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"c87b36047aed470899d49b15852a08ea",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":218},
                    "size":{
                      "width":187,
                      "height":48}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/协同管理/u25.png"}},
{
              "id":"d8c67467604b4031a5d3fe55d3a7c79f",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":187,
                  "y":218},
                "size":{
                  "width":124,
                  "height":48}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"748105090dfe4720b846e452c07022db",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":187,
                      "y":218},
                    "size":{
                      "width":124,
                      "height":48}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/协同管理/u27.png"}},
{
              "id":"92f69f618c9144ef9f28f746bf8b3d29",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":311,
                  "y":218},
                "size":{
                  "width":249,
                  "height":48}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"1a62e36913844a60b31292a00d7715a0",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":311,
                      "y":218},
                    "size":{
                      "width":249,
                      "height":48}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/协同管理/u29.png"}}]}]}},
  "masters":{
},
  "objectPaths":{
    "23440cfd026641b791c076b46b9af7b3":{
      "scriptId":"u0"},
    "fe17962fcd4c460fabf4dfb2598c607d":{
      "scriptId":"u1"},
    "c6768d04448e41a1bbfa2a38bc112bb6":{
      "scriptId":"u2"},
    "053a85445a024572833d4ce56dd523e0":{
      "scriptId":"u3"},
    "b9fa0a4ee9514e32984add6e9d101f91":{
      "scriptId":"u4"},
    "8dfc28f0f67a4bff8399479107ee3245":{
      "scriptId":"u5"},
    "762107d9da8f476ba7c09f7b075e5dc0":{
      "scriptId":"u6"},
    "2c1ba710f5d54d75b1e1ffcc79be5167":{
      "scriptId":"u7"},
    "824e2fb7c95749d8ab5d7422e4151ebc":{
      "scriptId":"u8"},
    "2314c42145de4b12ac3637227f473ef4":{
      "scriptId":"u9"},
    "9d12ebbac70b41919bca624a6a096c31":{
      "scriptId":"u10"},
    "0742834b1aab43f6800c2c19436f653f":{
      "scriptId":"u11"},
    "113f1ab617c6473fb9d1905e7bef5099":{
      "scriptId":"u12"},
    "a0c1597a1e5b43919f02458354036d3c":{
      "scriptId":"u13"},
    "9ce2a2a15cfa44f7a55a8436fca3b3a2":{
      "scriptId":"u14"},
    "4a88da2bafae4f949451080c3a6d8819":{
      "scriptId":"u15"},
    "1aed5dfa37cb443ea9b75fea5cdbf3d2":{
      "scriptId":"u16"},
    "d4083aad930546a5a36405daa205489f":{
      "scriptId":"u17"},
    "46d786e9a9004f7f8da30028ffa4a0e4":{
      "scriptId":"u18"},
    "4b674e2bf4214d4a8d2d94ac003d560d":{
      "scriptId":"u19"},
    "de2f6258da744e2cbb9ff7cafd556e85":{
      "scriptId":"u20"},
    "575f6ff9fafb4425850e3614f975bee1":{
      "scriptId":"u21"},
    "6ee0d89517de41f2984437f67e5fbcf4":{
      "scriptId":"u22"},
    "67de8c16cc294c11b3de66e5feb552d6":{
      "scriptId":"u23"},
    "1cca2cbdb67049ab8dd9cbf51f0c7ca8":{
      "scriptId":"u24"},
    "3e205a4d523e4551a3877ce0df22b4cd":{
      "scriptId":"u25"},
    "188d744a08bc4c60996b9f9d579d5aa6":{
      "scriptId":"u26"},
    "b248106cf25b4735a3b8eaa45411c0a8":{
      "scriptId":"u27"},
    "568103ea1a7146b48d3f99e76f349c7f":{
      "scriptId":"u28"},
    "c68d376c04874017adee5eda72bfeb3b":{
      "scriptId":"u29"},
    "eccc1b36e13c45f5adfd3361482287b3":{
      "scriptId":"u30"},
    "25c58e2c1d554957b74de05e40751bbc":{
      "scriptId":"u31"},
    "c87b36047aed470899d49b15852a08ea":{
      "scriptId":"u32"},
    "d8c67467604b4031a5d3fe55d3a7c79f":{
      "scriptId":"u33"},
    "748105090dfe4720b846e452c07022db":{
      "scriptId":"u34"},
    "92f69f618c9144ef9f28f746bf8b3d29":{
      "scriptId":"u35"},
    "1a62e36913844a60b31292a00d7715a0":{
      "scriptId":"u36"}}});