$axure.loadCurrentPage({
  "url":"贷款余额走势图-按月.html",
  "generationDate":new Date(1659117590908.99),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"06be03041ccc42d5adb8445aa659a52e",
    "type":"Axure:Page",
    "name":"贷款余额走势图-按月",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"e2074b88634e448a98768fcb6bad6b7c",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":50,
              "y":32},
            "size":{
              "width":510,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4e83c609a0384a3c925cbe416b84d670",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":50,
                  "y":32},
                "size":{
                  "width":510,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f248b7d560c1447ea2bb75187abc561c",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":75,
              "y":90},
            "size":{
              "width":105,
              "height":25}},
          "adaptiveStyles":{
},
          "placeholderText":"请输入客户名称"},
{
          "id":"4006281f45324024977edc354b922a96",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":48,
              "y":70},
            "size":{
              "width":852,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/贷款余额登记管理/u6_line.png"}},
{
          "id":"8f4a10112df24b938532ca6d6c9ca233",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":190,
              "y":90},
            "size":{
              "width":130,
              "height":25}},
          "adaptiveStyles":{
},
          "placeholderText":"请输入截止日期起止"},
{
          "id":"b336e60f6a3348948b262ddd0c2a5c68",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":330,
              "y":90},
            "size":{
              "width":120,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"ddc748402e0d42fca0a6d8a2c040ad04",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":460,
              "y":90},
            "size":{
              "width":120,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"e5ef3f618ae84136ba49b793e068af9f",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":590,
              "y":90},
            "size":{
              "width":120,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"f1828aa5bbf74245b81a691a70bef4a0",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":730,
              "y":90},
            "size":{
              "width":110,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"12b83612b23f4520be05dd9f3f7b2f20",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":850,
              "y":90},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"6665266d83c144ef8e68049b49f44499",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":970,
              "y":90},
            "size":{
              "width":60,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"a6a7e844839f4989a3442d660b0e1c63",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":90,
              "y":132},
            "size":{
              "width":155,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1a109bf4e95b43328d1b1bbd12a37111",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":90,
                  "y":132},
                "size":{
                  "width":155,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3117ba0980e94fa3944a33b59fab67a9",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":75,
              "y":170},
            "size":{
              "width":700,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b61793e3cfbc4f42852af87bbfe47795",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "size":{
                  "width":100,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"084909015cea4a2ab1c070bcc4429744",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":100,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/贷款余额走势图-按月/u14.png"}},
{
              "id":"84c6d73fad7f4550b52fba08c57d4250",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":20},
                "size":{
                  "width":100,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"0fecff91f0c140cf8e1ad49e3f2f5516",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":20},
                    "size":{
                      "width":100,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/贷款余额走势图-按月/u14.png"}},
{
              "id":"04ff3eb7a41f4f32b25246c8330b4038",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":40},
                "size":{
                  "width":100,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"8648ab256666485e94cf9d9d4c4897a3",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":40},
                    "size":{
                      "width":100,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/贷款余额走势图-按月/u14.png"}},
{
              "id":"220a56d26a474a308dd0afc8bcfb8d15",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":60},
                "size":{
                  "width":100,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"aef91fa8e51d4c28936e3ac7770dae9c",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":60},
                    "size":{
                      "width":100,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/贷款余额走势图-按月/u56.png"}},
{
              "id":"e211a00a36bf4a78982097f1476217bb",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":100,
                  "y":0},
                "size":{
                  "width":100,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"8707c4cb1c3a43fb8aba26ba850ff7d3",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":100,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/贷款余额走势图-按月/u14.png"}},
{
              "id":"48ebfe7018184e28bca40d8488d2fc4b",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":100,
                  "y":20},
                "size":{
                  "width":100,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"8aff4b3854ab48eba5bc6e061e26ac4b",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":100,
                      "y":20},
                    "size":{
                      "width":100,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/贷款余额走势图-按月/u14.png"}},
{
              "id":"6c5008f8063e4384ab053b19278974ff",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":100,
                  "y":40},
                "size":{
                  "width":100,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"edaa6311d5834e39bd977a2cb2014c11",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":100,
                      "y":40},
                    "size":{
                      "width":100,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/贷款余额走势图-按月/u14.png"}},
{
              "id":"5044b972098d4a8eb3823df13cc6e01b",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":100,
                  "y":60},
                "size":{
                  "width":100,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"74ac59a68d80449a80f0a6f9ccc06abf",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":100,
                      "y":60},
                    "size":{
                      "width":100,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/贷款余额走势图-按月/u56.png"}},
{
              "id":"8150970b034b41a184d1830c4e94cde4",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":200,
                  "y":0},
                "size":{
                  "width":100,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"912d53f2f70a45b8b06be9a026eafeb7",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":200,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/贷款余额走势图-按月/u14.png"}},
{
              "id":"af94a258c664495b91e6335bb151fc96",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":200,
                  "y":20},
                "size":{
                  "width":100,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"339957505e9548f4b52e508cadd93c77",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":200,
                      "y":20},
                    "size":{
                      "width":100,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/贷款余额走势图-按月/u14.png"}},
{
              "id":"d1324c8f189e4fa5a4e20e39519c2d9e",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":200,
                  "y":40},
                "size":{
                  "width":100,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"60ac5f1ec2c8420b9ee71d2a5b4fd282",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":200,
                      "y":40},
                    "size":{
                      "width":100,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/贷款余额走势图-按月/u14.png"}},
{
              "id":"5ceb5860b5c74b6b88511d5172028c9e",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":200,
                  "y":60},
                "size":{
                  "width":100,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"a19aaf2d9cca400ebc9ede557502a7fd",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":200,
                      "y":60},
                    "size":{
                      "width":100,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/贷款余额走势图-按月/u56.png"}},
{
              "id":"38a1bfcfe929403abcff518101b7965d",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":300,
                  "y":0},
                "size":{
                  "width":100,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"e1a82d057c7b471797da28ae20854f00",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":300,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/贷款余额走势图-按月/u14.png"}},
{
              "id":"1e9983dabe7a4a61ac664de3549a231e",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":300,
                  "y":20},
                "size":{
                  "width":100,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"24560237791e466da9b2bd40f9b1aca4",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":300,
                      "y":20},
                    "size":{
                      "width":100,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/贷款余额走势图-按月/u14.png"}},
{
              "id":"1a6028808aa147fd94ee8eff5dd844b5",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":300,
                  "y":40},
                "size":{
                  "width":100,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"6cec20e6b1e544bb853eaca5cef152cd",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":300,
                      "y":40},
                    "size":{
                      "width":100,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/贷款余额走势图-按月/u14.png"}},
{
              "id":"1a32f802a30c4e0e8c1a24485b7ebc81",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":300,
                  "y":60},
                "size":{
                  "width":100,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"1fc0efa33c984909858a00ae2fc8d18c",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":300,
                      "y":60},
                    "size":{
                      "width":100,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/贷款余额走势图-按月/u56.png"}},
{
              "id":"a5958beac8e84c93899513d971979d73",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":400,
                  "y":0},
                "size":{
                  "width":100,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"348ac94f5a434b5084ccd3de2275cac2",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":400,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/贷款余额走势图-按月/u14.png"}},
{
              "id":"aac0dfdc19d34f4d9758c84f9def3037",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":400,
                  "y":20},
                "size":{
                  "width":100,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"6e8ea3b4dfc248279c33338905f21be2",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":400,
                      "y":20},
                    "size":{
                      "width":100,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/贷款余额走势图-按月/u14.png"}},
{
              "id":"cf42c808ac794b26ac27da58f8223c14",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":400,
                  "y":40},
                "size":{
                  "width":100,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"a07a876175f14b28a8ec6098548ecfcc",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":400,
                      "y":40},
                    "size":{
                      "width":100,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/贷款余额走势图-按月/u14.png"}},
{
              "id":"36f7aee779c6474a81e188b1595208f8",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":400,
                  "y":60},
                "size":{
                  "width":100,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"b35eb1cebb77405eb173699157de7f9e",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":400,
                      "y":60},
                    "size":{
                      "width":100,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/贷款余额走势图-按月/u56.png"}},
{
              "id":"4ee624d9da97429ea31515b06aa205ff",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":500,
                  "y":0},
                "size":{
                  "width":100,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"e16a2e4eb2da4522a2e3bf330e5353d2",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":500,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/贷款余额走势图-按月/u14.png"}},
{
              "id":"8e44dd39b0af43fa8a1ab0843e4e85d0",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":500,
                  "y":20},
                "size":{
                  "width":100,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"e5a3942ccbea414b8e785777a49b6c91",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":500,
                      "y":20},
                    "size":{
                      "width":100,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/贷款余额走势图-按月/u14.png"}},
{
              "id":"47df554429784b10b0206f640860d0bb",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":500,
                  "y":40},
                "size":{
                  "width":100,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"278c803d736f4bb2975efe08b83a9bd0",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":500,
                      "y":40},
                    "size":{
                      "width":100,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/贷款余额走势图-按月/u14.png"}},
{
              "id":"ed3c003c66564ba8b95be70b96f975d3",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":500,
                  "y":60},
                "size":{
                  "width":100,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"10b85acb997d4bf9a13cc2fceb7fe6fd",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":500,
                      "y":60},
                    "size":{
                      "width":100,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/贷款余额走势图-按月/u56.png"}},
{
              "id":"7302ef7548924df48840ac08ac13aaf0",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":600,
                  "y":0},
                "size":{
                  "width":100,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"0803326674c94f79b04cf5fe8e1bb615",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":600,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/贷款余额走势图-按月/u26.png"}},
{
              "id":"5041dadb60514e07b116cada80cb7113",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":600,
                  "y":20},
                "size":{
                  "width":100,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"fc216596826f4c6a8146532272564f34",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":600,
                      "y":20},
                    "size":{
                      "width":100,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/贷款余额走势图-按月/u26.png"}},
{
              "id":"8b725647089c4467a780bcafa2722a53",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":600,
                  "y":40},
                "size":{
                  "width":100,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"5c57862e22a94434b2341a736498fd61",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":600,
                      "y":40},
                    "size":{
                      "width":100,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/贷款余额走势图-按月/u26.png"}},
{
              "id":"70679814c7334a84bd349b5c2cd7b557",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":600,
                  "y":60},
                "size":{
                  "width":100,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"3e32f4ee09704cd5ad1e48c530612945",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":600,
                      "y":60},
                    "size":{
                      "width":100,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/贷款余额走势图-按月/u68.png"}}]},
{
          "id":"9222f26e824a4a31bca3b5377346ff73",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":59,
              "y":313},
            "size":{
              "width":392,
              "height":257}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9cb32e9ceef1418cb4d7816f80475481",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":59,
                  "y":313},
                "size":{
                  "width":392,
                  "height":257}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/贷款余额走势图-按月/u70.png"}},
{
          "id":"47e812e4a7c04c188d661d245e07099c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":474,
              "y":313},
            "size":{
              "width":416,
              "height":247}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c7f04cd8b713463f919b76b7a6327d3b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":474,
                  "y":313},
                "size":{
                  "width":416,
                  "height":247}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/贷款余额走势图-按月/u72.png"}},
{
          "id":"9cc3fe9ded3d431592cdf96aa055bf24",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "underline":true,
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":190,
              "y":273},
            "size":{
              "width":80,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5a9d0a9a52ac434383118f571f52b18f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "underline":true,
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":190,
                  "y":273},
                "size":{
                  "width":80,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fec8214114404227aa334cf19b3feafc",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":75,
              "y":270},
            "size":{
              "width":105,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"70bf561119cf424bbe4d45ecb4ddb761",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":90,
              "y":590},
            "size":{
              "width":386,
              "height":160}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"068e7f16ac6e406f958a0a5343c02f90",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":90,
                  "y":590},
                "size":{
                  "width":386,
                  "height":160}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "e2074b88634e448a98768fcb6bad6b7c":{
      "scriptId":"u0"},
    "4e83c609a0384a3c925cbe416b84d670":{
      "scriptId":"u1"},
    "f248b7d560c1447ea2bb75187abc561c":{
      "scriptId":"u2"},
    "4006281f45324024977edc354b922a96":{
      "scriptId":"u3"},
    "8f4a10112df24b938532ca6d6c9ca233":{
      "scriptId":"u4"},
    "b336e60f6a3348948b262ddd0c2a5c68":{
      "scriptId":"u5"},
    "ddc748402e0d42fca0a6d8a2c040ad04":{
      "scriptId":"u6"},
    "e5ef3f618ae84136ba49b793e068af9f":{
      "scriptId":"u7"},
    "f1828aa5bbf74245b81a691a70bef4a0":{
      "scriptId":"u8"},
    "12b83612b23f4520be05dd9f3f7b2f20":{
      "scriptId":"u9"},
    "6665266d83c144ef8e68049b49f44499":{
      "scriptId":"u10"},
    "a6a7e844839f4989a3442d660b0e1c63":{
      "scriptId":"u11"},
    "1a109bf4e95b43328d1b1bbd12a37111":{
      "scriptId":"u12"},
    "3117ba0980e94fa3944a33b59fab67a9":{
      "scriptId":"u13"},
    "b61793e3cfbc4f42852af87bbfe47795":{
      "scriptId":"u14"},
    "084909015cea4a2ab1c070bcc4429744":{
      "scriptId":"u15"},
    "e211a00a36bf4a78982097f1476217bb":{
      "scriptId":"u16"},
    "8707c4cb1c3a43fb8aba26ba850ff7d3":{
      "scriptId":"u17"},
    "8150970b034b41a184d1830c4e94cde4":{
      "scriptId":"u18"},
    "912d53f2f70a45b8b06be9a026eafeb7":{
      "scriptId":"u19"},
    "38a1bfcfe929403abcff518101b7965d":{
      "scriptId":"u20"},
    "e1a82d057c7b471797da28ae20854f00":{
      "scriptId":"u21"},
    "a5958beac8e84c93899513d971979d73":{
      "scriptId":"u22"},
    "348ac94f5a434b5084ccd3de2275cac2":{
      "scriptId":"u23"},
    "4ee624d9da97429ea31515b06aa205ff":{
      "scriptId":"u24"},
    "e16a2e4eb2da4522a2e3bf330e5353d2":{
      "scriptId":"u25"},
    "7302ef7548924df48840ac08ac13aaf0":{
      "scriptId":"u26"},
    "0803326674c94f79b04cf5fe8e1bb615":{
      "scriptId":"u27"},
    "84c6d73fad7f4550b52fba08c57d4250":{
      "scriptId":"u28"},
    "0fecff91f0c140cf8e1ad49e3f2f5516":{
      "scriptId":"u29"},
    "48ebfe7018184e28bca40d8488d2fc4b":{
      "scriptId":"u30"},
    "8aff4b3854ab48eba5bc6e061e26ac4b":{
      "scriptId":"u31"},
    "af94a258c664495b91e6335bb151fc96":{
      "scriptId":"u32"},
    "339957505e9548f4b52e508cadd93c77":{
      "scriptId":"u33"},
    "1e9983dabe7a4a61ac664de3549a231e":{
      "scriptId":"u34"},
    "24560237791e466da9b2bd40f9b1aca4":{
      "scriptId":"u35"},
    "aac0dfdc19d34f4d9758c84f9def3037":{
      "scriptId":"u36"},
    "6e8ea3b4dfc248279c33338905f21be2":{
      "scriptId":"u37"},
    "8e44dd39b0af43fa8a1ab0843e4e85d0":{
      "scriptId":"u38"},
    "e5a3942ccbea414b8e785777a49b6c91":{
      "scriptId":"u39"},
    "5041dadb60514e07b116cada80cb7113":{
      "scriptId":"u40"},
    "fc216596826f4c6a8146532272564f34":{
      "scriptId":"u41"},
    "04ff3eb7a41f4f32b25246c8330b4038":{
      "scriptId":"u42"},
    "8648ab256666485e94cf9d9d4c4897a3":{
      "scriptId":"u43"},
    "6c5008f8063e4384ab053b19278974ff":{
      "scriptId":"u44"},
    "edaa6311d5834e39bd977a2cb2014c11":{
      "scriptId":"u45"},
    "d1324c8f189e4fa5a4e20e39519c2d9e":{
      "scriptId":"u46"},
    "60ac5f1ec2c8420b9ee71d2a5b4fd282":{
      "scriptId":"u47"},
    "1a6028808aa147fd94ee8eff5dd844b5":{
      "scriptId":"u48"},
    "6cec20e6b1e544bb853eaca5cef152cd":{
      "scriptId":"u49"},
    "cf42c808ac794b26ac27da58f8223c14":{
      "scriptId":"u50"},
    "a07a876175f14b28a8ec6098548ecfcc":{
      "scriptId":"u51"},
    "47df554429784b10b0206f640860d0bb":{
      "scriptId":"u52"},
    "278c803d736f4bb2975efe08b83a9bd0":{
      "scriptId":"u53"},
    "8b725647089c4467a780bcafa2722a53":{
      "scriptId":"u54"},
    "5c57862e22a94434b2341a736498fd61":{
      "scriptId":"u55"},
    "220a56d26a474a308dd0afc8bcfb8d15":{
      "scriptId":"u56"},
    "aef91fa8e51d4c28936e3ac7770dae9c":{
      "scriptId":"u57"},
    "5044b972098d4a8eb3823df13cc6e01b":{
      "scriptId":"u58"},
    "74ac59a68d80449a80f0a6f9ccc06abf":{
      "scriptId":"u59"},
    "5ceb5860b5c74b6b88511d5172028c9e":{
      "scriptId":"u60"},
    "a19aaf2d9cca400ebc9ede557502a7fd":{
      "scriptId":"u61"},
    "1a32f802a30c4e0e8c1a24485b7ebc81":{
      "scriptId":"u62"},
    "1fc0efa33c984909858a00ae2fc8d18c":{
      "scriptId":"u63"},
    "36f7aee779c6474a81e188b1595208f8":{
      "scriptId":"u64"},
    "b35eb1cebb77405eb173699157de7f9e":{
      "scriptId":"u65"},
    "ed3c003c66564ba8b95be70b96f975d3":{
      "scriptId":"u66"},
    "10b85acb997d4bf9a13cc2fceb7fe6fd":{
      "scriptId":"u67"},
    "70679814c7334a84bd349b5c2cd7b557":{
      "scriptId":"u68"},
    "3e32f4ee09704cd5ad1e48c530612945":{
      "scriptId":"u69"},
    "9222f26e824a4a31bca3b5377346ff73":{
      "scriptId":"u70"},
    "9cb32e9ceef1418cb4d7816f80475481":{
      "scriptId":"u71"},
    "47e812e4a7c04c188d661d245e07099c":{
      "scriptId":"u72"},
    "c7f04cd8b713463f919b76b7a6327d3b":{
      "scriptId":"u73"},
    "9cc3fe9ded3d431592cdf96aa055bf24":{
      "scriptId":"u74"},
    "5a9d0a9a52ac434383118f571f52b18f":{
      "scriptId":"u75"},
    "fec8214114404227aa334cf19b3feafc":{
      "scriptId":"u76"},
    "70bf561119cf424bbe4d45ecb4ddb761":{
      "scriptId":"u77"},
    "068e7f16ac6e406f958a0a5343c02f90":{
      "scriptId":"u78"}}});