$axure.loadCurrentPage({
  "url":"客户经理积分统计.html",
  "generationDate":new Date(1662616252344.8),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"96375c01e2c249aa8d644e15ee5a0389",
    "type":"Axure:Page",
    "name":"客户经理积分统计",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"0651bd8a300042d38aac429308eb0813",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":51,
              "y":32},
            "size":{
              "width":249,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4bb9f8bf396146b7b66fb14802e4c4c7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":51,
                  "y":32},
                "size":{
                  "width":249,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7bb5514923734bf7ac3fad9921ef5542",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":48,
              "y":70},
            "size":{
              "width":852,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/金融产品管理/u5_line.png"}},
{
          "id":"1c6c986da48a4abab79039b45f08ef7e",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":730,
              "y":90},
            "size":{
              "width":60,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"2d1d1b0ba7384e61b4d59bb564aa4cef",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":800,
              "y":90},
            "size":{
              "width":60,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"764ee102b4104c10b85745d10d312937",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":48,
              "y":150},
            "size":{
              "width":777,
              "height":96}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b5135ccf027a47c089827d6f3a1a0015",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":86,
                  "y":0},
                "size":{
                  "width":82,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"1fbbd90cc5a54088b215f6979400cbd4",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":86,
                      "y":0},
                    "size":{
                      "width":82,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/余额_收入详情/u15.png"}},
{
              "id":"a4024332b9bd47248c4f9e38de61f73c",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":86,
                  "y":36},
                "size":{
                  "width":82,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"7f7b4df9522547f991b0eaf398c207d1",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":86,
                      "y":36},
                    "size":{
                      "width":82,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/金融产品管理/u29.png"}},
{
              "id":"6eeac3850be74af5bd42ace98709d32b",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":86,
                  "y":56},
                "size":{
                  "width":82,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"0e923acf6e4e49458211ce4054782cc3",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":86,
                      "y":56},
                    "size":{
                      "width":82,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/金融产品管理/u29.png"}},
{
              "id":"978c3a8a54d44fbdbcca480cefb4c4e2",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":86,
                  "y":76},
                "size":{
                  "width":82,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"7ddbf61c9e2b44ccbfc92cc48cfefc9b",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":86,
                      "y":76},
                    "size":{
                      "width":82,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/金融产品管理/u69.png"}},
{
              "id":"58bae2b351264fbe80b960f2f5d3a5d9",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":168,
                  "y":0},
                "size":{
                  "width":78,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"ae43f79d5186477abb085a92b49d5225",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":168,
                      "y":0},
                    "size":{
                      "width":78,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/客户管理-业务数据展示/u91.png"}},
{
              "id":"96e890df29df4c84b62c15ce260153f7",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":168,
                  "y":36},
                "size":{
                  "width":78,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"dde045c7f1c94b46aa947797204eb7dc",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":168,
                      "y":36},
                    "size":{
                      "width":78,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/客户管理-业务数据展示/u73.png"}},
{
              "id":"48fd2b48789943afb36e186954c7910b",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":168,
                  "y":56},
                "size":{
                  "width":78,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"d8210f5f179b48729ca57dd7a4d53ca1",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":168,
                      "y":56},
                    "size":{
                      "width":78,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/客户管理-业务数据展示/u73.png"}},
{
              "id":"e628bf22227645c1b91c7486e976761b",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":168,
                  "y":76},
                "size":{
                  "width":78,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"abf5eef607d146409b4a608460109fcb",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":168,
                      "y":76},
                    "size":{
                      "width":78,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/客户管理-业务数据展示/u473.png"}},
{
              "id":"260ee175c7c841fd9e5185542ecf7a05",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":246,
                  "y":0},
                "size":{
                  "width":71,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"086731303cb94d2ea98b24d6f6f44697",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":246,
                      "y":0},
                    "size":{
                      "width":71,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/金融产品管理/u13.png"}},
{
              "id":"8ebc026f6e694973984885c03b94a02c",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":246,
                  "y":36},
                "size":{
                  "width":71,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"df3110b4e10e4536b02ec2e35a562b33",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":246,
                      "y":36},
                    "size":{
                      "width":71,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/金融产品管理/u33.png"}},
{
              "id":"3c771e181a79454594c501454b8f49bc",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":246,
                  "y":56},
                "size":{
                  "width":71,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"98fedfaf152f438ea2f41b98a7aa8486",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":246,
                      "y":56},
                    "size":{
                      "width":71,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/金融产品管理/u33.png"}},
{
              "id":"ccc9af254f834e7bb366fb6a1587ca6b",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":246,
                  "y":76},
                "size":{
                  "width":71,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"ea8f0b9ab215410db5bb4b94b548a81e",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":246,
                      "y":76},
                    "size":{
                      "width":71,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/金融产品管理/u73.png"}},
{
              "id":"e18420e37f5b4ad9b3885a0151e03238",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":317,
                  "y":0},
                "size":{
                  "width":113,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"ed405d9696be43c9b023ec2043b95e0d",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":317,
                      "y":0},
                    "size":{
                      "width":113,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/金融产品管理/u15.png"}},
{
              "id":"4ea1f27299c6474ebe5a2af11023ec7b",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":317,
                  "y":36},
                "size":{
                  "width":113,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"6b855497f9634c2f95896c89be17792d",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":317,
                      "y":36},
                    "size":{
                      "width":113,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/金融产品管理/u35.png"}},
{
              "id":"c09a6f6ea8c745c4bb67d389bd5d3274",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":317,
                  "y":56},
                "size":{
                  "width":113,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"7949fb66e5cd4a7eb73a9dd825d668cb",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":317,
                      "y":56},
                    "size":{
                      "width":113,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/金融产品管理/u35.png"}},
{
              "id":"115983d77a42465484cb47975b60765b",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":317,
                  "y":76},
                "size":{
                  "width":113,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"4c4b9bc35bd747fb9e8fcdcc6d6051e2",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":317,
                      "y":76},
                    "size":{
                      "width":113,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/金融产品管理/u75.png"}},
{
              "id":"7e839768e5d041709889ed5c2577cc59",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":512,
                  "y":0},
                "size":{
                  "width":46,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"12e434d394ae4828b1f5cc7988481026",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":512,
                      "y":0},
                    "size":{
                      "width":46,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/余额_收入详情/u7.png"}},
{
              "id":"37614c2fcc704ec48634351ab3db5729",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":512,
                  "y":36},
                "size":{
                  "width":46,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"2e65be4cc39e4964adbc94ec8bd747fd",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":512,
                      "y":36},
                    "size":{
                      "width":46,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/金融产品管理/u45.png"}},
{
              "id":"099effa2cc5348ce85d5f465608f9d11",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":512,
                  "y":56},
                "size":{
                  "width":46,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"b204b31bd4ec40909d3da5e6358b2ade",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":512,
                      "y":56},
                    "size":{
                      "width":46,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/金融产品管理/u45.png"}},
{
              "id":"35ed3da7ca7e43cd8bd741909cca9616",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":512,
                  "y":76},
                "size":{
                  "width":46,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"6f4748cfd23c4a8d87f15d4db59cf86c",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":512,
                      "y":76},
                    "size":{
                      "width":46,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/金融产品管理/u85.png"}},
{
              "id":"eaf62c42c8c041509fb01c649232aaf2",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":558,
                  "y":0},
                "size":{
                  "width":132,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"50bf6e3f9f904f33b705b9d37062b018",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":558,
                      "y":0},
                    "size":{
                      "width":132,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/工作汇报管理/u4.png"}},
{
              "id":"20773267381140e68b30679349bb2090",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000099,
                  "opacity":1},
                "location":{
                  "x":558,
                  "y":36},
                "size":{
                  "width":132,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"0de98a55a97f4ac9bf22f89c1c5b7dbd",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF000099,
                      "opacity":1},
                    "location":{
                      "x":558,
                      "y":36},
                    "size":{
                      "width":132,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/工作汇报管理/u44.png"}},
{
              "id":"81cf65cb04954b638a6bcb88724204e1",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":558,
                  "y":56},
                "size":{
                  "width":132,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"5a62f36419414cbe8e6b3c817d3cb74b",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":558,
                      "y":56},
                    "size":{
                      "width":132,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/工作汇报管理/u44.png"}},
{
              "id":"f7df7ee4553a4526a70ea01bc7407799",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":558,
                  "y":76},
                "size":{
                  "width":132,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"77a149ee63fd492b85000a8d152a7df3",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":558,
                      "y":76},
                    "size":{
                      "width":132,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/客户经理积分统计/u74.png"}},
{
              "id":"9a90a6cfd2874eb8bd86860813818634",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":430,
                  "y":0},
                "size":{
                  "width":82,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"e5eea0adadb34452af1d32b463d55f38",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":430,
                      "y":0},
                    "size":{
                      "width":82,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/余额_收入详情/u15.png"}},
{
              "id":"48a5842d4ebb4a1cb243ae1d67323580",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":430,
                  "y":36},
                "size":{
                  "width":82,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"2554188d207247099a02ba659dde6c2d",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":430,
                      "y":36},
                    "size":{
                      "width":82,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/金融产品管理/u29.png"}},
{
              "id":"abb02af9d67e43e4a629110342d6ae7c",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":430,
                  "y":56},
                "size":{
                  "width":82,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"791211784efc40fe86bee75d0272db8e",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":430,
                      "y":56},
                    "size":{
                      "width":82,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/金融产品管理/u29.png"}},
{
              "id":"8dd1d5b653a54315bd0592e8fe6cb63d",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":430,
                  "y":76},
                "size":{
                  "width":82,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"5dee25050fd94643987acca17e5ebcdf",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":430,
                      "y":76},
                    "size":{
                      "width":82,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/金融产品管理/u69.png"}},
{
              "id":"38d9597898dc42138e0f13e536b290be",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "size":{
                  "width":86,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"9862b2ac875945e5bb9c1f0193afc23f",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":86,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/内部业务数据管理-仅查看/u36.png"}},
{
              "id":"990007817b164f51b871eac42c94caba",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":36},
                "size":{
                  "width":86,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"ff7bcb6874464f9785c7c384515e252a",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":36},
                    "size":{
                      "width":86,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/内部业务数据管理-仅查看/u70.png"}},
{
              "id":"9c61c43e560d48e19d10ca7c9d9cb650",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":56},
                "size":{
                  "width":86,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"14104680224946108603fe8318f1f384",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":56},
                    "size":{
                      "width":86,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/内部业务数据管理-仅查看/u70.png"}},
{
              "id":"61eba8f82e5b41768942dc63fb042f99",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":76},
                "size":{
                  "width":86,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"b403dbae24ac4c35947688bf5b35d6fa",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":76},
                    "size":{
                      "width":86,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/内部业务数据管理-仅查看/u240.png"}},
{
              "id":"5f8ecbe231eb4db08652f71cbe794873",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":690,
                  "y":0},
                "size":{
                  "width":87,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"d4f7707eed634be68451954a4dacab58",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":690,
                      "y":0},
                    "size":{
                      "width":87,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/客户经理积分统计/u22.png"}},
{
              "id":"ee8c645a83734af2a6916d694968b16f",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000099,
                  "opacity":1},
                "location":{
                  "x":690,
                  "y":36},
                "size":{
                  "width":87,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"051180f41ff946f88de506d766bd123a",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF000099,
                      "opacity":1},
                    "location":{
                      "x":690,
                      "y":36},
                    "size":{
                      "width":87,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/客户经理积分统计/u40.png"}},
{
              "id":"043dca65be4a4edbac7b68aaf52303be",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":690,
                  "y":56},
                "size":{
                  "width":87,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"bc9ebb1113464d85a6c95e9981cb3e2d",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":690,
                      "y":56},
                    "size":{
                      "width":87,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/客户经理积分统计/u40.png"}},
{
              "id":"93ddc47126644c3e95314d3b791962db",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":690,
                  "y":76},
                "size":{
                  "width":87,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"1fbd54a46be24bbb92aac61a9f652fe0",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":690,
                      "y":76},
                    "size":{
                      "width":87,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/客户经理积分统计/u76.png"}}]},
{
          "id":"a8aa1723f3b242158d0f748101787a78",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":220,
              "y":263},
            "size":{
              "width":508,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8df78616ff844d6e919846ef20ea4fed",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":220,
                  "y":263},
                "size":{
                  "width":508,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/客户管理-业务数据展示/u559.png"}},
{
          "id":"7e78be9c1530448c9abb3a3520b97b7b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":717,
              "y":394},
            "size":{
              "width":513,
              "height":192}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"69147be70ae548eb8a436d7fa08903cc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":717,
                  "y":394},
                "size":{
                  "width":513,
                  "height":192}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6211a7f56c4d4ad78390a178c435a9b0",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":370,
              "y":90},
            "size":{
              "width":120,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"aaa6652102bb4a808462100f73e283da",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":186,
              "y":92},
            "size":{
              "width":154,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"5d39747913cc43f899369f8ff97859a7",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":48,
              "y":92},
            "size":{
              "width":132,
              "height":25}},
          "adaptiveStyles":{
},
          "placeholderText":"请输入客户经理姓名"},
{
          "id":"f0c3166460a04fabae9297ed922b1ce9",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":90,
              "y":350},
            "size":{
              "width":300,
              "height":90}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6882d50930094c239f1b16f48b9c450f",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"fa5b9b081168480c88208810021452c5",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/添加模块/u1.png"}},
{
              "id":"d02133fa7ee749168f61cb2609019548",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":30},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"de78cff921e84731b5a231fb6523b6ae",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":30},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/添加模块/u1.png"}},
{
              "id":"06df18228fb74c16ace36a92e897da95",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":60},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"d4072e465d5f4102adcc5bb034cd0143",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":60},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/编辑模块顺序/u13.png"}},
{
              "id":"6ca81e84ab5b49d3a65c234cb37939a6",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":100,
                  "y":0},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"0cf0aaa1be0b48da8e2cfa9fc5d323b3",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":100,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/添加模块/u1.png"}},
{
              "id":"6e38f10f99e94279918a2eac1d0c6cc3",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":100,
                  "y":30},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"76c0501aaed045afb141e4c29989505b",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":100,
                      "y":30},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/添加模块/u1.png"}},
{
              "id":"a7228e898b504ed3a34ef9e136621f40",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":100,
                  "y":60},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"2b9e53cd237845bd9cb3d6a8c5fbd995",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":100,
                      "y":60},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/编辑模块顺序/u13.png"}},
{
              "id":"5ca99604358c456cbb6ae8f893fc6b1a",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":200,
                  "y":0},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"edd7a6015c8c41438d5baa3f846ff9a1",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":200,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/添加模块/u5.png"}},
{
              "id":"d9ee676c860347389d703ae7ab573dd8",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":200,
                  "y":30},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"7234a929bea145c8bb667fa6305fd1ec",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":200,
                      "y":30},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/添加模块/u5.png"}},
{
              "id":"42fafc80595d454fb6bde974e6303d53",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":200,
                  "y":60},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"d0c09e09ebbe4cd4943f756b205029a3",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":200,
                      "y":60},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/编辑模块顺序/u15.png"}}]},
{
          "id":"3875b95a5f8043779727104462ff7dbd",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":48,
              "y":117},
            "size":{
              "width":102,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"52eb38ef3c56467eb2a0100524b788c6",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":340,
              "y":315},
            "size":{
              "width":60,
              "height":25}},
          "adaptiveStyles":{
}}]}},
  "masters":{
},
  "objectPaths":{
    "0651bd8a300042d38aac429308eb0813":{
      "scriptId":"u0"},
    "4bb9f8bf396146b7b66fb14802e4c4c7":{
      "scriptId":"u1"},
    "7bb5514923734bf7ac3fad9921ef5542":{
      "scriptId":"u2"},
    "1c6c986da48a4abab79039b45f08ef7e":{
      "scriptId":"u3"},
    "2d1d1b0ba7384e61b4d59bb564aa4cef":{
      "scriptId":"u4"},
    "764ee102b4104c10b85745d10d312937":{
      "scriptId":"u5"},
    "38d9597898dc42138e0f13e536b290be":{
      "scriptId":"u6"},
    "9862b2ac875945e5bb9c1f0193afc23f":{
      "scriptId":"u7"},
    "b5135ccf027a47c089827d6f3a1a0015":{
      "scriptId":"u8"},
    "1fbbd90cc5a54088b215f6979400cbd4":{
      "scriptId":"u9"},
    "58bae2b351264fbe80b960f2f5d3a5d9":{
      "scriptId":"u10"},
    "ae43f79d5186477abb085a92b49d5225":{
      "scriptId":"u11"},
    "260ee175c7c841fd9e5185542ecf7a05":{
      "scriptId":"u12"},
    "086731303cb94d2ea98b24d6f6f44697":{
      "scriptId":"u13"},
    "e18420e37f5b4ad9b3885a0151e03238":{
      "scriptId":"u14"},
    "ed405d9696be43c9b023ec2043b95e0d":{
      "scriptId":"u15"},
    "9a90a6cfd2874eb8bd86860813818634":{
      "scriptId":"u16"},
    "e5eea0adadb34452af1d32b463d55f38":{
      "scriptId":"u17"},
    "7e839768e5d041709889ed5c2577cc59":{
      "scriptId":"u18"},
    "12e434d394ae4828b1f5cc7988481026":{
      "scriptId":"u19"},
    "eaf62c42c8c041509fb01c649232aaf2":{
      "scriptId":"u20"},
    "50bf6e3f9f904f33b705b9d37062b018":{
      "scriptId":"u21"},
    "5f8ecbe231eb4db08652f71cbe794873":{
      "scriptId":"u22"},
    "d4f7707eed634be68451954a4dacab58":{
      "scriptId":"u23"},
    "990007817b164f51b871eac42c94caba":{
      "scriptId":"u24"},
    "ff7bcb6874464f9785c7c384515e252a":{
      "scriptId":"u25"},
    "a4024332b9bd47248c4f9e38de61f73c":{
      "scriptId":"u26"},
    "7f7b4df9522547f991b0eaf398c207d1":{
      "scriptId":"u27"},
    "96e890df29df4c84b62c15ce260153f7":{
      "scriptId":"u28"},
    "dde045c7f1c94b46aa947797204eb7dc":{
      "scriptId":"u29"},
    "8ebc026f6e694973984885c03b94a02c":{
      "scriptId":"u30"},
    "df3110b4e10e4536b02ec2e35a562b33":{
      "scriptId":"u31"},
    "4ea1f27299c6474ebe5a2af11023ec7b":{
      "scriptId":"u32"},
    "6b855497f9634c2f95896c89be17792d":{
      "scriptId":"u33"},
    "48a5842d4ebb4a1cb243ae1d67323580":{
      "scriptId":"u34"},
    "2554188d207247099a02ba659dde6c2d":{
      "scriptId":"u35"},
    "37614c2fcc704ec48634351ab3db5729":{
      "scriptId":"u36"},
    "2e65be4cc39e4964adbc94ec8bd747fd":{
      "scriptId":"u37"},
    "20773267381140e68b30679349bb2090":{
      "scriptId":"u38"},
    "0de98a55a97f4ac9bf22f89c1c5b7dbd":{
      "scriptId":"u39"},
    "ee8c645a83734af2a6916d694968b16f":{
      "scriptId":"u40"},
    "051180f41ff946f88de506d766bd123a":{
      "scriptId":"u41"},
    "9c61c43e560d48e19d10ca7c9d9cb650":{
      "scriptId":"u42"},
    "14104680224946108603fe8318f1f384":{
      "scriptId":"u43"},
    "6eeac3850be74af5bd42ace98709d32b":{
      "scriptId":"u44"},
    "0e923acf6e4e49458211ce4054782cc3":{
      "scriptId":"u45"},
    "48fd2b48789943afb36e186954c7910b":{
      "scriptId":"u46"},
    "d8210f5f179b48729ca57dd7a4d53ca1":{
      "scriptId":"u47"},
    "3c771e181a79454594c501454b8f49bc":{
      "scriptId":"u48"},
    "98fedfaf152f438ea2f41b98a7aa8486":{
      "scriptId":"u49"},
    "c09a6f6ea8c745c4bb67d389bd5d3274":{
      "scriptId":"u50"},
    "7949fb66e5cd4a7eb73a9dd825d668cb":{
      "scriptId":"u51"},
    "abb02af9d67e43e4a629110342d6ae7c":{
      "scriptId":"u52"},
    "791211784efc40fe86bee75d0272db8e":{
      "scriptId":"u53"},
    "099effa2cc5348ce85d5f465608f9d11":{
      "scriptId":"u54"},
    "b204b31bd4ec40909d3da5e6358b2ade":{
      "scriptId":"u55"},
    "81cf65cb04954b638a6bcb88724204e1":{
      "scriptId":"u56"},
    "5a62f36419414cbe8e6b3c817d3cb74b":{
      "scriptId":"u57"},
    "043dca65be4a4edbac7b68aaf52303be":{
      "scriptId":"u58"},
    "bc9ebb1113464d85a6c95e9981cb3e2d":{
      "scriptId":"u59"},
    "61eba8f82e5b41768942dc63fb042f99":{
      "scriptId":"u60"},
    "b403dbae24ac4c35947688bf5b35d6fa":{
      "scriptId":"u61"},
    "978c3a8a54d44fbdbcca480cefb4c4e2":{
      "scriptId":"u62"},
    "7ddbf61c9e2b44ccbfc92cc48cfefc9b":{
      "scriptId":"u63"},
    "e628bf22227645c1b91c7486e976761b":{
      "scriptId":"u64"},
    "abf5eef607d146409b4a608460109fcb":{
      "scriptId":"u65"},
    "ccc9af254f834e7bb366fb6a1587ca6b":{
      "scriptId":"u66"},
    "ea8f0b9ab215410db5bb4b94b548a81e":{
      "scriptId":"u67"},
    "115983d77a42465484cb47975b60765b":{
      "scriptId":"u68"},
    "4c4b9bc35bd747fb9e8fcdcc6d6051e2":{
      "scriptId":"u69"},
    "8dd1d5b653a54315bd0592e8fe6cb63d":{
      "scriptId":"u70"},
    "5dee25050fd94643987acca17e5ebcdf":{
      "scriptId":"u71"},
    "35ed3da7ca7e43cd8bd741909cca9616":{
      "scriptId":"u72"},
    "6f4748cfd23c4a8d87f15d4db59cf86c":{
      "scriptId":"u73"},
    "f7df7ee4553a4526a70ea01bc7407799":{
      "scriptId":"u74"},
    "77a149ee63fd492b85000a8d152a7df3":{
      "scriptId":"u75"},
    "93ddc47126644c3e95314d3b791962db":{
      "scriptId":"u76"},
    "1fbd54a46be24bbb92aac61a9f652fe0":{
      "scriptId":"u77"},
    "a8aa1723f3b242158d0f748101787a78":{
      "scriptId":"u78"},
    "8df78616ff844d6e919846ef20ea4fed":{
      "scriptId":"u79"},
    "7e78be9c1530448c9abb3a3520b97b7b":{
      "scriptId":"u80"},
    "69147be70ae548eb8a436d7fa08903cc":{
      "scriptId":"u81"},
    "6211a7f56c4d4ad78390a178c435a9b0":{
      "scriptId":"u82"},
    "aaa6652102bb4a808462100f73e283da":{
      "scriptId":"u83"},
    "5d39747913cc43f899369f8ff97859a7":{
      "scriptId":"u84"},
    "f0c3166460a04fabae9297ed922b1ce9":{
      "scriptId":"u85"},
    "6882d50930094c239f1b16f48b9c450f":{
      "scriptId":"u86"},
    "fa5b9b081168480c88208810021452c5":{
      "scriptId":"u87"},
    "6ca81e84ab5b49d3a65c234cb37939a6":{
      "scriptId":"u88"},
    "0cf0aaa1be0b48da8e2cfa9fc5d323b3":{
      "scriptId":"u89"},
    "5ca99604358c456cbb6ae8f893fc6b1a":{
      "scriptId":"u90"},
    "edd7a6015c8c41438d5baa3f846ff9a1":{
      "scriptId":"u91"},
    "d02133fa7ee749168f61cb2609019548":{
      "scriptId":"u92"},
    "de78cff921e84731b5a231fb6523b6ae":{
      "scriptId":"u93"},
    "6e38f10f99e94279918a2eac1d0c6cc3":{
      "scriptId":"u94"},
    "76c0501aaed045afb141e4c29989505b":{
      "scriptId":"u95"},
    "d9ee676c860347389d703ae7ab573dd8":{
      "scriptId":"u96"},
    "7234a929bea145c8bb667fa6305fd1ec":{
      "scriptId":"u97"},
    "06df18228fb74c16ace36a92e897da95":{
      "scriptId":"u98"},
    "d4072e465d5f4102adcc5bb034cd0143":{
      "scriptId":"u99"},
    "a7228e898b504ed3a34ef9e136621f40":{
      "scriptId":"u100"},
    "2b9e53cd237845bd9cb3d6a8c5fbd995":{
      "scriptId":"u101"},
    "42fafc80595d454fb6bde974e6303d53":{
      "scriptId":"u102"},
    "d0c09e09ebbe4cd4943f756b205029a3":{
      "scriptId":"u103"},
    "3875b95a5f8043779727104462ff7dbd":{
      "scriptId":"u104"},
    "52eb38ef3c56467eb2a0100524b788c6":{
      "scriptId":"u105"}}});