$axure.loadCurrentPage({
  "url":"查看数据-外部存款数据.html",
  "generationDate":new Date(1661406631572.72),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"2e95f8c0726140ebab1bcbaa7ceef198",
    "type":"Axure:Page",
    "name":"查看数据-外部存款数据",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"838e0d9e555e40519856271b46579fe1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":-8,
              "y":94},
            "size":{
              "width":1178,
              "height":556}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"24a7e020d79d47169034d2e6a7b49e67",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":-8,
                  "y":94},
                "size":{
                  "width":1178,
                  "height":556}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/查看数据-香港公司/u0.png"}},
{
          "id":"848179f3481241fe9ae0aba57b52033c",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":27,
              "y":94},
            "size":{
              "width":97,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8f905ce22942409d88c126724657648a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":27,
                  "y":94},
                "size":{
                  "width":97,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"14e0bf6a93e64983b641bfc17385c1c0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":34,
              "y":164},
            "size":{
              "width":112,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"73f16647ffb845fc810e462dc15d7790",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":34,
                  "y":164},
                "size":{
                  "width":112,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"682c82cebf934c249d4c61c26f1cb052",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "disabled":true,
          "visible":true,
          "style":{
            "location":{
              "x":146,
              "y":164.5},
            "size":{
              "width":120,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"e50d631b6fd04791b674e1c1d3ba3830",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":34,
              "y":218},
            "size":{
              "width":126,
              "height":52}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"955d62b397594e31931cfbeb6bb10e38",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "size":{
                  "width":126,
                  "height":52}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"0de7f6d8933d4e3b9a884848d3c58d2b",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"11px",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFF0000,
                      "opacity":1},
                    "size":{
                      "width":126,
                      "height":52}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/查看数据-往来客户账-损益/u8.png"}}]},
{
          "id":"5e1d9ada7fed46dba7919a1db8e62357",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":302,
              "y":136},
            "size":{
              "width":54,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e1a8aa2bec7647bc8ce8799342eb70da",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":302,
                  "y":136},
                "size":{
                  "width":54,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"638536f5876b46b3ab42f2f1620578d1",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "disabled":true,
          "visible":true,
          "style":{
            "location":{
              "x":398,
              "y":132.5},
            "size":{
              "width":120,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"59ade5a89b384360bc4589d1deb8cad0",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":146,
              "y":132.5},
            "size":{
              "width":120,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"87d4972dd0324bf081f27baa89987810",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":34,
              "y":138},
            "size":{
              "width":86,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"524adc81647b49b687c2eb277d4b90fc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":34,
                  "y":138},
                "size":{
                  "width":86,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7628074c51704a4f8e79b98af7bad292",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":362,
              "y":583},
            "size":{
              "width":508,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9d5ba9f3ec6445f69147aefeed62c8fd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":362,
                  "y":583},
                "size":{
                  "width":508,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/余额_收入详情/u73.png"}},
{
          "id":"9823c2fd75634c248a33ad460214f2de",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":1200,
              "y":383},
            "size":{
              "width":166,
              "height":48}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1b22c27bd84342048b8ce606897181ad",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1200,
                  "y":383},
                "size":{
                  "width":166,
                  "height":48}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5cf6c04af0f74924ae4d91c51f710b33",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":34,
              "y":270},
            "size":{
              "width":600,
              "height":116}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"eb5733a8ee5a4b7f8680028cf1c4a6c1",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "size":{
                  "width":100,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"01b4a4d3261c4a34ac5359528e203d6d",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":100,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/客户管理-业务数据展示/u20.png"}},
{
              "id":"eafef30b1bec4a51885d9a478146e2f7",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":36},
                "size":{
                  "width":100,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"7570d0ce81d1496ba9d058d75de5d36d",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":36},
                    "size":{
                      "width":100,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/客户管理-业务数据展示/u30.png"}},
{
              "id":"d959868574b248ba80606dfafed803fa",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":56},
                "size":{
                  "width":100,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"c4e13917928d4a6c898fd1a01b86d5cc",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":56},
                    "size":{
                      "width":100,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/客户管理-业务数据展示/u30.png"}},
{
              "id":"a740e4fd638548398cbddf74d89963e8",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":76},
                "size":{
                  "width":100,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"ba2272616cbc40e9ad69ad1bf04da283",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":76},
                    "size":{
                      "width":100,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/客户管理-业务数据展示/u30.png"}},
{
              "id":"21f46bd3ea7a4deab1d9ccbf084d164d",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":96},
                "size":{
                  "width":100,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"04047474f2e14a58a56fe793fcea5a20",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":96},
                    "size":{
                      "width":100,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/客户管理-业务数据展示/u60.png"}},
{
              "id":"2ff2ba3a7a8d43debe921667bd154a15",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":100,
                  "y":0},
                "size":{
                  "width":100,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"5a70d71d76e948f4a65886abe1ebe66f",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":100,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/客户管理-业务数据展示/u20.png"}},
{
              "id":"7f28cb1bc6f744e08c41779a2d77721f",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":100,
                  "y":36},
                "size":{
                  "width":100,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"3b1e62a4ba8649cc8fe2ca26fa251ebd",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":100,
                      "y":36},
                    "size":{
                      "width":100,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/客户管理-业务数据展示/u30.png"}},
{
              "id":"18b258d7a0b644e39cde1d061aa1cde7",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":100,
                  "y":56},
                "size":{
                  "width":100,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"8da054362acd4b20b0aee7a80878bd25",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":100,
                      "y":56},
                    "size":{
                      "width":100,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/客户管理-业务数据展示/u30.png"}},
{
              "id":"2e7eebdad17b408c81acb653bd4a81b8",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":100,
                  "y":76},
                "size":{
                  "width":100,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"afec24b9ec474260bc46803b75851f54",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":100,
                      "y":76},
                    "size":{
                      "width":100,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/客户管理-业务数据展示/u30.png"}},
{
              "id":"e73d21333b564e8cbf779e3e5ca52683",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":100,
                  "y":96},
                "size":{
                  "width":100,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"93f40189d5df41a3bf62b76f5d11a7ca",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":100,
                      "y":96},
                    "size":{
                      "width":100,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/客户管理-业务数据展示/u60.png"}},
{
              "id":"ad3b4872c7074c2181fe22fb9453e3a3",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":200,
                  "y":0},
                "size":{
                  "width":100,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"fe978f228bc94607b5d9ca3f3c0cae45",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":200,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/客户管理-业务数据展示/u20.png"}},
{
              "id":"a444db4c765647198594e90fa5adfc51",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":200,
                  "y":36},
                "size":{
                  "width":100,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"0460bb92f08341ccaa572e9b077fba6f",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":200,
                      "y":36},
                    "size":{
                      "width":100,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/客户管理-业务数据展示/u30.png"}},
{
              "id":"1abfa133578648b581b97f97f8091b6f",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":200,
                  "y":56},
                "size":{
                  "width":100,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"2452a3da1c29496dba3b4769c1797a99",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":200,
                      "y":56},
                    "size":{
                      "width":100,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/客户管理-业务数据展示/u30.png"}},
{
              "id":"5eb5c1f2fec0499f82d9646e20540e9a",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":200,
                  "y":76},
                "size":{
                  "width":100,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"3f4df7873baa480484eb2c1c113d969c",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":200,
                      "y":76},
                    "size":{
                      "width":100,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/客户管理-业务数据展示/u30.png"}},
{
              "id":"7c654d70c162437f8eddf5556c4996e3",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":200,
                  "y":96},
                "size":{
                  "width":100,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"2a258ac7afd443d289c1f88b649f3bea",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":200,
                      "y":96},
                    "size":{
                      "width":100,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/客户管理-业务数据展示/u60.png"}},
{
              "id":"a64b12a6bc464d7698bb010423f9adbb",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":300,
                  "y":0},
                "size":{
                  "width":100,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"7e79eac6eb2049f09508ba5bed501ed7",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":300,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/客户管理-业务数据展示/u20.png"}},
{
              "id":"5672b4aa25b54294b0d228f3dc2c3f57",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":300,
                  "y":36},
                "size":{
                  "width":100,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"0f0a4d93ba1b4ff3aeabc23e28adaaae",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":300,
                      "y":36},
                    "size":{
                      "width":100,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/客户管理-业务数据展示/u30.png"}},
{
              "id":"5c0e42fa4c494966af33ea98d1c05962",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":300,
                  "y":56},
                "size":{
                  "width":100,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"8825f6145e8c495685b5e2f25ddf79ea",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":300,
                      "y":56},
                    "size":{
                      "width":100,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/客户管理-业务数据展示/u30.png"}},
{
              "id":"0cbe47adbc9f45669d4aadd2007ba8a8",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":300,
                  "y":76},
                "size":{
                  "width":100,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"48d3fd1738ee4513879b0055ee829c14",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":300,
                      "y":76},
                    "size":{
                      "width":100,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/客户管理-业务数据展示/u30.png"}},
{
              "id":"61ca47e3c7a94a3aa140c53bff29d134",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":300,
                  "y":96},
                "size":{
                  "width":100,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"fe0bcaabae434c139fac3a9b125c7c8e",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":300,
                      "y":96},
                    "size":{
                      "width":100,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/客户管理-业务数据展示/u60.png"}},
{
              "id":"b8a34643f2b04979bd8ad911094ec7f9",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":400,
                  "y":0},
                "size":{
                  "width":100,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"a1b0e17fa1154e2f8780169425928060",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":400,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/客户管理-业务数据展示/u20.png"}},
{
              "id":"48a8eca327fb4d6388023683c632fd31",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":400,
                  "y":36},
                "size":{
                  "width":100,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"0619f7ad54314a27b4c33ac3f78cd1f1",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":400,
                      "y":36},
                    "size":{
                      "width":100,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/客户管理-业务数据展示/u30.png"}},
{
              "id":"3e7294203c8e4a188982b1f60985ff15",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":400,
                  "y":56},
                "size":{
                  "width":100,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"828977da21974a1ba5e054374722d547",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":400,
                      "y":56},
                    "size":{
                      "width":100,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/客户管理-业务数据展示/u30.png"}},
{
              "id":"264717c4c5fe4bd69b293b85456948bf",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":400,
                  "y":76},
                "size":{
                  "width":100,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"235ba893d378481d8d907ee38a286b33",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":400,
                      "y":76},
                    "size":{
                      "width":100,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/客户管理-业务数据展示/u30.png"}},
{
              "id":"36f9bd1d02234626a286b7adcdca8250",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":400,
                  "y":96},
                "size":{
                  "width":100,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"167e722319864e148732eedc652be7af",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":400,
                      "y":96},
                    "size":{
                      "width":100,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/客户管理-业务数据展示/u60.png"}},
{
              "id":"43750f4a853b4f6d954f05fc998fe2dd",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":500,
                  "y":0},
                "size":{
                  "width":100,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"8b06bd73e02c423da75ee12850255a65",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":500,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/客户管理-业务数据展示/u28.png"}},
{
              "id":"5cc74ff5470f40a08f068ba63b2d7477",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":500,
                  "y":36},
                "size":{
                  "width":100,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"7bb5167f795540708e3814457bed5c42",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":500,
                      "y":36},
                    "size":{
                      "width":100,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/客户管理-业务数据展示/u38.png"}},
{
              "id":"5dd450a324994b09ad65721344f18195",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":500,
                  "y":56},
                "size":{
                  "width":100,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"ff51e0d23d19439e91ed2d40348bb4c2",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":500,
                      "y":56},
                    "size":{
                      "width":100,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/客户管理-业务数据展示/u38.png"}},
{
              "id":"b7941eedb0ec4738a5e3914c2ee30ca2",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":500,
                  "y":76},
                "size":{
                  "width":100,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"4df75c272b374ffab33cc4aca46135b9",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":500,
                      "y":76},
                    "size":{
                      "width":100,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/客户管理-业务数据展示/u38.png"}},
{
              "id":"39f1d3b257fa4dd4b93337c62eaf9d8d",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":500,
                  "y":96},
                "size":{
                  "width":100,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"d532ac2bbd40407fa72f26af3c813dc0",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":500,
                      "y":96},
                    "size":{
                      "width":100,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/客户管理-业务数据展示/u68.png"}}]}]}},
  "masters":{
},
  "objectPaths":{
    "838e0d9e555e40519856271b46579fe1":{
      "scriptId":"u0"},
    "24a7e020d79d47169034d2e6a7b49e67":{
      "scriptId":"u1"},
    "848179f3481241fe9ae0aba57b52033c":{
      "scriptId":"u2"},
    "8f905ce22942409d88c126724657648a":{
      "scriptId":"u3"},
    "14e0bf6a93e64983b641bfc17385c1c0":{
      "scriptId":"u4"},
    "73f16647ffb845fc810e462dc15d7790":{
      "scriptId":"u5"},
    "682c82cebf934c249d4c61c26f1cb052":{
      "scriptId":"u6"},
    "e50d631b6fd04791b674e1c1d3ba3830":{
      "scriptId":"u7"},
    "955d62b397594e31931cfbeb6bb10e38":{
      "scriptId":"u8"},
    "0de7f6d8933d4e3b9a884848d3c58d2b":{
      "scriptId":"u9"},
    "5e1d9ada7fed46dba7919a1db8e62357":{
      "scriptId":"u10"},
    "e1a8aa2bec7647bc8ce8799342eb70da":{
      "scriptId":"u11"},
    "638536f5876b46b3ab42f2f1620578d1":{
      "scriptId":"u12"},
    "59ade5a89b384360bc4589d1deb8cad0":{
      "scriptId":"u13"},
    "87d4972dd0324bf081f27baa89987810":{
      "scriptId":"u14"},
    "524adc81647b49b687c2eb277d4b90fc":{
      "scriptId":"u15"},
    "7628074c51704a4f8e79b98af7bad292":{
      "scriptId":"u16"},
    "9d5ba9f3ec6445f69147aefeed62c8fd":{
      "scriptId":"u17"},
    "9823c2fd75634c248a33ad460214f2de":{
      "scriptId":"u18"},
    "1b22c27bd84342048b8ce606897181ad":{
      "scriptId":"u19"},
    "5cf6c04af0f74924ae4d91c51f710b33":{
      "scriptId":"u20"},
    "eb5733a8ee5a4b7f8680028cf1c4a6c1":{
      "scriptId":"u21"},
    "01b4a4d3261c4a34ac5359528e203d6d":{
      "scriptId":"u22"},
    "2ff2ba3a7a8d43debe921667bd154a15":{
      "scriptId":"u23"},
    "5a70d71d76e948f4a65886abe1ebe66f":{
      "scriptId":"u24"},
    "ad3b4872c7074c2181fe22fb9453e3a3":{
      "scriptId":"u25"},
    "fe978f228bc94607b5d9ca3f3c0cae45":{
      "scriptId":"u26"},
    "a64b12a6bc464d7698bb010423f9adbb":{
      "scriptId":"u27"},
    "7e79eac6eb2049f09508ba5bed501ed7":{
      "scriptId":"u28"},
    "b8a34643f2b04979bd8ad911094ec7f9":{
      "scriptId":"u29"},
    "a1b0e17fa1154e2f8780169425928060":{
      "scriptId":"u30"},
    "43750f4a853b4f6d954f05fc998fe2dd":{
      "scriptId":"u31"},
    "8b06bd73e02c423da75ee12850255a65":{
      "scriptId":"u32"},
    "eafef30b1bec4a51885d9a478146e2f7":{
      "scriptId":"u33"},
    "7570d0ce81d1496ba9d058d75de5d36d":{
      "scriptId":"u34"},
    "7f28cb1bc6f744e08c41779a2d77721f":{
      "scriptId":"u35"},
    "3b1e62a4ba8649cc8fe2ca26fa251ebd":{
      "scriptId":"u36"},
    "a444db4c765647198594e90fa5adfc51":{
      "scriptId":"u37"},
    "0460bb92f08341ccaa572e9b077fba6f":{
      "scriptId":"u38"},
    "5672b4aa25b54294b0d228f3dc2c3f57":{
      "scriptId":"u39"},
    "0f0a4d93ba1b4ff3aeabc23e28adaaae":{
      "scriptId":"u40"},
    "48a8eca327fb4d6388023683c632fd31":{
      "scriptId":"u41"},
    "0619f7ad54314a27b4c33ac3f78cd1f1":{
      "scriptId":"u42"},
    "5cc74ff5470f40a08f068ba63b2d7477":{
      "scriptId":"u43"},
    "7bb5167f795540708e3814457bed5c42":{
      "scriptId":"u44"},
    "d959868574b248ba80606dfafed803fa":{
      "scriptId":"u45"},
    "c4e13917928d4a6c898fd1a01b86d5cc":{
      "scriptId":"u46"},
    "18b258d7a0b644e39cde1d061aa1cde7":{
      "scriptId":"u47"},
    "8da054362acd4b20b0aee7a80878bd25":{
      "scriptId":"u48"},
    "1abfa133578648b581b97f97f8091b6f":{
      "scriptId":"u49"},
    "2452a3da1c29496dba3b4769c1797a99":{
      "scriptId":"u50"},
    "5c0e42fa4c494966af33ea98d1c05962":{
      "scriptId":"u51"},
    "8825f6145e8c495685b5e2f25ddf79ea":{
      "scriptId":"u52"},
    "3e7294203c8e4a188982b1f60985ff15":{
      "scriptId":"u53"},
    "828977da21974a1ba5e054374722d547":{
      "scriptId":"u54"},
    "5dd450a324994b09ad65721344f18195":{
      "scriptId":"u55"},
    "ff51e0d23d19439e91ed2d40348bb4c2":{
      "scriptId":"u56"},
    "a740e4fd638548398cbddf74d89963e8":{
      "scriptId":"u57"},
    "ba2272616cbc40e9ad69ad1bf04da283":{
      "scriptId":"u58"},
    "2e7eebdad17b408c81acb653bd4a81b8":{
      "scriptId":"u59"},
    "afec24b9ec474260bc46803b75851f54":{
      "scriptId":"u60"},
    "5eb5c1f2fec0499f82d9646e20540e9a":{
      "scriptId":"u61"},
    "3f4df7873baa480484eb2c1c113d969c":{
      "scriptId":"u62"},
    "0cbe47adbc9f45669d4aadd2007ba8a8":{
      "scriptId":"u63"},
    "48d3fd1738ee4513879b0055ee829c14":{
      "scriptId":"u64"},
    "264717c4c5fe4bd69b293b85456948bf":{
      "scriptId":"u65"},
    "235ba893d378481d8d907ee38a286b33":{
      "scriptId":"u66"},
    "b7941eedb0ec4738a5e3914c2ee30ca2":{
      "scriptId":"u67"},
    "4df75c272b374ffab33cc4aca46135b9":{
      "scriptId":"u68"},
    "21f46bd3ea7a4deab1d9ccbf084d164d":{
      "scriptId":"u69"},
    "04047474f2e14a58a56fe793fcea5a20":{
      "scriptId":"u70"},
    "e73d21333b564e8cbf779e3e5ca52683":{
      "scriptId":"u71"},
    "93f40189d5df41a3bf62b76f5d11a7ca":{
      "scriptId":"u72"},
    "7c654d70c162437f8eddf5556c4996e3":{
      "scriptId":"u73"},
    "2a258ac7afd443d289c1f88b649f3bea":{
      "scriptId":"u74"},
    "61ca47e3c7a94a3aa140c53bff29d134":{
      "scriptId":"u75"},
    "fe0bcaabae434c139fac3a9b125c7c8e":{
      "scriptId":"u76"},
    "36f9bd1d02234626a286b7adcdca8250":{
      "scriptId":"u77"},
    "167e722319864e148732eedc652be7af":{
      "scriptId":"u78"},
    "39f1d3b257fa4dd4b93337c62eaf9d8d":{
      "scriptId":"u79"},
    "d532ac2bbd40407fa72f26af3c813dc0":{
      "scriptId":"u80"}}});