$axure.loadCurrentPage({
  "url":"接口对接.html",
  "generationDate":new Date(1661326032833.89),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"c38003725c854219a48fd1893bd4fd47",
    "type":"Axure:Page",
    "name":"接口对接",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"51909b6a323e482780a217be80e47984",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":33,
              "y":229.999984741211},
            "size":{
              "width":193,
              "height":38}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"430173bf6adb4272b38556f88b12f2af",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":33,
                  "y":229.999984741211},
                "size":{
                  "width":193,
                  "height":38}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ab99c605ce5e4354a1c3805d3c45a058",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":290},
            "size":{
              "width":290,
              "height":76}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8e9eaf42e2834e3eb323518cab3427f6",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "size":{
                  "width":145,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"9a5a2affa9b34f9a89419030d78a7e98",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":145,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/接口对接/u3.png"}},
{
              "id":"971de96dd828463d8ec8269d10fd095e",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":20},
                "size":{
                  "width":145,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"199a779ecaa84025b920a2e7a61aa6ba",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":20},
                    "size":{
                      "width":145,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/接口对接/u3.png"}},
{
              "id":"c8688787894f4d9ab50b5c1395e6e2b7",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":40},
                "size":{
                  "width":145,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"81e887b36c5c4264b0b5959c271f4781",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":40},
                    "size":{
                      "width":145,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/接口对接/u11.png"}},
{
              "id":"d8fa7a3ce0b047c3b67bca86304bf59b",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":145,
                  "y":0},
                "size":{
                  "width":145,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"880a5a6885174c81aed0f7e60356e172",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":145,
                      "y":0},
                    "size":{
                      "width":145,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/接口对接/u5.png"}},
{
              "id":"38fc630402864d9d985dc315c9b502d8",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":145,
                  "y":20},
                "size":{
                  "width":145,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"5cb321acb2db4f83b40d6c29ac044e3e",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":145,
                      "y":20},
                    "size":{
                      "width":145,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/接口对接/u5.png"}},
{
              "id":"0a84719ac804426b91219c465aa9cfb5",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":145,
                  "y":40},
                "size":{
                  "width":145,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"b8f75dcab48142bebef5afc21dfdd8ec",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":145,
                      "y":40},
                    "size":{
                      "width":145,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/接口对接/u13.png"}}]},
{
          "id":"c647a40409c943d5a097933a4a412327",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":50,
              "y":23},
            "size":{
              "width":405,
              "height":198}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7abc3e0118a4419b9626dc70233f572f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":50,
                  "y":23},
                "size":{
                  "width":405,
                  "height":198}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/接口对接/u15.png"}},
{
          "id":"70efaf059f604ca19806b6dc3d6cf72e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":366,
              "y":246},
            "size":{
              "width":324,
              "height":114}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a3584acf4d1c4749a1e15f8eb4758a9f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":366,
                  "y":246},
                "size":{
                  "width":324,
                  "height":114}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b0939a261c514f62aa0655da09fd9d31",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":376},
            "size":{
              "width":289,
              "height":38}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5aeb94f0af1b4b15909057ae77aa6ff9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":40,
                  "y":376},
                "size":{
                  "width":289,
                  "height":38}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8302de25863f44ba9de0e6eac9a4e34e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":40.0000305175781,
              "y":424},
            "size":{
              "width":637,
              "height":483}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dc6b8da36b864aa7b76d8ec45d41a9c2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":40.0000305175781,
                  "y":424},
                "size":{
                  "width":637,
                  "height":483}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/接口对接/u21.jpg"}},
{
          "id":"0f59d4a778c94193a62c870832cf439e",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":952},
            "size":{
              "width":240,
              "height":38}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a69b007f207647dead5796d291c24c62",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":40,
                  "y":952},
                "size":{
                  "width":240,
                  "height":38}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9ea651bbd2674b299346c31dff2bfad8",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":50,
              "y":1015},
            "size":{
              "width":1073,
              "height":105}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"32c165052fca41ba9920c07f71c461df",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":50,
                  "y":1015},
                "size":{
                  "width":1073,
                  "height":105}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/接口对接/u25.png"}},
{
          "id":"91f10c6b04654944901e4c9cb63d793b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":436,
              "y":400},
            "size":{
              "width":324,
              "height":114}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7f904d0896ce41a085e874fddf33b761",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":436,
                  "y":400},
                "size":{
                  "width":324,
                  "height":114}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "51909b6a323e482780a217be80e47984":{
      "scriptId":"u0"},
    "430173bf6adb4272b38556f88b12f2af":{
      "scriptId":"u1"},
    "ab99c605ce5e4354a1c3805d3c45a058":{
      "scriptId":"u2"},
    "8e9eaf42e2834e3eb323518cab3427f6":{
      "scriptId":"u3"},
    "9a5a2affa9b34f9a89419030d78a7e98":{
      "scriptId":"u4"},
    "d8fa7a3ce0b047c3b67bca86304bf59b":{
      "scriptId":"u5"},
    "880a5a6885174c81aed0f7e60356e172":{
      "scriptId":"u6"},
    "971de96dd828463d8ec8269d10fd095e":{
      "scriptId":"u7"},
    "199a779ecaa84025b920a2e7a61aa6ba":{
      "scriptId":"u8"},
    "38fc630402864d9d985dc315c9b502d8":{
      "scriptId":"u9"},
    "5cb321acb2db4f83b40d6c29ac044e3e":{
      "scriptId":"u10"},
    "c8688787894f4d9ab50b5c1395e6e2b7":{
      "scriptId":"u11"},
    "81e887b36c5c4264b0b5959c271f4781":{
      "scriptId":"u12"},
    "0a84719ac804426b91219c465aa9cfb5":{
      "scriptId":"u13"},
    "b8f75dcab48142bebef5afc21dfdd8ec":{
      "scriptId":"u14"},
    "c647a40409c943d5a097933a4a412327":{
      "scriptId":"u15"},
    "7abc3e0118a4419b9626dc70233f572f":{
      "scriptId":"u16"},
    "70efaf059f604ca19806b6dc3d6cf72e":{
      "scriptId":"u17"},
    "a3584acf4d1c4749a1e15f8eb4758a9f":{
      "scriptId":"u18"},
    "b0939a261c514f62aa0655da09fd9d31":{
      "scriptId":"u19"},
    "5aeb94f0af1b4b15909057ae77aa6ff9":{
      "scriptId":"u20"},
    "8302de25863f44ba9de0e6eac9a4e34e":{
      "scriptId":"u21"},
    "dc6b8da36b864aa7b76d8ec45d41a9c2":{
      "scriptId":"u22"},
    "0f59d4a778c94193a62c870832cf439e":{
      "scriptId":"u23"},
    "a69b007f207647dead5796d291c24c62":{
      "scriptId":"u24"},
    "9ea651bbd2674b299346c31dff2bfad8":{
      "scriptId":"u25"},
    "32c165052fca41ba9920c07f71c461df":{
      "scriptId":"u26"},
    "91f10c6b04654944901e4c9cb63d793b":{
      "scriptId":"u27"},
    "7f904d0896ce41a085e874fddf33b761":{
      "scriptId":"u28"}}});