$axure.loadCurrentPage({
  "url":"拜访详情列表.html",
  "generationDate":new Date(1662526088424.03),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"b54b0bf7706245029ae7120aa32c3427",
    "type":"Axure:Page",
    "name":"拜访详情列表",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"c0783762a80f4b77b691587543e86af4",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":120,
              "y":50},
            "size":{
              "width":900,
              "height":87}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4310ad6f980248aca02c8db8124a670d",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "size":{
                  "width":100,
                  "height":27}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"1ff53411f83c40499ab709f2bd66dc39",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "size":{
                      "width":100,
                      "height":27}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/拜访详情列表/u1.png"}},
{
              "id":"f94698920e894e909755e4f411b8bd93",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":27},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"02b6adbea6244c7287848d1c9b992ba2",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":27},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/添加模块/u1.png"}},
{
              "id":"b9808cfc89bc41a9b75402fb6c6ce4a2",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":57},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"ed956bd6b0fa48d8a06b0806491d9ab5",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":57},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/编辑模块顺序/u13.png"}},
{
              "id":"a899797afebf4025989463696206a738",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":100,
                  "y":0},
                "size":{
                  "width":100,
                  "height":27}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"45e664d8cba44789937ac9c37d1419aa",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":100,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":27}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/拜访详情列表/u1.png"}},
{
              "id":"dc670ee620df482bbd8d8bbfb7189f42",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":100,
                  "y":27},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"b563471b1b4a461aa0986fd69f8883f6",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":100,
                      "y":27},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/添加模块/u1.png"}},
{
              "id":"4ac2ba758df2432592d898d2e4f25d18",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":100,
                  "y":57},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"6a8047aae5e147529760c7dbd39d12fb",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":100,
                      "y":57},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/编辑模块顺序/u13.png"}},
{
              "id":"cb3835bc2a5f455fb6d3029139719eec",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":200,
                  "y":0},
                "size":{
                  "width":100,
                  "height":27}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"e8725835c4714f3b949a6bc8077803e1",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":200,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":27}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/拜访详情列表/u1.png"}},
{
              "id":"6137c1ce5469448289c51773b39af91a",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":200,
                  "y":27},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"f709d27c04f44c3ba84edc938a23c54c",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":200,
                      "y":27},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/添加模块/u1.png"}},
{
              "id":"72bc4d383a564cb9a7fe6eae2a35d21d",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":200,
                  "y":57},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"0eb3f015f83f4b8a96b6cbbe6f30f627",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":200,
                      "y":57},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/编辑模块顺序/u13.png"}},
{
              "id":"d2b8850dfd854439904b915b8bf41f67",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":300,
                  "y":0},
                "size":{
                  "width":100,
                  "height":27}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"8576d137e5c14e7b9066e5c90cba2135",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":300,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":27}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/拜访详情列表/u1.png"}},
{
              "id":"41a504cc82a44759989b4458e58ab2df",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":300,
                  "y":27},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"429eafe88b38403e81c4cf0a70b7c62b",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":300,
                      "y":27},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/添加模块/u1.png"}},
{
              "id":"441fada940b24f6e85e0a202cf66d950",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":300,
                  "y":57},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"2f287cc999784bb89ef919eeab89a297",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":300,
                      "y":57},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/编辑模块顺序/u13.png"}},
{
              "id":"dd1d1eca1d114e10a56117975cc541bc",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":400,
                  "y":0},
                "size":{
                  "width":100,
                  "height":27}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"bc9ecc5baa064076ba13c229d4d4ae3a",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":400,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":27}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/拜访详情列表/u1.png"}},
{
              "id":"4fb677017e2f453dafbbeb785db4ff44",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":400,
                  "y":27},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"da28a4d3d2334c7fab144cbc9f4b8779",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":400,
                      "y":27},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/添加模块/u1.png"}},
{
              "id":"d4ac67ef72b647ce99ae94fb5abee9f4",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":400,
                  "y":57},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"58930d6240c441f4be93280f4d0c12d1",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":400,
                      "y":57},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/编辑模块顺序/u13.png"}},
{
              "id":"c9bdd532a3344e5bbe68a08e5054a238",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":500,
                  "y":0},
                "size":{
                  "width":100,
                  "height":27}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"398e4a8c3e3e4b2790b4d23f5b2dd111",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":500,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":27}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/拜访详情列表/u1.png"}},
{
              "id":"5bfa80d3c0754e16817cde40c6fd98cf",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":500,
                  "y":27},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"33b6709d57e04a7793811ded173c31a9",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":500,
                      "y":27},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/添加模块/u1.png"}},
{
              "id":"04cb9c8ce55043699abf85d56f4cab9d",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":500,
                  "y":57},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"3acec9c98b14456dba45926135020f47",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":500,
                      "y":57},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/编辑模块顺序/u13.png"}},
{
              "id":"a4ab26c656d84955b67b9fc81315de33",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":700,
                  "y":0},
                "size":{
                  "width":100,
                  "height":27}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"8df04828de574eb880794edcbf403232",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":700,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":27}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/拜访详情列表/u1.png"}},
{
              "id":"f63ae80bed5b4492bcf50d4ea30ec7e6",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":700,
                  "y":27},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"e7bfbf5c9e474122ae8331b23f7b699e",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":700,
                      "y":27},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/添加模块/u1.png"}},
{
              "id":"a3d8a209dd6e4117b38a36fbbba5b7a1",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":700,
                  "y":57},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"c425b0557f16454ead14c61357e43b10",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":700,
                      "y":57},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/编辑模块顺序/u13.png"}},
{
              "id":"85d901fbd3fd4502a5a22665679ed156",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":600,
                  "y":0},
                "size":{
                  "width":100,
                  "height":27}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"268ce8a3df134b9b941d97ccb2977295",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":600,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":27}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/拜访详情列表/u1.png"}},
{
              "id":"1b5161d113a34a3fbd856bc1d9cf46ff",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":600,
                  "y":27},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"35b93644e1c64c6784c8da9f0bcb2fcf",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":600,
                      "y":27},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/添加模块/u1.png"}},
{
              "id":"088dd0810f354b42b9491d9521491216",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":600,
                  "y":57},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"df80d4a88762462d86ed155333b1f736",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":600,
                      "y":57},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/编辑模块顺序/u13.png"}},
{
              "id":"8cd8f4a9d3e04e8c8ac26cb25d7305d0",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":800,
                  "y":0},
                "size":{
                  "width":100,
                  "height":27}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"04f3d7d5001848a8afb5f01ed73c716e",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":800,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":27}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/拜访详情列表/u17.png"}},
{
              "id":"bf2a7e14f65f4f4f97304db39816f8b6",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "underline":true,
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":800,
                  "y":27},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"2e4cd52eec2647dc8eec84c78759ad3d",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "underline":true,
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0000FF,
                      "opacity":1},
                    "location":{
                      "x":800,
                      "y":27},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/添加模块/u5.png"}},
{
              "id":"06dd6623320d4b3f9be3024c52326809",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":800,
                  "y":57},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"c92d873128704d8299dde364357f42fa",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":800,
                      "y":57},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/编辑模块顺序/u15.png"}}]},
{
          "id":"0ad43501b49e488792805dfb1463dfb3",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":502.000030517578,
              "y":147},
            "size":{
              "width":508,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ac510e225d9640eb8bc9521f958969ea",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":502.000030517578,
                  "y":147},
                "size":{
                  "width":508,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/客户管理-业务数据展示/u559.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "c0783762a80f4b77b691587543e86af4":{
      "scriptId":"u0"},
    "4310ad6f980248aca02c8db8124a670d":{
      "scriptId":"u1"},
    "1ff53411f83c40499ab709f2bd66dc39":{
      "scriptId":"u2"},
    "a899797afebf4025989463696206a738":{
      "scriptId":"u3"},
    "45e664d8cba44789937ac9c37d1419aa":{
      "scriptId":"u4"},
    "cb3835bc2a5f455fb6d3029139719eec":{
      "scriptId":"u5"},
    "e8725835c4714f3b949a6bc8077803e1":{
      "scriptId":"u6"},
    "d2b8850dfd854439904b915b8bf41f67":{
      "scriptId":"u7"},
    "8576d137e5c14e7b9066e5c90cba2135":{
      "scriptId":"u8"},
    "dd1d1eca1d114e10a56117975cc541bc":{
      "scriptId":"u9"},
    "bc9ecc5baa064076ba13c229d4d4ae3a":{
      "scriptId":"u10"},
    "c9bdd532a3344e5bbe68a08e5054a238":{
      "scriptId":"u11"},
    "398e4a8c3e3e4b2790b4d23f5b2dd111":{
      "scriptId":"u12"},
    "85d901fbd3fd4502a5a22665679ed156":{
      "scriptId":"u13"},
    "268ce8a3df134b9b941d97ccb2977295":{
      "scriptId":"u14"},
    "a4ab26c656d84955b67b9fc81315de33":{
      "scriptId":"u15"},
    "8df04828de574eb880794edcbf403232":{
      "scriptId":"u16"},
    "8cd8f4a9d3e04e8c8ac26cb25d7305d0":{
      "scriptId":"u17"},
    "04f3d7d5001848a8afb5f01ed73c716e":{
      "scriptId":"u18"},
    "f94698920e894e909755e4f411b8bd93":{
      "scriptId":"u19"},
    "02b6adbea6244c7287848d1c9b992ba2":{
      "scriptId":"u20"},
    "dc670ee620df482bbd8d8bbfb7189f42":{
      "scriptId":"u21"},
    "b563471b1b4a461aa0986fd69f8883f6":{
      "scriptId":"u22"},
    "6137c1ce5469448289c51773b39af91a":{
      "scriptId":"u23"},
    "f709d27c04f44c3ba84edc938a23c54c":{
      "scriptId":"u24"},
    "41a504cc82a44759989b4458e58ab2df":{
      "scriptId":"u25"},
    "429eafe88b38403e81c4cf0a70b7c62b":{
      "scriptId":"u26"},
    "4fb677017e2f453dafbbeb785db4ff44":{
      "scriptId":"u27"},
    "da28a4d3d2334c7fab144cbc9f4b8779":{
      "scriptId":"u28"},
    "5bfa80d3c0754e16817cde40c6fd98cf":{
      "scriptId":"u29"},
    "33b6709d57e04a7793811ded173c31a9":{
      "scriptId":"u30"},
    "1b5161d113a34a3fbd856bc1d9cf46ff":{
      "scriptId":"u31"},
    "35b93644e1c64c6784c8da9f0bcb2fcf":{
      "scriptId":"u32"},
    "f63ae80bed5b4492bcf50d4ea30ec7e6":{
      "scriptId":"u33"},
    "e7bfbf5c9e474122ae8331b23f7b699e":{
      "scriptId":"u34"},
    "bf2a7e14f65f4f4f97304db39816f8b6":{
      "scriptId":"u35"},
    "2e4cd52eec2647dc8eec84c78759ad3d":{
      "scriptId":"u36"},
    "b9808cfc89bc41a9b75402fb6c6ce4a2":{
      "scriptId":"u37"},
    "ed956bd6b0fa48d8a06b0806491d9ab5":{
      "scriptId":"u38"},
    "4ac2ba758df2432592d898d2e4f25d18":{
      "scriptId":"u39"},
    "6a8047aae5e147529760c7dbd39d12fb":{
      "scriptId":"u40"},
    "72bc4d383a564cb9a7fe6eae2a35d21d":{
      "scriptId":"u41"},
    "0eb3f015f83f4b8a96b6cbbe6f30f627":{
      "scriptId":"u42"},
    "441fada940b24f6e85e0a202cf66d950":{
      "scriptId":"u43"},
    "2f287cc999784bb89ef919eeab89a297":{
      "scriptId":"u44"},
    "d4ac67ef72b647ce99ae94fb5abee9f4":{
      "scriptId":"u45"},
    "58930d6240c441f4be93280f4d0c12d1":{
      "scriptId":"u46"},
    "04cb9c8ce55043699abf85d56f4cab9d":{
      "scriptId":"u47"},
    "3acec9c98b14456dba45926135020f47":{
      "scriptId":"u48"},
    "088dd0810f354b42b9491d9521491216":{
      "scriptId":"u49"},
    "df80d4a88762462d86ed155333b1f736":{
      "scriptId":"u50"},
    "a3d8a209dd6e4117b38a36fbbba5b7a1":{
      "scriptId":"u51"},
    "c425b0557f16454ead14c61357e43b10":{
      "scriptId":"u52"},
    "06dd6623320d4b3f9be3024c52326809":{
      "scriptId":"u53"},
    "c92d873128704d8299dde364357f42fa":{
      "scriptId":"u54"},
    "0ad43501b49e488792805dfb1463dfb3":{
      "scriptId":"u55"},
    "ac510e225d9640eb8bc9521f958969ea":{
      "scriptId":"u56"}}});