$axure.loadCurrentPage({
  "url":"查看数据-融资计划.html",
  "generationDate":new Date(1661498371055.19),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"039872403d56432c830406f5e3eb13a7",
    "type":"Axure:Page",
    "name":"查看数据-融资计划",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"838e0d9e555e40519856271b46579fe1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":-8,
              "y":94},
            "size":{
              "width":1178,
              "height":556}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"24a7e020d79d47169034d2e6a7b49e67",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":-8,
                  "y":94},
                "size":{
                  "width":1178,
                  "height":556}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/查看数据-香港公司/u0.png"}},
{
          "id":"848179f3481241fe9ae0aba57b52033c",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":27,
              "y":94},
            "size":{
              "width":97,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8f905ce22942409d88c126724657648a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":27,
                  "y":94},
                "size":{
                  "width":97,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"14e0bf6a93e64983b641bfc17385c1c0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":34,
              "y":164},
            "size":{
              "width":112,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"73f16647ffb845fc810e462dc15d7790",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":34,
                  "y":164},
                "size":{
                  "width":112,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"682c82cebf934c249d4c61c26f1cb052",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "disabled":true,
          "visible":true,
          "style":{
            "location":{
              "x":146,
              "y":164.5},
            "size":{
              "width":120,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"e50d631b6fd04791b674e1c1d3ba3830",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":34,
              "y":196},
            "size":{
              "width":126,
              "height":52}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"955d62b397594e31931cfbeb6bb10e38",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "size":{
                  "width":126,
                  "height":52}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"0de7f6d8933d4e3b9a884848d3c58d2b",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFF0000,
                      "opacity":1},
                    "size":{
                      "width":126,
                      "height":52}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/查看数据-往来客户账-损益/u8.png"}}]},
{
          "id":"5e1d9ada7fed46dba7919a1db8e62357",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":302,
              "y":136},
            "size":{
              "width":54,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e1a8aa2bec7647bc8ce8799342eb70da",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":302,
                  "y":136},
                "size":{
                  "width":54,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"638536f5876b46b3ab42f2f1620578d1",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "disabled":true,
          "visible":true,
          "style":{
            "location":{
              "x":398,
              "y":132.5},
            "size":{
              "width":120,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"59ade5a89b384360bc4589d1deb8cad0",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":146,
              "y":132.5},
            "size":{
              "width":120,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"87d4972dd0324bf081f27baa89987810",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":34,
              "y":138},
            "size":{
              "width":86,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"524adc81647b49b687c2eb277d4b90fc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":34,
                  "y":138},
                "size":{
                  "width":86,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7628074c51704a4f8e79b98af7bad292",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":362,
              "y":583},
            "size":{
              "width":508,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9d5ba9f3ec6445f69147aefeed62c8fd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":362,
                  "y":583},
                "size":{
                  "width":508,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/客户管理-业务数据展示/u614.png"}},
{
          "id":"9823c2fd75634c248a33ad460214f2de",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":1200,
              "y":383},
            "size":{
              "width":166,
              "height":48}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1b22c27bd84342048b8ce606897181ad",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1200,
                  "y":383},
                "size":{
                  "width":166,
                  "height":48}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f2c8fa80a87c4647b9e22c896af9fba9",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":34,
              "y":248},
            "size":{
              "width":500,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"08b907f806824b1e8bcc164304d596ff",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "size":{
                  "width":100,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"80fb869975614a3dbb177b5810387de3",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":100,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/客户管理-业务数据展示/u30.png"}},
{
              "id":"47900837c58e4de49f17e0e00909a275",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":20},
                "size":{
                  "width":100,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"19c6d71292b74da6ad4172583e955e75",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":20},
                    "size":{
                      "width":100,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/客户管理-业务数据展示/u30.png"}},
{
              "id":"c3ad8eef1db2499badeb91eb79de604a",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":40},
                "size":{
                  "width":100,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"dd9a03160b3546a2a79379268863fbf3",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":40},
                    "size":{
                      "width":100,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/客户管理-业务数据展示/u30.png"}},
{
              "id":"1db03dfa5a654121888392cdcbbf69a9",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":60},
                "size":{
                  "width":100,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"2beddcc87d7e487ca2916b6b8c7b62b7",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":60},
                    "size":{
                      "width":100,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/客户管理-业务数据展示/u60.png"}},
{
              "id":"7854cb33853049a986b21aa2d2cb6473",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":100,
                  "y":0},
                "size":{
                  "width":100,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"a9fbdf7209234dca8f52fe09c3d2aa98",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":100,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/客户管理-业务数据展示/u30.png"}},
{
              "id":"944ba00b5ae44a69bc88dc77e420085a",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":100,
                  "y":20},
                "size":{
                  "width":100,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"87b1bfbd27fd4a2b9e2b80c5476d332d",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":100,
                      "y":20},
                    "size":{
                      "width":100,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/客户管理-业务数据展示/u30.png"}},
{
              "id":"6fbd3991d3434d53bc8ac59394b0d5c6",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":100,
                  "y":40},
                "size":{
                  "width":100,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"987ef4e9764140269a8fb798ecc3a06a",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":100,
                      "y":40},
                    "size":{
                      "width":100,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/客户管理-业务数据展示/u30.png"}},
{
              "id":"b6a9dca2830d4c508099155893381981",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":100,
                  "y":60},
                "size":{
                  "width":100,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"8534593dc5b24d538bbe040b93f3c261",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":100,
                      "y":60},
                    "size":{
                      "width":100,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/客户管理-业务数据展示/u60.png"}},
{
              "id":"f16306b98d7248a09d8e5de4a8b15ffa",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":200,
                  "y":0},
                "size":{
                  "width":100,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"674019462470404d8db115998fc1c497",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":200,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/客户管理-业务数据展示/u30.png"}},
{
              "id":"b201decabdf641ebb91120b47fd75436",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":200,
                  "y":20},
                "size":{
                  "width":100,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"f571e3a76b1844fe98591247534ec6eb",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":200,
                      "y":20},
                    "size":{
                      "width":100,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/客户管理-业务数据展示/u30.png"}},
{
              "id":"7417c8686ade477eb23f5280bfc7702a",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":200,
                  "y":40},
                "size":{
                  "width":100,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"58556fcaf2534a5ba3c21b968172fd0e",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":200,
                      "y":40},
                    "size":{
                      "width":100,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/客户管理-业务数据展示/u30.png"}},
{
              "id":"92f2af52a38b4b76a105d804dd0d8bc7",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":200,
                  "y":60},
                "size":{
                  "width":100,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"454261c5ebc14366a05571c11355a45d",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":200,
                      "y":60},
                    "size":{
                      "width":100,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/客户管理-业务数据展示/u60.png"}},
{
              "id":"604d50edd2da44758d9c7e9bfc93ec60",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":300,
                  "y":0},
                "size":{
                  "width":100,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"91aeace228784524bb55df58ad8d4a98",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":300,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/客户管理-业务数据展示/u30.png"}},
{
              "id":"e08db2a5752e4ba89c4af73283f10f91",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":300,
                  "y":20},
                "size":{
                  "width":100,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"17ad9cad014843678bae63e478ff415c",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":300,
                      "y":20},
                    "size":{
                      "width":100,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/客户管理-业务数据展示/u30.png"}},
{
              "id":"8fef8f7b6e0040549d7bb53d48f3c796",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":300,
                  "y":40},
                "size":{
                  "width":100,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"34530de6bf97430da37b25ccba95cfda",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":300,
                      "y":40},
                    "size":{
                      "width":100,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/客户管理-业务数据展示/u30.png"}},
{
              "id":"5d6ba89b6a564b2198712c7269b81b2e",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":300,
                  "y":60},
                "size":{
                  "width":100,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"0aea567f27cd4d439c28943d37080ecf",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":300,
                      "y":60},
                    "size":{
                      "width":100,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/客户管理-业务数据展示/u60.png"}},
{
              "id":"109df1204f9940108d6bec5df28c8916",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":400,
                  "y":0},
                "size":{
                  "width":100,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"3f31523ef4c44449879c44e9716eeb78",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":400,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/客户管理-业务数据展示/u38.png"}},
{
              "id":"664427063f1e4be9a95148c55cb30800",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":400,
                  "y":20},
                "size":{
                  "width":100,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"e922e5f0f2d84fa5b8983f8ab40566d4",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":400,
                      "y":20},
                    "size":{
                      "width":100,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/客户管理-业务数据展示/u38.png"}},
{
              "id":"239f248f36184e56a05a4a092678f97a",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":400,
                  "y":40},
                "size":{
                  "width":100,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"129cdc62c94b4131852c0c6226684c1a",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":400,
                      "y":40},
                    "size":{
                      "width":100,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/客户管理-业务数据展示/u38.png"}},
{
              "id":"8d8d4dcd5bab488683436553660bdd12",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":400,
                  "y":60},
                "size":{
                  "width":100,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"0d1c931d840345758b1470cd033b6cf6",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":400,
                      "y":60},
                    "size":{
                      "width":100,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/客户管理-业务数据展示/u68.png"}}]}]}},
  "masters":{
},
  "objectPaths":{
    "838e0d9e555e40519856271b46579fe1":{
      "scriptId":"u0"},
    "24a7e020d79d47169034d2e6a7b49e67":{
      "scriptId":"u1"},
    "848179f3481241fe9ae0aba57b52033c":{
      "scriptId":"u2"},
    "8f905ce22942409d88c126724657648a":{
      "scriptId":"u3"},
    "14e0bf6a93e64983b641bfc17385c1c0":{
      "scriptId":"u4"},
    "73f16647ffb845fc810e462dc15d7790":{
      "scriptId":"u5"},
    "682c82cebf934c249d4c61c26f1cb052":{
      "scriptId":"u6"},
    "e50d631b6fd04791b674e1c1d3ba3830":{
      "scriptId":"u7"},
    "955d62b397594e31931cfbeb6bb10e38":{
      "scriptId":"u8"},
    "0de7f6d8933d4e3b9a884848d3c58d2b":{
      "scriptId":"u9"},
    "5e1d9ada7fed46dba7919a1db8e62357":{
      "scriptId":"u10"},
    "e1a8aa2bec7647bc8ce8799342eb70da":{
      "scriptId":"u11"},
    "638536f5876b46b3ab42f2f1620578d1":{
      "scriptId":"u12"},
    "59ade5a89b384360bc4589d1deb8cad0":{
      "scriptId":"u13"},
    "87d4972dd0324bf081f27baa89987810":{
      "scriptId":"u14"},
    "524adc81647b49b687c2eb277d4b90fc":{
      "scriptId":"u15"},
    "7628074c51704a4f8e79b98af7bad292":{
      "scriptId":"u16"},
    "9d5ba9f3ec6445f69147aefeed62c8fd":{
      "scriptId":"u17"},
    "9823c2fd75634c248a33ad460214f2de":{
      "scriptId":"u18"},
    "1b22c27bd84342048b8ce606897181ad":{
      "scriptId":"u19"},
    "f2c8fa80a87c4647b9e22c896af9fba9":{
      "scriptId":"u20"},
    "08b907f806824b1e8bcc164304d596ff":{
      "scriptId":"u21"},
    "80fb869975614a3dbb177b5810387de3":{
      "scriptId":"u22"},
    "7854cb33853049a986b21aa2d2cb6473":{
      "scriptId":"u23"},
    "a9fbdf7209234dca8f52fe09c3d2aa98":{
      "scriptId":"u24"},
    "f16306b98d7248a09d8e5de4a8b15ffa":{
      "scriptId":"u25"},
    "674019462470404d8db115998fc1c497":{
      "scriptId":"u26"},
    "604d50edd2da44758d9c7e9bfc93ec60":{
      "scriptId":"u27"},
    "91aeace228784524bb55df58ad8d4a98":{
      "scriptId":"u28"},
    "109df1204f9940108d6bec5df28c8916":{
      "scriptId":"u29"},
    "3f31523ef4c44449879c44e9716eeb78":{
      "scriptId":"u30"},
    "47900837c58e4de49f17e0e00909a275":{
      "scriptId":"u31"},
    "19c6d71292b74da6ad4172583e955e75":{
      "scriptId":"u32"},
    "944ba00b5ae44a69bc88dc77e420085a":{
      "scriptId":"u33"},
    "87b1bfbd27fd4a2b9e2b80c5476d332d":{
      "scriptId":"u34"},
    "b201decabdf641ebb91120b47fd75436":{
      "scriptId":"u35"},
    "f571e3a76b1844fe98591247534ec6eb":{
      "scriptId":"u36"},
    "e08db2a5752e4ba89c4af73283f10f91":{
      "scriptId":"u37"},
    "17ad9cad014843678bae63e478ff415c":{
      "scriptId":"u38"},
    "664427063f1e4be9a95148c55cb30800":{
      "scriptId":"u39"},
    "e922e5f0f2d84fa5b8983f8ab40566d4":{
      "scriptId":"u40"},
    "c3ad8eef1db2499badeb91eb79de604a":{
      "scriptId":"u41"},
    "dd9a03160b3546a2a79379268863fbf3":{
      "scriptId":"u42"},
    "6fbd3991d3434d53bc8ac59394b0d5c6":{
      "scriptId":"u43"},
    "987ef4e9764140269a8fb798ecc3a06a":{
      "scriptId":"u44"},
    "7417c8686ade477eb23f5280bfc7702a":{
      "scriptId":"u45"},
    "58556fcaf2534a5ba3c21b968172fd0e":{
      "scriptId":"u46"},
    "8fef8f7b6e0040549d7bb53d48f3c796":{
      "scriptId":"u47"},
    "34530de6bf97430da37b25ccba95cfda":{
      "scriptId":"u48"},
    "239f248f36184e56a05a4a092678f97a":{
      "scriptId":"u49"},
    "129cdc62c94b4131852c0c6226684c1a":{
      "scriptId":"u50"},
    "1db03dfa5a654121888392cdcbbf69a9":{
      "scriptId":"u51"},
    "2beddcc87d7e487ca2916b6b8c7b62b7":{
      "scriptId":"u52"},
    "b6a9dca2830d4c508099155893381981":{
      "scriptId":"u53"},
    "8534593dc5b24d538bbe040b93f3c261":{
      "scriptId":"u54"},
    "92f2af52a38b4b76a105d804dd0d8bc7":{
      "scriptId":"u55"},
    "454261c5ebc14366a05571c11355a45d":{
      "scriptId":"u56"},
    "5d6ba89b6a564b2198712c7269b81b2e":{
      "scriptId":"u57"},
    "0aea567f27cd4d439c28943d37080ecf":{
      "scriptId":"u58"},
    "8d8d4dcd5bab488683436553660bdd12":{
      "scriptId":"u59"},
    "0d1c931d840345758b1470cd033b6cf6":{
      "scriptId":"u60"}}});