$axure.loadCurrentPage({
  "url":"审批流程.html",
  "generationDate":new Date(1662083787562.9),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"52bbe3a349944252b3f92da61c7de1e0",
    "type":"Axure:Page",
    "name":"审批流程",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"6f7c862df49c4404997736a0ae9bbeda",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":68,
              "y":80},
            "size":{
              "width":675,
              "height":224}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1b0599a1beee456facac9f93e2d466ce",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":68,
                  "y":80},
                "size":{
                  "width":675,
                  "height":224}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "6f7c862df49c4404997736a0ae9bbeda":{
      "scriptId":"u0"},
    "1b0599a1beee456facac9f93e2d466ce":{
      "scriptId":"u1"}}});