$axure.loadCurrentPage({
  "url":"审批流程图.html",
  "generationDate":new Date(1661394098842.91),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"52bbe3a349944252b3f92da61c7de1e0",
    "type":"Axure:Page",
    "name":"审批流程图",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"380cfcb870b540928012704ceb6db7e4",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":20},
            "size":{
              "width":760,
              "height":420}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"02f0010238704a91ae1fb8c806e7c8b3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":20},
                "size":{
                  "width":760,
                  "height":420}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/审批流程图/u0.jpg"}},
{
          "id":"6f7c862df49c4404997736a0ae9bbeda",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":770,
              "y":150},
            "size":{
              "width":552,
              "height":144}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1b0599a1beee456facac9f93e2d466ce",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":770,
                  "y":150},
                "size":{
                  "width":552,
                  "height":144}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "380cfcb870b540928012704ceb6db7e4":{
      "scriptId":"u0"},
    "02f0010238704a91ae1fb8c806e7c8b3":{
      "scriptId":"u1"},
    "6f7c862df49c4404997736a0ae9bbeda":{
      "scriptId":"u2"},
    "1b0599a1beee456facac9f93e2d466ce":{
      "scriptId":"u3"}}});