$axure.loadCurrentPage({
  "url":"文章分类管理.html",
  "generationDate":new Date(1661498375643.07),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"ffca4a3ba9234aab999ad6f0cba10e67",
    "type":"Axure:Page",
    "name":"文章分类管理",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"4724fa39274f46479bb670d462345ebf",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":30,
              "y":120},
            "size":{
              "width":1037,
              "height":570}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5e21032552d440208c1daa3da87d293e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":30,
                  "y":120},
                "size":{
                  "width":1037,
                  "height":570}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/文章分类管理/u0.jpg"}},
{
          "id":"edbe09b6e91248ba819daeeae07de721",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":530,
              "y":54},
            "size":{
              "width":450,
              "height":66}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e9309be57bf045148de66fefd3bc2d48",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":530,
                  "y":54},
                "size":{
                  "width":450,
                  "height":66}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2c0b7ac5829f4e94964f19a59871e276",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":587,
              "y":284},
            "size":{
              "width":253,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"db56cf105d81424b9a149b33fe3e937f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":587,
                  "y":284},
                "size":{
                  "width":253,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "4724fa39274f46479bb670d462345ebf":{
      "scriptId":"u0"},
    "5e21032552d440208c1daa3da87d293e":{
      "scriptId":"u1"},
    "edbe09b6e91248ba819daeeae07de721":{
      "scriptId":"u2"},
    "e9309be57bf045148de66fefd3bc2d48":{
      "scriptId":"u3"},
    "2c0b7ac5829f4e94964f19a59871e276":{
      "scriptId":"u4"},
    "db56cf105d81424b9a149b33fe3e937f":{
      "scriptId":"u5"}}});