$axure.loadCurrentPage({
  "url":"带货营销-查看页面.html",
  "generationDate":new Date(1662608855157.22),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"d728bef5f684468cb274324fccdae26b",
    "type":"Axure:Page",
    "name":"带货营销-查看页面",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"b5ec6d0d2db44bfa8fc7170765e555bb",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":150,
              "y":44},
            "size":{
              "width":963,
              "height":616}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"558da1beccd143089cde05d4d063c839",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":150,
                  "y":44},
                "size":{
                  "width":963,
                  "height":616}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/带货营销-查看页面/u0.jpg"}},
{
          "id":"ae7200c6a50849168e9ba8d1d7edc581",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":150,
              "y":440},
            "size":{
              "width":600,
              "height":90}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5512e233df3c499e8a2d02a1947fd048",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":30},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"6b70fcf81ef14c7aa5c2d7c8dec4a5b9",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":30},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/添加模块/u1.png"}},
{
              "id":"67ecaf818fc9439e9935757ddc23462d",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":60},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"78b7673f9e2946df92c267f5a5f47cf5",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":60},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/编辑模块顺序/u13.png"}},
{
              "id":"b34a2620213d44e2a2ccaa7c25e6953a",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":100,
                  "y":30},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"335e3c6a46844156a5273310224bcb98",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":100,
                      "y":30},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/添加模块/u1.png"}},
{
              "id":"4d4fc5d1e1bd43569a391cc8bd3d9a22",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":100,
                  "y":60},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"22b67cc8fec54ddea98152ddbda08e69",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":100,
                      "y":60},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/编辑模块顺序/u13.png"}},
{
              "id":"4075bdf1dcb6446e9d7de78a2d989fa7",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":500,
                  "y":30},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"e1352c5dd4cd432a8c09b6351a031ecc",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":500,
                      "y":30},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/添加模块/u5.png"}},
{
              "id":"462bb0ad1fc84686a5174efc7695903d",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":500,
                  "y":60},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"79c7f9bae9394408bb3e1d73226a195b",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":500,
                      "y":60},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/编辑模块顺序/u15.png"}},
{
              "id":"454b18b8eeda4613882bd363062f08ac",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":400,
                  "y":30},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"4889ef5bf4784074811f7d0d78e91130",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":400,
                      "y":30},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/添加模块/u1.png"}},
{
              "id":"abc336dfb4294584a0931b48e0f73483",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":400,
                  "y":60},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"7f4b3d91008e4b43810d40ccb5307c9e",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":400,
                      "y":60},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/编辑模块顺序/u13.png"}},
{
              "id":"f336ac256a8a4c5bb4ebdee0a4cddb1e",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"c8c6ef2780a34797861ac07133399d3e",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/添加模块/u1.png"}},
{
              "id":"d9ba187c66944a4b9c311e414aa90cab",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":100,
                  "y":0},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"32748cd61f21485d854717913a9bb822",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":100,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/添加模块/u1.png"}},
{
              "id":"503d54b53a594969a4ae86190911d7e4",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":400,
                  "y":0},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"18c657a8d16446d3951a58d7c8170da5",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":400,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/添加模块/u1.png"}},
{
              "id":"429e238f157e4ae2b02561793cd30c61",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":500,
                  "y":0},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"34c2ffc31a2d4297859acd02e1bf80dd",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":500,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/添加模块/u5.png"}},
{
              "id":"8c868fdeb7c848199db535070a319261",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":300,
                  "y":0},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"fdffe02f929a4fd791da2a9fdc14615d",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":300,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/添加模块/u1.png"}},
{
              "id":"4652bdd601cf4489a219bd4abeebf5f0",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":300,
                  "y":30},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"3dd20bf8eec842c392b06db6a0b4b690",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":300,
                      "y":30},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/添加模块/u1.png"}},
{
              "id":"64de24bbe8c2404c96e1eca3c1382ed8",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":300,
                  "y":60},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"023f102eff6347c8ab937885456ed734",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":300,
                      "y":60},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/编辑模块顺序/u13.png"}},
{
              "id":"25f137f73d944e7bbe74286451d33c8b",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":200,
                  "y":0},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"e0b0f44f3b9346ea828ec0eb1b46a2e9",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":200,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/添加模块/u1.png"}},
{
              "id":"08f9a872499f46fdb3fc5a6d3bced34a",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":200,
                  "y":30},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"64e241191d0d45aa91dc6d71a6462c44",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":200,
                      "y":30},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/添加模块/u1.png"}},
{
              "id":"ada36145f38d429298e088699066bdf1",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":200,
                  "y":60},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"30239a737cdb42998575cd1ca55e5a66",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":200,
                      "y":60},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/编辑模块顺序/u13.png"}}]},
{
          "id":"2bcfcc45845c49558ff09843a2394530",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "location":{
              "x":150,
              "y":402},
            "size":{
              "width":97,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fbff79a05b9f40a9a604c313b5fc1109",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":150,
                  "y":402},
                "size":{
                  "width":97,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1f7f6ee3e89c472080d8a8cf48b1268d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":697,
              "y":477},
            "size":{
              "width":389,
              "height":48}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8013302437cb405297390af58641100f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":697,
                  "y":477},
                "size":{
                  "width":389,
                  "height":48}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "b5ec6d0d2db44bfa8fc7170765e555bb":{
      "scriptId":"u0"},
    "558da1beccd143089cde05d4d063c839":{
      "scriptId":"u1"},
    "ae7200c6a50849168e9ba8d1d7edc581":{
      "scriptId":"u2"},
    "f336ac256a8a4c5bb4ebdee0a4cddb1e":{
      "scriptId":"u3"},
    "c8c6ef2780a34797861ac07133399d3e":{
      "scriptId":"u4"},
    "d9ba187c66944a4b9c311e414aa90cab":{
      "scriptId":"u5"},
    "32748cd61f21485d854717913a9bb822":{
      "scriptId":"u6"},
    "25f137f73d944e7bbe74286451d33c8b":{
      "scriptId":"u7"},
    "e0b0f44f3b9346ea828ec0eb1b46a2e9":{
      "scriptId":"u8"},
    "8c868fdeb7c848199db535070a319261":{
      "scriptId":"u9"},
    "fdffe02f929a4fd791da2a9fdc14615d":{
      "scriptId":"u10"},
    "503d54b53a594969a4ae86190911d7e4":{
      "scriptId":"u11"},
    "18c657a8d16446d3951a58d7c8170da5":{
      "scriptId":"u12"},
    "429e238f157e4ae2b02561793cd30c61":{
      "scriptId":"u13"},
    "34c2ffc31a2d4297859acd02e1bf80dd":{
      "scriptId":"u14"},
    "5512e233df3c499e8a2d02a1947fd048":{
      "scriptId":"u15"},
    "6b70fcf81ef14c7aa5c2d7c8dec4a5b9":{
      "scriptId":"u16"},
    "b34a2620213d44e2a2ccaa7c25e6953a":{
      "scriptId":"u17"},
    "335e3c6a46844156a5273310224bcb98":{
      "scriptId":"u18"},
    "08f9a872499f46fdb3fc5a6d3bced34a":{
      "scriptId":"u19"},
    "64e241191d0d45aa91dc6d71a6462c44":{
      "scriptId":"u20"},
    "4652bdd601cf4489a219bd4abeebf5f0":{
      "scriptId":"u21"},
    "3dd20bf8eec842c392b06db6a0b4b690":{
      "scriptId":"u22"},
    "454b18b8eeda4613882bd363062f08ac":{
      "scriptId":"u23"},
    "4889ef5bf4784074811f7d0d78e91130":{
      "scriptId":"u24"},
    "4075bdf1dcb6446e9d7de78a2d989fa7":{
      "scriptId":"u25"},
    "e1352c5dd4cd432a8c09b6351a031ecc":{
      "scriptId":"u26"},
    "67ecaf818fc9439e9935757ddc23462d":{
      "scriptId":"u27"},
    "78b7673f9e2946df92c267f5a5f47cf5":{
      "scriptId":"u28"},
    "4d4fc5d1e1bd43569a391cc8bd3d9a22":{
      "scriptId":"u29"},
    "22b67cc8fec54ddea98152ddbda08e69":{
      "scriptId":"u30"},
    "ada36145f38d429298e088699066bdf1":{
      "scriptId":"u31"},
    "30239a737cdb42998575cd1ca55e5a66":{
      "scriptId":"u32"},
    "64de24bbe8c2404c96e1eca3c1382ed8":{
      "scriptId":"u33"},
    "023f102eff6347c8ab937885456ed734":{
      "scriptId":"u34"},
    "abc336dfb4294584a0931b48e0f73483":{
      "scriptId":"u35"},
    "7f4b3d91008e4b43810d40ccb5307c9e":{
      "scriptId":"u36"},
    "462bb0ad1fc84686a5174efc7695903d":{
      "scriptId":"u37"},
    "79c7f9bae9394408bb3e1d73226a195b":{
      "scriptId":"u38"},
    "2bcfcc45845c49558ff09843a2394530":{
      "scriptId":"u39"},
    "fbff79a05b9f40a9a604c313b5fc1109":{
      "scriptId":"u40"},
    "1f7f6ee3e89c472080d8a8cf48b1268d":{
      "scriptId":"u41"},
    "8013302437cb405297390af58641100f":{
      "scriptId":"u42"}}});