$axure.loadCurrentPage({
  "url":"带货营销-第2级审批单据.html",
  "generationDate":new Date(1662692044027.97),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"18ed2c19f6914308a7065b25108b7a09",
    "type":"Axure:Page",
    "name":"带货营销-第2级审批单据",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"b5ec6d0d2db44bfa8fc7170765e555bb",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":150,
              "y":44},
            "size":{
              "width":963,
              "height":616}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"558da1beccd143089cde05d4d063c839",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":150,
                  "y":44},
                "size":{
                  "width":963,
                  "height":616}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/带货营销-查看页面/u0.jpg"}}]}},
  "masters":{
},
  "objectPaths":{
    "b5ec6d0d2db44bfa8fc7170765e555bb":{
      "scriptId":"u0"},
    "558da1beccd143089cde05d4d063c839":{
      "scriptId":"u1"}}});