$axure.loadCurrentPage({
  "url":"查看数据-财务公司.html",
  "generationDate":new Date(1661416129722.53),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"47c923758fab4fafbc8914c0d8fe6848",
    "type":"Axure:Page",
    "name":"查看数据-财务公司",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"838e0d9e555e40519856271b46579fe1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":-8,
              "y":94},
            "size":{
              "width":950,
              "height":476}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"24a7e020d79d47169034d2e6a7b49e67",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":-8,
                  "y":94},
                "size":{
                  "width":950,
                  "height":476}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/查看数据-财务公司/u0.png"}},
{
          "id":"848179f3481241fe9ae0aba57b52033c",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":20,
              "y":93.5},
            "size":{
              "width":97,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8f905ce22942409d88c126724657648a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":20,
                  "y":93.5},
                "size":{
                  "width":97,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"14e0bf6a93e64983b641bfc17385c1c0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":34,
              "y":164},
            "size":{
              "width":112,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"73f16647ffb845fc810e462dc15d7790",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":34,
                  "y":164},
                "size":{
                  "width":112,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"682c82cebf934c249d4c61c26f1cb052",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "disabled":true,
          "visible":true,
          "style":{
            "location":{
              "x":146,
              "y":164.5},
            "size":{
              "width":120,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"e50d631b6fd04791b674e1c1d3ba3830",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":34,
              "y":196.5},
            "size":{
              "width":993,
              "height":52}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"955d62b397594e31931cfbeb6bb10e38",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "size":{
                  "width":99,
                  "height":52}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"0de7f6d8933d4e3b9a884848d3c58d2b",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFF0000,
                      "opacity":1},
                    "size":{
                      "width":99,
                      "height":52}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/业务数据导入/u209.png"}},
{
              "id":"0974d71d1ac64f47a47ac3b9b03a54e6",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":198,
                  "y":0},
                "size":{
                  "width":99,
                  "height":52}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"8a64159776d048db93bef74019c90420",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":198,
                      "y":0},
                    "size":{
                      "width":99,
                      "height":52}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/业务数据导入/u209.png"}},
{
              "id":"19fbc6260b69491eb3c8b574f5f5c955",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":297,
                  "y":0},
                "size":{
                  "width":99,
                  "height":52}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"e4be8f145b7247e1a9440618a082be7c",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":297,
                      "y":0},
                    "size":{
                      "width":99,
                      "height":52}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/业务数据导入/u209.png"}},
{
              "id":"27d5812df6ac477781a6d8157c6c3d24",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":396,
                  "y":0},
                "size":{
                  "width":99,
                  "height":52}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"56f7313e0f534b4ab4701f9446bccb98",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":396,
                      "y":0},
                    "size":{
                      "width":99,
                      "height":52}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/业务数据导入/u209.png"}},
{
              "id":"9f8686414a864fd59bea5d6f777cdd25",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":495,
                  "y":0},
                "size":{
                  "width":99,
                  "height":52}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"6b5194fe3ba747a7bdcca21898d6f2bd",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":495,
                      "y":0},
                    "size":{
                      "width":99,
                      "height":52}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/业务数据导入/u209.png"}},
{
              "id":"ec5add094f654086a90a351e952668a4",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":594,
                  "y":0},
                "size":{
                  "width":99,
                  "height":52}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"c2dd6706232a43199e64c360d47c7170",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":594,
                      "y":0},
                    "size":{
                      "width":99,
                      "height":52}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/业务数据导入/u209.png"}},
{
              "id":"e5718d83199a4cebb334747c10bf5ef9",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":693,
                  "y":0},
                "size":{
                  "width":99,
                  "height":52}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"37b61148304c4f29b736a7d95f5a958e",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":693,
                      "y":0},
                    "size":{
                      "width":99,
                      "height":52}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/业务数据导入/u209.png"}},
{
              "id":"407dc542ff35493ba96691785a9a1e2e",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":792,
                  "y":0},
                "size":{
                  "width":99,
                  "height":52}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"d8cf3325faf64d5ea792d490abf2872a",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":792,
                      "y":0},
                    "size":{
                      "width":99,
                      "height":52}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/业务数据导入/u209.png"}},
{
              "id":"389cf857531c4915a2abaa55158340f2",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":891,
                  "y":0},
                "size":{
                  "width":102,
                  "height":52}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"961cf3c41b9246f59ee223b1ad801e4f",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":891,
                      "y":0},
                    "size":{
                      "width":102,
                      "height":52}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/业务数据导入/u227.png"}},
{
              "id":"dbc164d3e8674ee5a5a17406346196b8",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":99,
                  "y":0},
                "size":{
                  "width":99,
                  "height":52}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"84cde387ac0844bf8e303e823a4d81af",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFF0000,
                      "opacity":1},
                    "location":{
                      "x":99,
                      "y":0},
                    "size":{
                      "width":99,
                      "height":52}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/业务数据导入/u209.png"}}]},
{
          "id":"5e1d9ada7fed46dba7919a1db8e62357",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":302,
              "y":136},
            "size":{
              "width":54,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e1a8aa2bec7647bc8ce8799342eb70da",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":302,
                  "y":136},
                "size":{
                  "width":54,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"638536f5876b46b3ab42f2f1620578d1",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "disabled":true,
          "visible":true,
          "style":{
            "location":{
              "x":398,
              "y":132.5},
            "size":{
              "width":120,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"59ade5a89b384360bc4589d1deb8cad0",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":146,
              "y":132.5},
            "size":{
              "width":120,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"87d4972dd0324bf081f27baa89987810",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":34,
              "y":138},
            "size":{
              "width":86,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"524adc81647b49b687c2eb277d4b90fc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":34,
                  "y":138},
                "size":{
                  "width":86,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d15d0486c011433a8f2d6db07ce84242",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":43,
              "y":253},
            "size":{
              "width":830,
              "height":240}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3dbc94ffdd6e44de9b9e04f20ae73cf6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":43,
                  "y":253},
                "size":{
                  "width":830,
                  "height":240}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/业务数据导入/u238.png"}},
{
          "id":"7628074c51704a4f8e79b98af7bad292",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":372,
              "y":489},
            "size":{
              "width":508,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9d5ba9f3ec6445f69147aefeed62c8fd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":372,
                  "y":489},
                "size":{
                  "width":508,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/余额_收入详情/u73.png"}},
{
          "id":"9823c2fd75634c248a33ad460214f2de",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":889,
              "y":450},
            "size":{
              "width":237,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1b22c27bd84342048b8ce606897181ad",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":889,
                  "y":450},
                "size":{
                  "width":237,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "838e0d9e555e40519856271b46579fe1":{
      "scriptId":"u0"},
    "24a7e020d79d47169034d2e6a7b49e67":{
      "scriptId":"u1"},
    "848179f3481241fe9ae0aba57b52033c":{
      "scriptId":"u2"},
    "8f905ce22942409d88c126724657648a":{
      "scriptId":"u3"},
    "14e0bf6a93e64983b641bfc17385c1c0":{
      "scriptId":"u4"},
    "73f16647ffb845fc810e462dc15d7790":{
      "scriptId":"u5"},
    "682c82cebf934c249d4c61c26f1cb052":{
      "scriptId":"u6"},
    "e50d631b6fd04791b674e1c1d3ba3830":{
      "scriptId":"u7"},
    "955d62b397594e31931cfbeb6bb10e38":{
      "scriptId":"u8"},
    "0de7f6d8933d4e3b9a884848d3c58d2b":{
      "scriptId":"u9"},
    "dbc164d3e8674ee5a5a17406346196b8":{
      "scriptId":"u10"},
    "84cde387ac0844bf8e303e823a4d81af":{
      "scriptId":"u11"},
    "0974d71d1ac64f47a47ac3b9b03a54e6":{
      "scriptId":"u12"},
    "8a64159776d048db93bef74019c90420":{
      "scriptId":"u13"},
    "19fbc6260b69491eb3c8b574f5f5c955":{
      "scriptId":"u14"},
    "e4be8f145b7247e1a9440618a082be7c":{
      "scriptId":"u15"},
    "27d5812df6ac477781a6d8157c6c3d24":{
      "scriptId":"u16"},
    "56f7313e0f534b4ab4701f9446bccb98":{
      "scriptId":"u17"},
    "9f8686414a864fd59bea5d6f777cdd25":{
      "scriptId":"u18"},
    "6b5194fe3ba747a7bdcca21898d6f2bd":{
      "scriptId":"u19"},
    "ec5add094f654086a90a351e952668a4":{
      "scriptId":"u20"},
    "c2dd6706232a43199e64c360d47c7170":{
      "scriptId":"u21"},
    "e5718d83199a4cebb334747c10bf5ef9":{
      "scriptId":"u22"},
    "37b61148304c4f29b736a7d95f5a958e":{
      "scriptId":"u23"},
    "407dc542ff35493ba96691785a9a1e2e":{
      "scriptId":"u24"},
    "d8cf3325faf64d5ea792d490abf2872a":{
      "scriptId":"u25"},
    "389cf857531c4915a2abaa55158340f2":{
      "scriptId":"u26"},
    "961cf3c41b9246f59ee223b1ad801e4f":{
      "scriptId":"u27"},
    "5e1d9ada7fed46dba7919a1db8e62357":{
      "scriptId":"u28"},
    "e1a8aa2bec7647bc8ce8799342eb70da":{
      "scriptId":"u29"},
    "638536f5876b46b3ab42f2f1620578d1":{
      "scriptId":"u30"},
    "59ade5a89b384360bc4589d1deb8cad0":{
      "scriptId":"u31"},
    "87d4972dd0324bf081f27baa89987810":{
      "scriptId":"u32"},
    "524adc81647b49b687c2eb277d4b90fc":{
      "scriptId":"u33"},
    "d15d0486c011433a8f2d6db07ce84242":{
      "scriptId":"u34"},
    "3dbc94ffdd6e44de9b9e04f20ae73cf6":{
      "scriptId":"u35"},
    "7628074c51704a4f8e79b98af7bad292":{
      "scriptId":"u36"},
    "9d5ba9f3ec6445f69147aefeed62c8fd":{
      "scriptId":"u37"},
    "9823c2fd75634c248a33ad460214f2de":{
      "scriptId":"u38"},
    "1b22c27bd84342048b8ce606897181ad":{
      "scriptId":"u39"}}});