$axure.loadCurrentPage({
  "url":"集团融资预算管理.html",
  "generationDate":new Date(1660793549823.59),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"6d1ba38830484a8bbf0e10316e2353b0",
    "type":"Axure:Page",
    "name":"集团融资预算管理",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"03f827ab84af40dc8a541b5def0d3102",
          "label":"",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":false,
          "selected":true,
          "style":{
            "location":{
              "x":40,
              "y":363},
            "size":{
              "width":630,
              "height":237},
            "visible":false},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"6844208d831d488a8fea1b8bbb7ee221",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[]}]},
{
          "id":"409a9458647e498cad434197c1447305",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":51,
              "y":374},
            "size":{
              "width":608,
              "height":206}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"960825daee234aa8af7b398de15d0e64",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":51,
                  "y":374},
                "size":{
                  "width":608,
                  "height":206}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/金融产品管理/u1.png"}},
{
          "id":"0651bd8a300042d38aac429308eb0813",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":50,
              "y":32},
            "size":{
              "width":250,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4bb9f8bf396146b7b66fb14802e4c4c7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":50,
                  "y":32},
                "size":{
                  "width":250,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b403396e58514c379287948174059cf1",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":160,
              "y":90},
            "size":{
              "width":105,
              "height":25}},
          "adaptiveStyles":{
},
          "placeholderText":"请输入客户名称"},
{
          "id":"7bb5514923734bf7ac3fad9921ef5542",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":48,
              "y":70},
            "size":{
              "width":852,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/贷款余额登记管理/u6_line.png"}},
{
          "id":"1c6c986da48a4abab79039b45f08ef7e",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":730,
              "y":90},
            "size":{
              "width":60,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"1fee7477afa54b49a5de5ed866a2052a",
          "label":"",
          "type":"button",
          "styleType":"button",
          "disabled":true,
          "visible":true,
          "style":{
            "location":{
              "x":870,
              "y":90},
            "size":{
              "width":60,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"2d1d1b0ba7384e61b4d59bb564aa4cef",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":940,
              "y":90},
            "size":{
              "width":60,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"764ee102b4104c10b85745d10d312937",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":48,
              "y":150},
            "size":{
              "width":660,
              "height":156}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b5135ccf027a47c089827d6f3a1a0015",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "size":{
                  "width":82,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"1fbbd90cc5a54088b215f6979400cbd4",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":82,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/贷款余额登记管理/u15.png"}},
{
              "id":"a4024332b9bd47248c4f9e38de61f73c",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":36},
                "size":{
                  "width":82,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"7f7b4df9522547f991b0eaf398c207d1",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":36},
                    "size":{
                      "width":82,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/贷款余额登记管理/u39.png"}},
{
              "id":"6eeac3850be74af5bd42ace98709d32b",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":56},
                "size":{
                  "width":82,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"0e923acf6e4e49458211ce4054782cc3",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":56},
                    "size":{
                      "width":82,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/贷款余额登记管理/u39.png"}},
{
              "id":"978c3a8a54d44fbdbcca480cefb4c4e2",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":76},
                "size":{
                  "width":82,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"7ddbf61c9e2b44ccbfc92cc48cfefc9b",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":76},
                    "size":{
                      "width":82,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/贷款余额登记管理/u39.png"}},
{
              "id":"056a6f762ad44022a3872dbfbbed667a",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":96},
                "size":{
                  "width":82,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"504dc5f2476848f9a38ee6dcfed56d25",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":96},
                    "size":{
                      "width":82,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/贷款余额登记管理/u39.png"}},
{
              "id":"41d9ed8a690343fb83772a5ec998dc71",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":116},
                "size":{
                  "width":82,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"85313d9e351e45a09ff42cb5f84268c6",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":116},
                    "size":{
                      "width":82,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/贷款余额登记管理/u39.png"}},
{
              "id":"91344cedef71482da1c55eb9c8abc1bc",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":136},
                "size":{
                  "width":82,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"55cb9caa30b6431fb60145b4da68e223",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":136},
                    "size":{
                      "width":82,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/贷款余额登记管理/u159.png"}},
{
              "id":"58bae2b351264fbe80b960f2f5d3a5d9",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":82,
                  "y":0},
                "size":{
                  "width":78,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"ae43f79d5186477abb085a92b49d5225",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":82,
                      "y":0},
                    "size":{
                      "width":78,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/贷款余额登记管理/u21.png"}},
{
              "id":"96e890df29df4c84b62c15ce260153f7",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":82,
                  "y":36},
                "size":{
                  "width":78,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"dde045c7f1c94b46aa947797204eb7dc",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":82,
                      "y":36},
                    "size":{
                      "width":78,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/贷款余额登记管理/u45.png"}},
{
              "id":"48fd2b48789943afb36e186954c7910b",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":82,
                  "y":56},
                "size":{
                  "width":78,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"d8210f5f179b48729ca57dd7a4d53ca1",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":82,
                      "y":56},
                    "size":{
                      "width":78,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/贷款余额登记管理/u45.png"}},
{
              "id":"e628bf22227645c1b91c7486e976761b",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":82,
                  "y":76},
                "size":{
                  "width":78,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"abf5eef607d146409b4a608460109fcb",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":82,
                      "y":76},
                    "size":{
                      "width":78,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/贷款余额登记管理/u45.png"}},
{
              "id":"7ce4b4d6b92c474d966cd9c082692b0e",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":82,
                  "y":96},
                "size":{
                  "width":78,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"0bae1257cac34ebb878f94d34790d69e",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":82,
                      "y":96},
                    "size":{
                      "width":78,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/贷款余额登记管理/u45.png"}},
{
              "id":"66091384b279416e88d56499c111e7da",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":82,
                  "y":116},
                "size":{
                  "width":78,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"bc9b66ac38b54d45aa6b2f1ccb2c09d8",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":82,
                      "y":116},
                    "size":{
                      "width":78,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/贷款余额登记管理/u45.png"}},
{
              "id":"5292775bdcb74a9bbdd1276d1d295a71",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":82,
                  "y":136},
                "size":{
                  "width":78,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"1750b76ea1224257a5bdf65a3b445610",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":82,
                      "y":136},
                    "size":{
                      "width":78,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/贷款余额登记管理/u165.png"}},
{
              "id":"260ee175c7c841fd9e5185542ecf7a05",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":160,
                  "y":0},
                "size":{
                  "width":71,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"086731303cb94d2ea98b24d6f6f44697",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":160,
                      "y":0},
                    "size":{
                      "width":71,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/贷款余额登记管理/u25.png"}},
{
              "id":"8ebc026f6e694973984885c03b94a02c",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":160,
                  "y":36},
                "size":{
                  "width":71,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"df3110b4e10e4536b02ec2e35a562b33",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":160,
                      "y":36},
                    "size":{
                      "width":71,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/贷款余额登记管理/u49.png"}},
{
              "id":"3c771e181a79454594c501454b8f49bc",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":160,
                  "y":56},
                "size":{
                  "width":71,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"98fedfaf152f438ea2f41b98a7aa8486",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":160,
                      "y":56},
                    "size":{
                      "width":71,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/贷款余额登记管理/u49.png"}},
{
              "id":"ccc9af254f834e7bb366fb6a1587ca6b",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":160,
                  "y":76},
                "size":{
                  "width":71,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"ea8f0b9ab215410db5bb4b94b548a81e",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":160,
                      "y":76},
                    "size":{
                      "width":71,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/贷款余额登记管理/u49.png"}},
{
              "id":"f3803edf583f4fcab29f486a8c717950",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":160,
                  "y":96},
                "size":{
                  "width":71,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"114c24815a704a699eab23204353bb67",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":160,
                      "y":96},
                    "size":{
                      "width":71,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/贷款余额登记管理/u49.png"}},
{
              "id":"d224c6022f2941c7999840d583c90572",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":160,
                  "y":116},
                "size":{
                  "width":71,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"5c4f7f06e2cb43f19ffe22b5c1e103a5",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":160,
                      "y":116},
                    "size":{
                      "width":71,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/贷款余额登记管理/u49.png"}},
{
              "id":"a0310a8681c44fac8483ebcc9c594c08",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":160,
                  "y":136},
                "size":{
                  "width":71,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"7725e183c47b46fbb7f650ff0e9351bf",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":160,
                      "y":136},
                    "size":{
                      "width":71,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/贷款余额登记管理/u169.png"}},
{
              "id":"e18420e37f5b4ad9b3885a0151e03238",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":231,
                  "y":0},
                "size":{
                  "width":113,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"ed405d9696be43c9b023ec2043b95e0d",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":231,
                      "y":0},
                    "size":{
                      "width":113,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/贷款余额登记管理/u27.png"}},
{
              "id":"4ea1f27299c6474ebe5a2af11023ec7b",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":231,
                  "y":36},
                "size":{
                  "width":113,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"6b855497f9634c2f95896c89be17792d",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":231,
                      "y":36},
                    "size":{
                      "width":113,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/贷款余额登记管理/u51.png"}},
{
              "id":"c09a6f6ea8c745c4bb67d389bd5d3274",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":231,
                  "y":56},
                "size":{
                  "width":113,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"7949fb66e5cd4a7eb73a9dd825d668cb",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":231,
                      "y":56},
                    "size":{
                      "width":113,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/贷款余额登记管理/u51.png"}},
{
              "id":"115983d77a42465484cb47975b60765b",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":231,
                  "y":76},
                "size":{
                  "width":113,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"4c4b9bc35bd747fb9e8fcdcc6d6051e2",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":231,
                      "y":76},
                    "size":{
                      "width":113,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/贷款余额登记管理/u51.png"}},
{
              "id":"9384fc1b448e4d3b80fedb18420a3f3a",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":231,
                  "y":96},
                "size":{
                  "width":113,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"95a33e6cc0f74525a90987309679e53a",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":231,
                      "y":96},
                    "size":{
                      "width":113,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/贷款余额登记管理/u51.png"}},
{
              "id":"959606aef7754fd2b72bdc2488d95e48",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":231,
                  "y":116},
                "size":{
                  "width":113,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"3df9797bcee94e5883813e62dddba9f7",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":231,
                      "y":116},
                    "size":{
                      "width":113,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/贷款余额登记管理/u51.png"}},
{
              "id":"4eac9e27ae0949d985ef8c51916ea5ee",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":231,
                  "y":136},
                "size":{
                  "width":113,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"271b998d5a274c1e947a4b3993f4ad1f",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":231,
                      "y":136},
                    "size":{
                      "width":113,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/贷款余额登记管理/u171.png"}},
{
              "id":"aecbfa91424642ffa885c9c43a4ce431",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":344,
                  "y":0},
                "size":{
                  "width":87,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"97bdffe0dde74eefb1bf5542cb7e0966",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":344,
                      "y":0},
                    "size":{
                      "width":87,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/贷款余额登记管理/u31.png"}},
{
              "id":"3d9bdb255ec6409ca558f0eb6b2b7a87",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":344,
                  "y":36},
                "size":{
                  "width":87,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"0e1941ab84db428e83e059898a0306ea",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":344,
                      "y":36},
                    "size":{
                      "width":87,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/贷款余额登记管理/u55.png"}},
{
              "id":"ea4489859b9b40c6a925a3bbb28e0494",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":344,
                  "y":56},
                "size":{
                  "width":87,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"8140c6bfb10847e89a7d2a2452ddca18",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":344,
                      "y":56},
                    "size":{
                      "width":87,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/贷款余额登记管理/u55.png"}},
{
              "id":"f93c7936a5734ec683df0d059b03c6ec",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":344,
                  "y":76},
                "size":{
                  "width":87,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"04fde484982c42bf89f09554c65a0d9b",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":344,
                      "y":76},
                    "size":{
                      "width":87,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/贷款余额登记管理/u55.png"}},
{
              "id":"df1ea0007efd45e5b0e90281796900f2",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":344,
                  "y":96},
                "size":{
                  "width":87,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"36fa423c5b2a40c9b0c16c3038c3713c",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":344,
                      "y":96},
                    "size":{
                      "width":87,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/贷款余额登记管理/u55.png"}},
{
              "id":"5c284c4e03884afa8ac14a75348dc265",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":344,
                  "y":116},
                "size":{
                  "width":87,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"3735b10105bf440ea506e5a086da4339",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":344,
                      "y":116},
                    "size":{
                      "width":87,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/贷款余额登记管理/u55.png"}},
{
              "id":"ed792024f6b141299e745c942059a4c5",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":344,
                  "y":136},
                "size":{
                  "width":87,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"4b6cc68c28274f4aaa683c4d77b5f78c",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":344,
                      "y":136},
                    "size":{
                      "width":87,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/贷款余额登记管理/u175.png"}},
{
              "id":"142ef0867a0f4ba7b8c7ade95ac64375",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":431,
                  "y":0},
                "size":{
                  "width":51,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"c3345bdd57854054b7e8df5e77d17db5",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":431,
                      "y":0},
                    "size":{
                      "width":51,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/贷款余额登记管理/u33.png"}},
{
              "id":"f91d67b0154a4d638e78b652a41dd655",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":431,
                  "y":36},
                "size":{
                  "width":51,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"4f29c63fa9e84b9bb5081f29313dae5c",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":431,
                      "y":36},
                    "size":{
                      "width":51,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/贷款余额登记管理/u57.png"}},
{
              "id":"3ee67ee02bc74656b64d51654ca8884b",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":431,
                  "y":56},
                "size":{
                  "width":51,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"3a0c573022404d0d8d939845a7439638",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":431,
                      "y":56},
                    "size":{
                      "width":51,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/贷款余额登记管理/u57.png"}},
{
              "id":"3a281df8cf2245f0b772441fe1298320",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":431,
                  "y":76},
                "size":{
                  "width":51,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"22e0d4094f9f4c0fbf74b3f09edfbdb0",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":431,
                      "y":76},
                    "size":{
                      "width":51,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/贷款余额登记管理/u57.png"}},
{
              "id":"74c2ed9c510642a4be39b0f447114089",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":431,
                  "y":96},
                "size":{
                  "width":51,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"1a4df115403a41b8a17150cd8516e03c",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":431,
                      "y":96},
                    "size":{
                      "width":51,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/贷款余额登记管理/u57.png"}},
{
              "id":"272301e5baae4304929b726da44d1680",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":431,
                  "y":116},
                "size":{
                  "width":51,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"656ce739be30435ead4584ebf2993bee",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":431,
                      "y":116},
                    "size":{
                      "width":51,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/贷款余额登记管理/u57.png"}},
{
              "id":"009c561c0464497c81ababf757acc591",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":431,
                  "y":136},
                "size":{
                  "width":51,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"e3ba0e5b70d04c898ec119de5ea827da",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":431,
                      "y":136},
                    "size":{
                      "width":51,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/贷款余额登记管理/u177.png"}},
{
              "id":"7e839768e5d041709889ed5c2577cc59",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":482,
                  "y":0},
                "size":{
                  "width":46,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"12e434d394ae4828b1f5cc7988481026",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":482,
                      "y":0},
                    "size":{
                      "width":46,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/贷款余额登记管理/u35.png"}},
{
              "id":"37614c2fcc704ec48634351ab3db5729",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":482,
                  "y":36},
                "size":{
                  "width":46,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"2e65be4cc39e4964adbc94ec8bd747fd",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":482,
                      "y":36},
                    "size":{
                      "width":46,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/贷款余额登记管理/u59.png"}},
{
              "id":"099effa2cc5348ce85d5f465608f9d11",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":482,
                  "y":56},
                "size":{
                  "width":46,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"b204b31bd4ec40909d3da5e6358b2ade",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":482,
                      "y":56},
                    "size":{
                      "width":46,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/贷款余额登记管理/u59.png"}},
{
              "id":"35ed3da7ca7e43cd8bd741909cca9616",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":482,
                  "y":76},
                "size":{
                  "width":46,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"6f4748cfd23c4a8d87f15d4db59cf86c",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":482,
                      "y":76},
                    "size":{
                      "width":46,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/贷款余额登记管理/u59.png"}},
{
              "id":"6884c7133dcc4d749fb08779ec48e282",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":482,
                  "y":96},
                "size":{
                  "width":46,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"176f1abc30c546c0b1f35a3e3864e0b3",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":482,
                      "y":96},
                    "size":{
                      "width":46,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/贷款余额登记管理/u59.png"}},
{
              "id":"6b6455cb923849349cbeac82201050b4",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":482,
                  "y":116},
                "size":{
                  "width":46,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"039c90a1067941418ae50bd1953e1eca",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":482,
                      "y":116},
                    "size":{
                      "width":46,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/贷款余额登记管理/u59.png"}},
{
              "id":"5e93e6d3bf1a48e092ddfe1e8201e7e4",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":482,
                  "y":136},
                "size":{
                  "width":46,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"91f562e5ca174b87bf22cc90531f0bf5",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":482,
                      "y":136},
                    "size":{
                      "width":46,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/贷款余额登记管理/u179.png"}},
{
              "id":"eaf62c42c8c041509fb01c649232aaf2",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":528,
                  "y":0},
                "size":{
                  "width":132,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"50bf6e3f9f904f33b705b9d37062b018",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":528,
                      "y":0},
                    "size":{
                      "width":132,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/贷款余额登记管理/u37.png"}},
{
              "id":"20773267381140e68b30679349bb2090",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000099,
                  "opacity":1},
                "location":{
                  "x":528,
                  "y":36},
                "size":{
                  "width":132,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"0de98a55a97f4ac9bf22f89c1c5b7dbd",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF000099,
                      "opacity":1},
                    "location":{
                      "x":528,
                      "y":36},
                    "size":{
                      "width":132,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/贷款余额登记管理/u61.png"}},
{
              "id":"81cf65cb04954b638a6bcb88724204e1",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":528,
                  "y":56},
                "size":{
                  "width":132,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"5a62f36419414cbe8e6b3c817d3cb74b",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":528,
                      "y":56},
                    "size":{
                      "width":132,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/贷款余额登记管理/u61.png"}},
{
              "id":"f7df7ee4553a4526a70ea01bc7407799",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":528,
                  "y":76},
                "size":{
                  "width":132,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"77a149ee63fd492b85000a8d152a7df3",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":528,
                      "y":76},
                    "size":{
                      "width":132,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/贷款余额登记管理/u61.png"}},
{
              "id":"637e56f969134c42a888f634e1b8a3ae",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":528,
                  "y":96},
                "size":{
                  "width":132,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"3b7ab59b4c264e8d80acc9110e5b7141",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":528,
                      "y":96},
                    "size":{
                      "width":132,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/贷款余额登记管理/u61.png"}},
{
              "id":"8f05a4383df845adac07e6a8bbcf5ed2",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":528,
                  "y":116},
                "size":{
                  "width":132,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"3b0979833c034b949dc9f014584f08f4",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":528,
                      "y":116},
                    "size":{
                      "width":132,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/贷款余额登记管理/u61.png"}},
{
              "id":"e960ec3898a848fbae6f4f0f230ae781",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":528,
                  "y":136},
                "size":{
                  "width":132,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"723c7c3e4ce1445ea310fc70a96fb276",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":528,
                      "y":136},
                    "size":{
                      "width":132,
                      "height":20}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/贷款余额登记管理/u181.png"}}]},
{
          "id":"a8aa1723f3b242158d0f748101787a78",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":490,
              "y":316},
            "size":{
              "width":508,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8df78616ff844d6e919846ef20ea4fed",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":490,
                  "y":316},
                "size":{
                  "width":508,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/贷款余额登记管理/u183.png"}},
{
          "id":"fef5ba7cd2404fda8f2ef97dbe55a5e6",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "location":{
              "x":69,
              "y":374},
            "size":{
              "width":254,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8db59e9005164d96808628e943c0efe0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":69,
                  "y":374},
                "size":{
                  "width":254,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"51bd028d31ca435ea2304581a938faa1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":98,
              "y":458},
            "size":{
              "width":33,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"853a720a522245b1ad6c2680727b461d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":98,
                  "y":458},
                "size":{
                  "width":33,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"270eea34c5b04e818ffdb00626dc1914",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":168,
              "y":454},
            "size":{
              "width":93,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"e8fb7dfc507c45d4975fe925524feb63",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":104,
              "y":425},
            "size":{
              "width":33,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f224a30f24ea4243bccba7ec995eceb3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":104,
                  "y":425},
                "size":{
                  "width":33,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"92da21720a494f688d10be077154a327",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":168,
              "y":422},
            "size":{
              "width":382,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"63b8d94496274429b26bba9e7f2ee57a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":331,
              "y":460},
            "size":{
              "width":112,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3dbda1bc04a04bb5b7070b8331973406",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":331,
                  "y":460},
                "size":{
                  "width":112,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"15c8ff1f53b449ef978de9b1a3658791",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":450,
              "y":457},
            "size":{
              "width":123,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"56fc86d32ccc464fa7d0284a5b6cde1e",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":800,
              "y":90},
            "size":{
              "width":60,
              "height":25}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 (动态面板)",
                      "objectsToFades":[{
                          "objectPath":["03f827ab84af40dc8a541b5def0d3102"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true},
{
          "id":"be907d098c2b4159929bf9338176fda5",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":370,
              "y":525},
            "size":{
              "width":60,
              "height":25}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"隐藏 (动态面板) 向下滑动 500 ms",
                      "objectsToFades":[{
                          "objectPath":["03f827ab84af40dc8a541b5def0d3102"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "easing":"slideDown",
                              "duration":500,
                              "showType":"none"}}}]}]}]}},
          "tabbable":true},
{
          "id":"7ed7fa6ff25d45fe9b51a3ada2fc01df",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":444,
              "y":525},
            "size":{
              "width":60,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"7e78be9c1530448c9abb3a3520b97b7b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":717,
              "y":394},
            "size":{
              "width":278,
              "height":48}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"69147be70ae548eb8a436d7fa08903cc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":717,
                  "y":394},
                "size":{
                  "width":278,
                  "height":48}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6211a7f56c4d4ad78390a178c435a9b0",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":565,
              "y":93},
            "size":{
              "width":120,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"b1b89af4b36a4318a9c9111b3ebf5c8a",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":514,
              "y":525},
            "size":{
              "width":76,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"04038f9ee86a41dea497ee2aa85c3b95",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":275,
              "y":92},
            "size":{
              "width":105,
              "height":25}},
          "adaptiveStyles":{
},
          "placeholderText":"请输入预算年度"},
{
          "id":"aaa6652102bb4a808462100f73e283da",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":412,
              "y":92},
            "size":{
              "width":120,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"ebb02fbc8ee745418a1550bfd940786c",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":48,
              "y":92},
            "size":{
              "width":105,
              "height":25}},
          "adaptiveStyles":{
},
          "placeholderText":"请输入客户编码"}]}},
  "masters":{
},
  "objectPaths":{
    "03f827ab84af40dc8a541b5def0d3102":{
      "scriptId":"u0"},
    "409a9458647e498cad434197c1447305":{
      "scriptId":"u1"},
    "960825daee234aa8af7b398de15d0e64":{
      "scriptId":"u2"},
    "0651bd8a300042d38aac429308eb0813":{
      "scriptId":"u3"},
    "4bb9f8bf396146b7b66fb14802e4c4c7":{
      "scriptId":"u4"},
    "b403396e58514c379287948174059cf1":{
      "scriptId":"u5"},
    "7bb5514923734bf7ac3fad9921ef5542":{
      "scriptId":"u6"},
    "1c6c986da48a4abab79039b45f08ef7e":{
      "scriptId":"u7"},
    "1fee7477afa54b49a5de5ed866a2052a":{
      "scriptId":"u8"},
    "2d1d1b0ba7384e61b4d59bb564aa4cef":{
      "scriptId":"u9"},
    "764ee102b4104c10b85745d10d312937":{
      "scriptId":"u10"},
    "b5135ccf027a47c089827d6f3a1a0015":{
      "scriptId":"u11"},
    "1fbbd90cc5a54088b215f6979400cbd4":{
      "scriptId":"u12"},
    "58bae2b351264fbe80b960f2f5d3a5d9":{
      "scriptId":"u13"},
    "ae43f79d5186477abb085a92b49d5225":{
      "scriptId":"u14"},
    "260ee175c7c841fd9e5185542ecf7a05":{
      "scriptId":"u15"},
    "086731303cb94d2ea98b24d6f6f44697":{
      "scriptId":"u16"},
    "e18420e37f5b4ad9b3885a0151e03238":{
      "scriptId":"u17"},
    "ed405d9696be43c9b023ec2043b95e0d":{
      "scriptId":"u18"},
    "aecbfa91424642ffa885c9c43a4ce431":{
      "scriptId":"u19"},
    "97bdffe0dde74eefb1bf5542cb7e0966":{
      "scriptId":"u20"},
    "142ef0867a0f4ba7b8c7ade95ac64375":{
      "scriptId":"u21"},
    "c3345bdd57854054b7e8df5e77d17db5":{
      "scriptId":"u22"},
    "7e839768e5d041709889ed5c2577cc59":{
      "scriptId":"u23"},
    "12e434d394ae4828b1f5cc7988481026":{
      "scriptId":"u24"},
    "eaf62c42c8c041509fb01c649232aaf2":{
      "scriptId":"u25"},
    "50bf6e3f9f904f33b705b9d37062b018":{
      "scriptId":"u26"},
    "a4024332b9bd47248c4f9e38de61f73c":{
      "scriptId":"u27"},
    "7f7b4df9522547f991b0eaf398c207d1":{
      "scriptId":"u28"},
    "96e890df29df4c84b62c15ce260153f7":{
      "scriptId":"u29"},
    "dde045c7f1c94b46aa947797204eb7dc":{
      "scriptId":"u30"},
    "8ebc026f6e694973984885c03b94a02c":{
      "scriptId":"u31"},
    "df3110b4e10e4536b02ec2e35a562b33":{
      "scriptId":"u32"},
    "4ea1f27299c6474ebe5a2af11023ec7b":{
      "scriptId":"u33"},
    "6b855497f9634c2f95896c89be17792d":{
      "scriptId":"u34"},
    "3d9bdb255ec6409ca558f0eb6b2b7a87":{
      "scriptId":"u35"},
    "0e1941ab84db428e83e059898a0306ea":{
      "scriptId":"u36"},
    "f91d67b0154a4d638e78b652a41dd655":{
      "scriptId":"u37"},
    "4f29c63fa9e84b9bb5081f29313dae5c":{
      "scriptId":"u38"},
    "37614c2fcc704ec48634351ab3db5729":{
      "scriptId":"u39"},
    "2e65be4cc39e4964adbc94ec8bd747fd":{
      "scriptId":"u40"},
    "20773267381140e68b30679349bb2090":{
      "scriptId":"u41"},
    "0de98a55a97f4ac9bf22f89c1c5b7dbd":{
      "scriptId":"u42"},
    "6eeac3850be74af5bd42ace98709d32b":{
      "scriptId":"u43"},
    "0e923acf6e4e49458211ce4054782cc3":{
      "scriptId":"u44"},
    "48fd2b48789943afb36e186954c7910b":{
      "scriptId":"u45"},
    "d8210f5f179b48729ca57dd7a4d53ca1":{
      "scriptId":"u46"},
    "3c771e181a79454594c501454b8f49bc":{
      "scriptId":"u47"},
    "98fedfaf152f438ea2f41b98a7aa8486":{
      "scriptId":"u48"},
    "c09a6f6ea8c745c4bb67d389bd5d3274":{
      "scriptId":"u49"},
    "7949fb66e5cd4a7eb73a9dd825d668cb":{
      "scriptId":"u50"},
    "ea4489859b9b40c6a925a3bbb28e0494":{
      "scriptId":"u51"},
    "8140c6bfb10847e89a7d2a2452ddca18":{
      "scriptId":"u52"},
    "3ee67ee02bc74656b64d51654ca8884b":{
      "scriptId":"u53"},
    "3a0c573022404d0d8d939845a7439638":{
      "scriptId":"u54"},
    "099effa2cc5348ce85d5f465608f9d11":{
      "scriptId":"u55"},
    "b204b31bd4ec40909d3da5e6358b2ade":{
      "scriptId":"u56"},
    "81cf65cb04954b638a6bcb88724204e1":{
      "scriptId":"u57"},
    "5a62f36419414cbe8e6b3c817d3cb74b":{
      "scriptId":"u58"},
    "978c3a8a54d44fbdbcca480cefb4c4e2":{
      "scriptId":"u59"},
    "7ddbf61c9e2b44ccbfc92cc48cfefc9b":{
      "scriptId":"u60"},
    "e628bf22227645c1b91c7486e976761b":{
      "scriptId":"u61"},
    "abf5eef607d146409b4a608460109fcb":{
      "scriptId":"u62"},
    "ccc9af254f834e7bb366fb6a1587ca6b":{
      "scriptId":"u63"},
    "ea8f0b9ab215410db5bb4b94b548a81e":{
      "scriptId":"u64"},
    "115983d77a42465484cb47975b60765b":{
      "scriptId":"u65"},
    "4c4b9bc35bd747fb9e8fcdcc6d6051e2":{
      "scriptId":"u66"},
    "f93c7936a5734ec683df0d059b03c6ec":{
      "scriptId":"u67"},
    "04fde484982c42bf89f09554c65a0d9b":{
      "scriptId":"u68"},
    "3a281df8cf2245f0b772441fe1298320":{
      "scriptId":"u69"},
    "22e0d4094f9f4c0fbf74b3f09edfbdb0":{
      "scriptId":"u70"},
    "35ed3da7ca7e43cd8bd741909cca9616":{
      "scriptId":"u71"},
    "6f4748cfd23c4a8d87f15d4db59cf86c":{
      "scriptId":"u72"},
    "f7df7ee4553a4526a70ea01bc7407799":{
      "scriptId":"u73"},
    "77a149ee63fd492b85000a8d152a7df3":{
      "scriptId":"u74"},
    "056a6f762ad44022a3872dbfbbed667a":{
      "scriptId":"u75"},
    "504dc5f2476848f9a38ee6dcfed56d25":{
      "scriptId":"u76"},
    "7ce4b4d6b92c474d966cd9c082692b0e":{
      "scriptId":"u77"},
    "0bae1257cac34ebb878f94d34790d69e":{
      "scriptId":"u78"},
    "f3803edf583f4fcab29f486a8c717950":{
      "scriptId":"u79"},
    "114c24815a704a699eab23204353bb67":{
      "scriptId":"u80"},
    "9384fc1b448e4d3b80fedb18420a3f3a":{
      "scriptId":"u81"},
    "95a33e6cc0f74525a90987309679e53a":{
      "scriptId":"u82"},
    "df1ea0007efd45e5b0e90281796900f2":{
      "scriptId":"u83"},
    "36fa423c5b2a40c9b0c16c3038c3713c":{
      "scriptId":"u84"},
    "74c2ed9c510642a4be39b0f447114089":{
      "scriptId":"u85"},
    "1a4df115403a41b8a17150cd8516e03c":{
      "scriptId":"u86"},
    "6884c7133dcc4d749fb08779ec48e282":{
      "scriptId":"u87"},
    "176f1abc30c546c0b1f35a3e3864e0b3":{
      "scriptId":"u88"},
    "637e56f969134c42a888f634e1b8a3ae":{
      "scriptId":"u89"},
    "3b7ab59b4c264e8d80acc9110e5b7141":{
      "scriptId":"u90"},
    "41d9ed8a690343fb83772a5ec998dc71":{
      "scriptId":"u91"},
    "85313d9e351e45a09ff42cb5f84268c6":{
      "scriptId":"u92"},
    "66091384b279416e88d56499c111e7da":{
      "scriptId":"u93"},
    "bc9b66ac38b54d45aa6b2f1ccb2c09d8":{
      "scriptId":"u94"},
    "d224c6022f2941c7999840d583c90572":{
      "scriptId":"u95"},
    "5c4f7f06e2cb43f19ffe22b5c1e103a5":{
      "scriptId":"u96"},
    "959606aef7754fd2b72bdc2488d95e48":{
      "scriptId":"u97"},
    "3df9797bcee94e5883813e62dddba9f7":{
      "scriptId":"u98"},
    "5c284c4e03884afa8ac14a75348dc265":{
      "scriptId":"u99"},
    "3735b10105bf440ea506e5a086da4339":{
      "scriptId":"u100"},
    "272301e5baae4304929b726da44d1680":{
      "scriptId":"u101"},
    "656ce739be30435ead4584ebf2993bee":{
      "scriptId":"u102"},
    "6b6455cb923849349cbeac82201050b4":{
      "scriptId":"u103"},
    "039c90a1067941418ae50bd1953e1eca":{
      "scriptId":"u104"},
    "8f05a4383df845adac07e6a8bbcf5ed2":{
      "scriptId":"u105"},
    "3b0979833c034b949dc9f014584f08f4":{
      "scriptId":"u106"},
    "91344cedef71482da1c55eb9c8abc1bc":{
      "scriptId":"u107"},
    "55cb9caa30b6431fb60145b4da68e223":{
      "scriptId":"u108"},
    "5292775bdcb74a9bbdd1276d1d295a71":{
      "scriptId":"u109"},
    "1750b76ea1224257a5bdf65a3b445610":{
      "scriptId":"u110"},
    "a0310a8681c44fac8483ebcc9c594c08":{
      "scriptId":"u111"},
    "7725e183c47b46fbb7f650ff0e9351bf":{
      "scriptId":"u112"},
    "4eac9e27ae0949d985ef8c51916ea5ee":{
      "scriptId":"u113"},
    "271b998d5a274c1e947a4b3993f4ad1f":{
      "scriptId":"u114"},
    "ed792024f6b141299e745c942059a4c5":{
      "scriptId":"u115"},
    "4b6cc68c28274f4aaa683c4d77b5f78c":{
      "scriptId":"u116"},
    "009c561c0464497c81ababf757acc591":{
      "scriptId":"u117"},
    "e3ba0e5b70d04c898ec119de5ea827da":{
      "scriptId":"u118"},
    "5e93e6d3bf1a48e092ddfe1e8201e7e4":{
      "scriptId":"u119"},
    "91f562e5ca174b87bf22cc90531f0bf5":{
      "scriptId":"u120"},
    "e960ec3898a848fbae6f4f0f230ae781":{
      "scriptId":"u121"},
    "723c7c3e4ce1445ea310fc70a96fb276":{
      "scriptId":"u122"},
    "a8aa1723f3b242158d0f748101787a78":{
      "scriptId":"u123"},
    "8df78616ff844d6e919846ef20ea4fed":{
      "scriptId":"u124"},
    "fef5ba7cd2404fda8f2ef97dbe55a5e6":{
      "scriptId":"u125"},
    "8db59e9005164d96808628e943c0efe0":{
      "scriptId":"u126"},
    "51bd028d31ca435ea2304581a938faa1":{
      "scriptId":"u127"},
    "853a720a522245b1ad6c2680727b461d":{
      "scriptId":"u128"},
    "270eea34c5b04e818ffdb00626dc1914":{
      "scriptId":"u129"},
    "e8fb7dfc507c45d4975fe925524feb63":{
      "scriptId":"u130"},
    "f224a30f24ea4243bccba7ec995eceb3":{
      "scriptId":"u131"},
    "92da21720a494f688d10be077154a327":{
      "scriptId":"u132"},
    "63b8d94496274429b26bba9e7f2ee57a":{
      "scriptId":"u133"},
    "3dbda1bc04a04bb5b7070b8331973406":{
      "scriptId":"u134"},
    "15c8ff1f53b449ef978de9b1a3658791":{
      "scriptId":"u135"},
    "56fc86d32ccc464fa7d0284a5b6cde1e":{
      "scriptId":"u136"},
    "be907d098c2b4159929bf9338176fda5":{
      "scriptId":"u137"},
    "7ed7fa6ff25d45fe9b51a3ada2fc01df":{
      "scriptId":"u138"},
    "7e78be9c1530448c9abb3a3520b97b7b":{
      "scriptId":"u139"},
    "69147be70ae548eb8a436d7fa08903cc":{
      "scriptId":"u140"},
    "6211a7f56c4d4ad78390a178c435a9b0":{
      "scriptId":"u141"},
    "b1b89af4b36a4318a9c9111b3ebf5c8a":{
      "scriptId":"u142"},
    "04038f9ee86a41dea497ee2aa85c3b95":{
      "scriptId":"u143"},
    "aaa6652102bb4a808462100f73e283da":{
      "scriptId":"u144"},
    "ebb02fbc8ee745418a1550bfd940786c":{
      "scriptId":"u145"}}});