$axure.loadCurrentPage({
  "url":"企业舆情同步服务.html",
  "generationDate":new Date(1662526086904.75),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"d92e27baf01a467f9ee6d1ddfc061f69",
    "type":"Axure:Page",
    "name":"企业舆情同步服务",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"4265f2512d78486db711abc36e6b1d3b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":70,
              "y":110},
            "size":{
              "width":340,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"532b111145604b688741b09e6d932a99",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":70,
                  "y":110},
                "size":{
                  "width":340,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "4265f2512d78486db711abc36e6b1d3b":{
      "scriptId":"u0"},
    "532b111145604b688741b09e6d932a99":{
      "scriptId":"u1"}}});