$axure.loadCurrentPage({
  "url":"客户经理.html",
  "generationDate":new Date(1662526079169.64),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"b9499109d59845a18d8b1cc7e5f0e478",
    "type":"Axure:Page",
    "name":"客户经理",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"6508169135b3409299134e9b189aa300",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":70,
              "y":40},
            "size":{
              "width":970,
              "height":760}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"53d9f549291c4bd6b681f99bc1eec801",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":70,
                  "y":40},
                "size":{
                  "width":970,
                  "height":760}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/客户经理/u0.png"}},
{
          "id":"c24aca317dbf4d759117eecbbf481cf9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":90,
              "y":60},
            "size":{
              "width":230,
              "height":230}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2ea6471d7f844bfe8d8191a3dafa7edb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":90,
                  "y":60},
                "size":{
                  "width":230,
                  "height":230}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/客户经理/u2.png"}},
{
          "id":"241f6ea7d21f4ae3b52c9295611b7eb3",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":90,
              "y":60},
            "size":{
              "width":230,
              "height":230}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"71c4d87bb9e44d9e8c739dbcdc549c7f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":90,
                  "y":60},
                "size":{
                  "width":230,
                  "height":230}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/客户经理/u4.png"}},
{
          "id":"f407b91254224e6180740cc8d2fcd67a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":330,
              "y":60},
            "size":{
              "width":240,
              "height":230}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b243e1dd0efa4cd39a71b71056b1db88",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":330,
                  "y":60},
                "size":{
                  "width":240,
                  "height":230}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/客户经理/u6.png"}},
{
          "id":"f02c2eb24609427996434606a2cc1516",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":585,
              "y":60},
            "size":{
              "width":255,
              "height":230},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"94da48adc9484f71a6394593e4293003",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":585,
                  "y":60},
                "size":{
                  "width":255,
                  "height":230},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/客户经理/u8.png"}},
{
          "id":"f9955ca4d09c4bbf881f11f420d3bf6f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":90,
              "y":300},
            "size":{
              "width":750,
              "height":240}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0fce59101665411597e7d0d9e0bd76e1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":90,
                  "y":300},
                "size":{
                  "width":750,
                  "height":240}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/客户经理/u10.png"}},
{
          "id":"594651d7d8c64588b9211475c5f74748",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":110,
              "y":340},
            "size":{
              "width":710,
              "height":178}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"99136a1289fa405d8f767e24b5df246e",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "size":{
                  "width":202,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"cc37e2ac7a83435b8b85e2ac56d1c324",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "size":{
                      "width":202,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/客户经理/u13.png"}},
{
              "id":"15ebb2de31e6400282e54b98ffad0496",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":30},
                "size":{
                  "width":202,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"a9eb195c98a04784b268d2bc652c2124",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":30},
                    "size":{
                      "width":202,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/客户经理/u21.png"}},
{
              "id":"e26c795b8cc44f198b31961ac86069e6",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":66},
                "size":{
                  "width":202,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"63efef1ea8bd485e8c71ada23fa1870c",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":66},
                    "size":{
                      "width":202,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/客户经理/u21.png"}},
{
              "id":"0c09f89070604da3a3bb5d0ae1e6ebd0",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":281,
                  "y":0},
                "size":{
                  "width":313,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"7dc30c76132749a28fab0c0271983572",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":281,
                      "y":0},
                    "size":{
                      "width":313,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/客户经理/u17.png"}},
{
              "id":"bef7ca7852a14ed698aa646f20f65337",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":281,
                  "y":30},
                "size":{
                  "width":313,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"a2476ea3829c4b9ebedabf78fe9f0a15",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":281,
                      "y":30},
                    "size":{
                      "width":313,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/客户经理/u25.png"}},
{
              "id":"eddb6bf5834c47e7831e87718ae8c132",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":281,
                  "y":66},
                "size":{
                  "width":313,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"497bf05d40bc435e97cc628020dd2250",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":281,
                      "y":66},
                    "size":{
                      "width":313,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/客户经理/u25.png"}},
{
              "id":"d324d6bd652a421ba244dfb5fae6bbe9",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":594,
                  "y":0},
                "size":{
                  "width":116,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"4ec4c34236814b4ca47f50eabc09ed1b",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":594,
                      "y":0},
                    "size":{
                      "width":116,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/客户经理/u19.png"}},
{
              "id":"0199277cdd6c4e6f956f49f64c41c0b6",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":594,
                  "y":30},
                "size":{
                  "width":116,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"21633cb8b22e43f8876dee25ae9cf74d",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":594,
                      "y":30},
                    "size":{
                      "width":116,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/客户经理/u27.png"}},
{
              "id":"2bfa5fd83c704e47a47dd652c83a6d49",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":594,
                  "y":66},
                "size":{
                  "width":116,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"7412dc4254e4446e85c9dccf158c647f",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":594,
                      "y":66},
                    "size":{
                      "width":116,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/客户经理/u27.png"}},
{
              "id":"b9bdaf24e89144028a1f051449c0bdd7",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":202,
                  "y":0},
                "size":{
                  "width":79,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"3ee23a60e32349bbbe1b299d62cb4fcc",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":202,
                      "y":0},
                    "size":{
                      "width":79,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/客户经理/u15.png"}},
{
              "id":"a03559d3b2424326bf435fc0a94e14d2",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":202,
                  "y":30},
                "size":{
                  "width":79,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"ab90684f0eb44ff9a3b210f5747a4bab",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":202,
                      "y":30},
                    "size":{
                      "width":79,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/客户经理/u23.png"}},
{
              "id":"f96ffa30af5b4fc5830c519f1b69b928",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":202,
                  "y":66},
                "size":{
                  "width":79,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"15f76d45ca3e4327b86fc5285d0bb50a",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":202,
                      "y":66},
                    "size":{
                      "width":79,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/客户经理/u23.png"}},
{
              "id":"ac0ac9f76476498b89dde49c3a964cce",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":102},
                "size":{
                  "width":202,
                  "height":38}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"633032e4613b4364b6382c88043b4803",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":102},
                    "size":{
                      "width":202,
                      "height":38}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/客户经理/u37.png"}},
{
              "id":"c7f128a9bff24e23b7bebe3d50ee57cd",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":202,
                  "y":102},
                "size":{
                  "width":79,
                  "height":38}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"76967cb0e9fb482cb3873ad4fe64ac39",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":202,
                      "y":102},
                    "size":{
                      "width":79,
                      "height":38}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/客户经理/u39.png"}},
{
              "id":"8a556f5306a848789c8dc176143c5555",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":281,
                  "y":102},
                "size":{
                  "width":313,
                  "height":38}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"560e1c92d394489c83b7b86913d8a0d8",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":281,
                      "y":102},
                    "size":{
                      "width":313,
                      "height":38}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/客户经理/u41.png"}},
{
              "id":"c2e75ce9074a4e11b6ff9d49452ba77c",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":594,
                  "y":102},
                "size":{
                  "width":116,
                  "height":38}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"50638e493ff749578ca227d365a5f3c1",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":594,
                      "y":102},
                    "size":{
                      "width":116,
                      "height":38}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/客户经理/u43.png"}},
{
              "id":"cc01e002257f4244bbb6fe8c60a59fcc",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":140},
                "size":{
                  "width":202,
                  "height":38}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"b1d7b0096ecb45cc99ca9f9566930822",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":140},
                    "size":{
                      "width":202,
                      "height":38}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/客户经理/u45.png"}},
{
              "id":"01c4f70d7ab94d678b29b357bf805481",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":202,
                  "y":140},
                "size":{
                  "width":79,
                  "height":38}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"c7f6e1d23fcd4bcdb6d15841c430b35b",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":202,
                      "y":140},
                    "size":{
                      "width":79,
                      "height":38}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/客户经理/u47.png"}},
{
              "id":"5d21bec1178946d79c948865f8f09e1c",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":281,
                  "y":140},
                "size":{
                  "width":313,
                  "height":38}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"97eeb88ca465467482f8fb929676efdf",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":281,
                      "y":140},
                    "size":{
                      "width":313,
                      "height":38}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/客户经理/u49.png"}},
{
              "id":"dff73e9e6f6b4dc4add0663afd9566a5",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":594,
                  "y":140},
                "size":{
                  "width":116,
                  "height":38}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"3e61853d481b46f48ebc9b88e0102b60",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":594,
                      "y":140},
                    "size":{
                      "width":116,
                      "height":38}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/客户经理/u51.png"}}]},
{
          "id":"4d553b878c9a450cad538772494ef6bf",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":206,
              "y":302},
            "size":{
              "width":129,
              "height":38}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"62267242f0e64d1bb78ddae8ed61c14a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":206,
                  "y":302},
                "size":{
                  "width":129,
                  "height":38}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"801a10b73130415c93c1703cbdb73ddd",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "underline":true,
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":96,
              "y":518},
            "size":{
              "width":54,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7c09ef1aa7564372b8ab9ecfd11c7074",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "underline":true,
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":96,
                  "y":518},
                "size":{
                  "width":54,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"68caccaab45c4237bc5ebff2ee176248",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":620,
              "y":513},
            "size":{
              "width":218,
              "height":27},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"13f3e7889cd8415e88fd1a3f5f29e524",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":620,
                  "y":513},
                "size":{
                  "width":218,
                  "height":27},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/客户经理/u57.png"}},
{
          "id":"f1f92de43ba44c2390891f9d5e5b22e9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":360,
              "y":70},
            "size":{
              "width":59,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"57c295bdb78646eea05d437dc1909067",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":360,
                  "y":70},
                "size":{
                  "width":59,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "6508169135b3409299134e9b189aa300":{
      "scriptId":"u0"},
    "53d9f549291c4bd6b681f99bc1eec801":{
      "scriptId":"u1"},
    "c24aca317dbf4d759117eecbbf481cf9":{
      "scriptId":"u2"},
    "2ea6471d7f844bfe8d8191a3dafa7edb":{
      "scriptId":"u3"},
    "241f6ea7d21f4ae3b52c9295611b7eb3":{
      "scriptId":"u4"},
    "71c4d87bb9e44d9e8c739dbcdc549c7f":{
      "scriptId":"u5"},
    "f407b91254224e6180740cc8d2fcd67a":{
      "scriptId":"u6"},
    "b243e1dd0efa4cd39a71b71056b1db88":{
      "scriptId":"u7"},
    "f02c2eb24609427996434606a2cc1516":{
      "scriptId":"u8"},
    "94da48adc9484f71a6394593e4293003":{
      "scriptId":"u9"},
    "f9955ca4d09c4bbf881f11f420d3bf6f":{
      "scriptId":"u10"},
    "0fce59101665411597e7d0d9e0bd76e1":{
      "scriptId":"u11"},
    "594651d7d8c64588b9211475c5f74748":{
      "scriptId":"u12"},
    "99136a1289fa405d8f767e24b5df246e":{
      "scriptId":"u13"},
    "cc37e2ac7a83435b8b85e2ac56d1c324":{
      "scriptId":"u14"},
    "b9bdaf24e89144028a1f051449c0bdd7":{
      "scriptId":"u15"},
    "3ee23a60e32349bbbe1b299d62cb4fcc":{
      "scriptId":"u16"},
    "0c09f89070604da3a3bb5d0ae1e6ebd0":{
      "scriptId":"u17"},
    "7dc30c76132749a28fab0c0271983572":{
      "scriptId":"u18"},
    "d324d6bd652a421ba244dfb5fae6bbe9":{
      "scriptId":"u19"},
    "4ec4c34236814b4ca47f50eabc09ed1b":{
      "scriptId":"u20"},
    "15ebb2de31e6400282e54b98ffad0496":{
      "scriptId":"u21"},
    "a9eb195c98a04784b268d2bc652c2124":{
      "scriptId":"u22"},
    "a03559d3b2424326bf435fc0a94e14d2":{
      "scriptId":"u23"},
    "ab90684f0eb44ff9a3b210f5747a4bab":{
      "scriptId":"u24"},
    "bef7ca7852a14ed698aa646f20f65337":{
      "scriptId":"u25"},
    "a2476ea3829c4b9ebedabf78fe9f0a15":{
      "scriptId":"u26"},
    "0199277cdd6c4e6f956f49f64c41c0b6":{
      "scriptId":"u27"},
    "21633cb8b22e43f8876dee25ae9cf74d":{
      "scriptId":"u28"},
    "e26c795b8cc44f198b31961ac86069e6":{
      "scriptId":"u29"},
    "63efef1ea8bd485e8c71ada23fa1870c":{
      "scriptId":"u30"},
    "f96ffa30af5b4fc5830c519f1b69b928":{
      "scriptId":"u31"},
    "15f76d45ca3e4327b86fc5285d0bb50a":{
      "scriptId":"u32"},
    "eddb6bf5834c47e7831e87718ae8c132":{
      "scriptId":"u33"},
    "497bf05d40bc435e97cc628020dd2250":{
      "scriptId":"u34"},
    "2bfa5fd83c704e47a47dd652c83a6d49":{
      "scriptId":"u35"},
    "7412dc4254e4446e85c9dccf158c647f":{
      "scriptId":"u36"},
    "ac0ac9f76476498b89dde49c3a964cce":{
      "scriptId":"u37"},
    "633032e4613b4364b6382c88043b4803":{
      "scriptId":"u38"},
    "c7f128a9bff24e23b7bebe3d50ee57cd":{
      "scriptId":"u39"},
    "76967cb0e9fb482cb3873ad4fe64ac39":{
      "scriptId":"u40"},
    "8a556f5306a848789c8dc176143c5555":{
      "scriptId":"u41"},
    "560e1c92d394489c83b7b86913d8a0d8":{
      "scriptId":"u42"},
    "c2e75ce9074a4e11b6ff9d49452ba77c":{
      "scriptId":"u43"},
    "50638e493ff749578ca227d365a5f3c1":{
      "scriptId":"u44"},
    "cc01e002257f4244bbb6fe8c60a59fcc":{
      "scriptId":"u45"},
    "b1d7b0096ecb45cc99ca9f9566930822":{
      "scriptId":"u46"},
    "01c4f70d7ab94d678b29b357bf805481":{
      "scriptId":"u47"},
    "c7f6e1d23fcd4bcdb6d15841c430b35b":{
      "scriptId":"u48"},
    "5d21bec1178946d79c948865f8f09e1c":{
      "scriptId":"u49"},
    "97eeb88ca465467482f8fb929676efdf":{
      "scriptId":"u50"},
    "dff73e9e6f6b4dc4add0663afd9566a5":{
      "scriptId":"u51"},
    "3e61853d481b46f48ebc9b88e0102b60":{
      "scriptId":"u52"},
    "4d553b878c9a450cad538772494ef6bf":{
      "scriptId":"u53"},
    "62267242f0e64d1bb78ddae8ed61c14a":{
      "scriptId":"u54"},
    "801a10b73130415c93c1703cbdb73ddd":{
      "scriptId":"u55"},
    "7c09ef1aa7564372b8ab9ecfd11c7074":{
      "scriptId":"u56"},
    "68caccaab45c4237bc5ebff2ee176248":{
      "scriptId":"u57"},
    "13f3e7889cd8415e88fd1a3f5f29e524":{
      "scriptId":"u58"},
    "f1f92de43ba44c2390891f9d5e5b22e9":{
      "scriptId":"u59"},
    "57c295bdb78646eea05d437dc1909067":{
      "scriptId":"u60"}}});